### ISSUE TITLE
sentiment analysis project3 does not consistently convert words to lowercase

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#100]
The solution code for mini-project 3 converts text to all lowercase in the run function.  However, it does not convert all training data words to lowercase when building the dictionary of possible inputs (pre_process_data function).  This isn't causing a noticeable issue here because it appears that the raw text file is already all lowercase.  However, the code itself is inconsistent, and wouldn't work if the text were not already converted to lowercase.

**Comment by clapollo** [comment]
This is half finished. I made notes for the TFLearn sentiment analysis, but will have to update the Trask notebooks tomorrow.

**Comment by clapollo** [comment]
Notebooks have been replaced with many changes, including this one.
