### ISSUE TITLE
Script bug in the python script used for the "How To Make A Neural Network" lecture

### ISSUE THREAD

**Issue by seyedrezamirkhani** [udacity/dlnd-issue-reports#101]
The main function definition is wrong it is using = instead of ==. So it should be if __name__ == '__main__':

**Comment by oritavital** [comment]
Thanks for your comment.
The live sessions sometimes has bugs in them, and Siraj is trying to comment on them all. I assume this one should be pretty easy to spot, but we will pass the feedback.
