### ISSUE TITLE
Question Incomplete - Confusion Matrix

### ISSUE THREAD

**Issue by vatsl** [udacity/dlnd-issue-reports#102]
In the Confusion Matrix quiz under Model Evaluation and Validation, the question should specify which points are positive and which are negative instead of just assuming that blue are positive and red negative. It can be the other way as well.

**Comment by vikrant2k** [comment]
Hi ColdKnight, 
Question is explained in video

**Comment by vatsl** [comment]
Agreed, but many people actually skip the videos if they are familiar with the topics.
Don't you think that the questions should be listing all the details?

**Comment by vikrant2k** [comment]
Ya it should be.
