### ISSUE TITLE
Assumptions in "Sentiment analysis with TFLearn"

### ISSUE THREAD

**Issue by renatolfc** [udacity/dlnd-issue-reports#103]
Both mat's and trask's notebooks assume you will call split with a single space argument (' '). If you call split() without arguments, strings will be split in other whitespace as well, causing the code to behave differently.

Although it doesn't take a genius to figure this out, perhaps this should've been mentioned *earlier* in the notebook.

**Comment by trovao** [comment]
Both mat's and trask's notebooks assume you will call split with a single space argument (' '). If you call split() without arguments, strings will be split in other whitespace as well, causing the code to behave differently.

Although it doesn't take a genius to figure this out, perhaps this should've been mentioned *earlier* in the notebook.

**Comment by clapollo** [comment]
This is half done. I added some comments in the TFLearn notebooks, but will need to do update the Trask notebooks tomorrow.

**Comment by clapollo** [comment]
This has been addressed in the latest version of the notebooks.
