### ISSUE TITLE
Abusing dot product for matrix summation

### ISSUE THREAD

**Issue by kittle31** [udacity/dlnd-issue-reports#106]
all the math equations show use of a summation, yet the calls to numpy use the dot product function, where dot product is traditionally a function done on Vectors, and not on a Matrix.

maybe start with using traditional 'for' loops and then transition to using numpy later?

**Comment by clapollo** [comment]
We'll be adding a lesson in the early section on numpy. I'll be sure to take this into account and explain why this is done and what's really going on

**Comment by clapollo** [comment]
Closing because I think we've addressed this with some of the content updates. We probably still have some uses of dot that would read better as matmul, but with 2D matrices they produce the same results and we now cover that in one of the lessons.
