### ISSUE TITLE
Quiz UX: [CONTINUE] rather than [CLOSE]

### ISSUE THREAD

**Issue by jg1141** [udacity/dlnd-issue-reports#108]
When a quiz has been completed successfully, the modal which pops up suggests the answer is not quite right (i.e. it is "close" to the right answer). Please change this button to CONTINUE.

**Comment by oritavital** [comment]
Can you share a screenshot and the specific quiz you're referring to? 
I actually see "Continue" when I complete a quiz.

![quiz](https://cloud.githubusercontent.com/assets/15270934/22949289/91c4f9e6-f2b6-11e6-8c3f-a26b771ffc2a.png)

**Comment by jg1141** [comment]
Here is one with [CLOSE]:
https://github.com/jg1141/deep-learning-nanodegree/blob/master/20170216/Quiz_Close.png

from:
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/43289903-8d8b-49fb-9a19-5baa4aabc2d7/lessons/6ec4ffd6-4f5c-4b88-bdf6-f169119834f0/concepts/a222f778-c0aa-45f0-97bc-7b3caf940f5b

**Comment by oritavital** [comment]
Indeed :) 
Thanks for reporting, I'll pass it along to our classroom team.

Orit
