### ISSUE TITLE
Incorrect variable name in Miniflow > Backpropagation

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#112]
In the *The Gradient & Backpropagation* section, the 6th statement below the image is

```
l2 = Linear(s1, W2, b2)
```

This uses `s1` which isn't defined anywhere. It should probably be:

```
l2 = Linear(s, W2, b2)
```

**Comment by clapollo** [comment]
Saw this and fixed it earlier. Can you refresh your classroom to see if it's still wrong?

**Comment by kulshekhar** [comment]
just refreshed the page to see that it has been fixed :+1:
