### ISSUE TITLE
Use better fonts for code snippets

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#113]
The current font leads to some confusion. Consider the screenshot of the following snippet, for instance:

![Imgur](http://i.imgur.com/Uq4zdMA.png)

(Taken from `Miniflow` > `Backpropagation` > `The Gradient & Backpropagation`)

It isn't clear whether the first parameter is `11` (the number eleven) or `l1` (the lowercase letter `l` followed by `1`). 

While looking at the context will make things clear (in most cases), it has the potential to break the train of thought while reading.

**Comment by oritavital** [comment]
Hi

Thanks for pointing it out.
Actually, we use a different font (called Lucida Console) which does look better, but probably it doesn't always load on different platforms (which platform are you using?)

I've filed a bug on this, but you can try to download that font to your computer, refresh the page and see if that changes.

Thanks
Orit

**Comment by clapollo** [comment]
This problem isn't really with the font. The examples have broken one of the cardinal rules of programming: never use a lowercase L for a variable name because it usually looks too much like a 1. Yes, different fonts will make this more or less of a problem, but in practice it's best to just never do it. :)

**Comment by kulshekhar** [comment]
@oritavital You're right. I didn't have Lucida Console on my machine (Chrome 56 on Linux Mint 18 (~ Ubuntu 16.04))

After installing the font, it seems a lot better. This is no longer an issue for me but I'll leave this open following @clapollo's comments.

**Comment by oritavital** [comment]
I totally agree with Chris's comment, I'll pass it on to out instructors
