### ISSUE TITLE
Converting Documents to Vectors

### ISSUE THREAD

**Issue by SiRi13** [udacity/dlnd-issue-reports#116]
The quiz at the end misses a comma in the third option, which is supposed to be a correct answer.
This list
`[1, 2, 3, 4, 5, 6, 1, 7 8]` 
should be 
`[1, 2, 3, 4, 5, 6, 1, 7, 8]`
to be a correct and valid answer.

**Comment by clapollo** [comment]
Which lesson is this in? I don't recognize this quiz from the description.

**Comment by SiRi13** [comment]
In lesson 12 "Preparing for Siraj's Lesson" part 3 "Converting Documents to Vectors"

**Comment by clapollo** [comment]
Ok, thanks! I'll take a look!
