### ISSUE TITLE
Student's course progress keeps "bouncing back"

### ISSUE THREAD

**Issue by AlphaGit** [udacity/dlnd-issue-reports#117]
In the Udacity platform, the progress that a certain student may have made in a course is usually sent back to old lessons not being marked as completed.

This was usually just fixable by visiting the pending sessions, that will automatically mark them as complete.

However, in this case, my projects had been reset to "in review" (when they were actually completed already).

I've heard comments from other students that this is a very common problem, and although it seems pretty harmless, now I'm concerned that my graduation in the course may be affected by this.

**Comment by oritavital** [comment]
Hi

This happens whenever we update some of the content - the classroom marks it again as unseen.
This is helpful for you in case you want to follow up on what was changed.
You can also just ignore it, there's no need to complete all lessons for graduation.

Thanks
Orit

**Comment by AlphaGit** [comment]
@oritavital Thanks for the information! That makes sense.

What about the projects? Will they stay as submitted even though the course page indicates otherwise?

**Comment by oritavital** [comment]
once you've submitted and passed a project, you're done :)
If we're updating the project's lesson you might see the lesson itself as incomplete, but the project status should remain completed.
We've had a bug in the classroom that made it go back to "need to submit" but that should be fixed by now.

**Comment by AlphaGit** [comment]
@oritavital I have verified my own case and exactly as you said, the "need to submit" issue with projects is fixed now.

Thank you very much!
