### ISSUE TITLE
The Picture in "Categorical Cross-Entropy" Broken

### ISSUE THREAD

**Issue by tangrui** [udacity/dlnd-issue-reports#119]
The picture introducing cross entropy is broken due to the invalid permission of s3.

<Error>
<script/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>86483312FB7229CD</RequestId>
<HostId>
13IsfOMaVGQBOnNDmISbtckrt90OoBaz1c6bpASzQGpeWpVzN7JCWUVnnicM46yiGIlGG5iVCzs=
</HostId>
</Error>

**Comment by tangrui** [comment]
URL is https://s3.cn-north-1.amazonaws.com.cn/u-img/262d2f72-4eb7-427c-9e35-f1803b4a0315.

**Comment by tangrui** [comment]
Sorry, there may be some network problem with the VPN. I change another proxy, then I can see the picture.

**Comment by clapollo** [comment]
Glad you got it working!
