### ISSUE TITLE
Add comment system on less page

### ISSUE THREAD

**Issue by fushion83** [udacity/dlnd-issue-reports#122]
To product team,

 I like the programming exercise + solution tab in some of the lessons. Helpful to see the solution easily accessible and to learn from it. Good design there.

I also noticed that instructors are answering questions outside of the lessons in a separate forum and that students are actually linking back to the lesson. For example, @tuatini  mentioned in a thread above that he posted a question (https://discussions.udacity.com/t/derivatives-question/220172) - and in that question he ends up linking back to the lesson -- so the user has to jump back and forth. It's also not easy to dig up this question thread if I were to try to search for it.

Why not make it so students can ask questions directly on the lesson page rather than in a separate forum and then linking back to it anyway?

For example, maybe something like this: http://www.gmatpill.com/gmat-practice-test/gmat-problem-solving-questions/gmat-prep/Coordinate%20Triangles/question/1069

- The lesson is at the top and the Q&A discussion is at the bottom. Students can answer each other and instructors can chime in as well -- all in context of the lesson at the top. As a user, I want to be able to ask questions in context and learn from other student questions, so that I can better understand the material from multiple angles.

What do you think? If you use an existing comment system like disqus, the dev effort shouldn't be too big and the benefit can be felt across the entire Udacity platform, not just this course.

**Comment by oritavital** [comment]
That's a nice suggestion, I'll bring it up with our eng team
