### ISSUE TITLE
Incorrect error calculation in Mean Squared Error using sklearn

### ISSUE THREAD

**Issue by agoila** [udacity/dlnd-issue-reports#123]
In lesson 9: Model Evaluation and Validation, chap 5: Regression Metrics, for Mean Squared error in sklearn, the error has been calculated incorrectly as mean_absolute_error again (from the previous topic). It should be mean_squared_error.

**Comment by clapollo** [comment]
Just to clarify, this is in the **video** around 1:06. The slide is supposed to be showing the use of the `mean_squared_error`, but it erroneously re-uses the text from a previous slide and shows `mean_absolute_error`.

**Comment by agoila** [comment]
@clapollo Yes, that's correct.

**Comment by clapollo** [comment]
This is Jira issue DLND-492
