### ISSUE TITLE
As a student, I want to be able to see an estimate time to complete a lesson. This give an effort needed summary

### ISSUE THREAD

**Issue by yepesasecas** [udacity/dlnd-issue-reports#126]
For example:

Lesson 11: Intro to TFLearn
Estimated time: 2 hours

lesson 12: Preparing for Siraj's Lesson
Estimated time: 3 hours

**Comment by oritavital** [comment]
I agree :)
We actually used to have them but in the Deep Learning classroom you can't see them.
We are working on redesigning some classroom elements now and they will be added soon :)

Thanks for you feedback
Orit
