### ISSUE TITLE
Sentiment analysis with TFlearn notebook

### ISSUE THREAD

**Issue by godardt** [udacity/dlnd-issue-reports#128]
In the notebook this sentence:
> You can set the number of units in the layer with n_hidden, and set the activation function with the activation keyword. You can keep adding layers to your network by repeated calling net = tflearn.fully_connected(net, n_units).

Should be:

> You can set the number of units in the layer with **n_units**, and set the activation function with the activation keyword. You can keep adding layers to your network by repeated calling net = tflearn.fully_connected(net, n_units).

**Comment by clapollo** [comment]
Closing as duplicate of #75. Although, I do like your title better - thanks for being detailed. :)
