### ISSUE TITLE
As a student in "Handwritten Number Recognition with TFLearn and MNIST". I'm unable to download mnist data using "nist.load_data(one_hot=True)"

### ISSUE THREAD

**Issue by yepesasecas** [udacity/dlnd-issue-reports#129]
trainX, trainY, testX, testY = mnist.load_data(one_hot=True) returns:

TypeError: only integer scalar arrays can be converted to a scalar index

Stackeroverflow :
http://stackoverflow.com/questions/34010859/tensorflow-beginner-tutorial-read-data-sets-fails

**Comment by kulshekhar** [comment]
@yepesasecas  #80 might help

**Comment by yepesasecas** [comment]
Thank youn I was able to fix the issue!
