### ISSUE TITLE
wrong flappy bird instruction

### ISSUE THREAD

**Issue by ltelwest** [udacity/dlnd-issue-reports#13]

**Comment by ltelwest** [comment]
there are two mistakes:

<img width="887" alt="screen shot 2017-01-28 at 00 48 47" src="https://cloud.githubusercontent.com/assets/7994920/22391801/c0204bf4-e4f3-11e6-9ae5-9407e2f82c7a.png">

## we need python version 2.7*:

<img width="728" alt="screen shot 2017-01-28 at 00 52 21" src="https://cloud.githubusercontent.com/assets/7994920/22391868/2b99ddbe-e4f4-11e6-935f-3991b6614e87.png">

__solved by:__
 ```conda create --name=flappybird  python=2.7 ```

## and we need to install pygame:
<img width="736" alt="screen shot 2017-01-28 at 00 52 40" src="https://cloud.githubusercontent.com/assets/7994920/22391875/3dfbcaa8-e4f4-11e6-8e0b-62bb308f5388.png">
__solved by:__
```pip install pygame```

**Comment by MarkusKluge** [comment]
Flappy-Bird-Fix for Windows:   
- python has to be 3.5 
- opencv3 not opencv
- and install pygame wasnt mentioned

conda create --name=flappybird python=3.5   
activate flappybird
conda install -c menpo opencv3
pip install pygame
pip install tensorflow
git clone https://github.com/yenchenlin/DeepLearningFlappyBird.git
cd DeepLearningFlappyBird
python deep_q_network.py

**Comment by MarkusKluge** [comment]
(Tested on Windows 10 64-bit with Anaconda)

**Comment by Brok-Bucholtz** [comment]
@Mkmk93,

Thanks for the new instructions.  We've changed our instructions to work with windows.
