### ISSUE TITLE
Heart Sign as Like button

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#133]
Please change the heart sign which is a Like button. I really find it weird.

**Comment by oritavital** [comment]
To which heart sign you refer exactly?

**Comment by rahul-ahuja** [comment]
it's a like button in the udacity discussion forum.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by oritavital** [comment]
oh, got you.
We're using an external platform for our forums so unfortunately don't have a lot of control over the UI.
