### ISSUE TITLE
Lesson not matching the project

### ISSUE THREAD

**Issue by theHound9987** [udacity/dlnd-issue-reports#134]
I have been spending so much time trying to do the project and using the lesson for help. After reading the forum I'm been told I need now watch videos from Kahn. I don't feel it is fair to pay for a course then have to watch video from other sources. I was lead to believe that to take this course you did not have to know calculus, what I needed to know would be teach to me

**Comment by oritavital** [comment]
Thanks for your feedback. I agree that the pre-reqs were not clearly communicated, this is why we've added supporting material (such as Kahn Academy courses). We believe that after you'll cover the basic calculus knowledge you should be able to complete course work using mainly Udacity content.

Orit
