### ISSUE TITLE
Backpropagation Lesson

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#135]
In the lesson https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/269a4aad-9025-4354-a0ea-2623e889540a/lessons/b6deebe4-7f78-4947-b2c6-fc660ca942fb/concepts/aaeef9a2-f825-4982-ba9d-2aeb8fd615c9

Minus sign is not included in the equation of differentiation of cost wrt to w2. Is it an error?
Below is the students question on discussion forum. Thanks

https://discussions.udacity.com/t/12-backpropagation-equation/221230/2

**Comment by clapollo** [comment]
I think the minus sign got lost. It was missing in some other equations and we fixed it, but this one slipped by.  Should be better now.
