### ISSUE TITLE
DeepLearningFlappyBird.git: permission denied while cloning

### ISSUE THREAD

**Issue by mkudurma** [udacity/dlnd-issue-reports#14]

**Comment by mkudurma** [comment]
git clone git@github.com:yenchenlin/DeepLearningFlappyBird.git
Cloning into 'DeepLearningFlappyBird'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by mkudurma** [comment]
Matt said try to clone like this and it worked: 

git clone https://github.com/yenchenlin/DeepLearningFlappyBird.git

**Comment by Brok-Bucholtz** [comment]
@mkudurma,

Thanks for spotting this!  I change the instructions to use "git clone https://github.com/yenchenlin/DeepLearningFlappyBird.git".
