### ISSUE TITLE
Links to TensorFlow documentation are outdated

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#141]
The content for 'Intro to TensorFlow' contains several links to the relevant documentation for TensorFlow methods. (for example, [tf.global_variables_initializer](https://www.tensorflow.org/api_docs/python/state_ops/variable_helper_functions#global_variables_initializer), [tf.variable](https://www.tensorflow.org/api_docs/python/state_ops/variables#Variable), [tf.placeholder](https://www.tensorflow.org/api_docs/python/io_ops/placeholders#placeholder), etc)

With the release of TensorFlow 1.0. these links are outdated and lead to non-existent pages.

**Comment by clapollo** [comment]
Ok, I think I've gotten them all fixed. If you notice anything else wrong, just open another issue. Thanks!
