### ISSUE TITLE
Broken TensorFlow link

### ISSUE THREAD

**Issue by toddstrader** [udacity/dlnd-issue-reports#145]

**Comment by toddstrader** [comment]
In section 5 of Intro to TensorFlow, the Common Problems link is broken:
https://www.tensorflow.org/get_started/os_setup#common_problems

**Comment by oritavital** [comment]
Yes, we are aware of this issue. Since there's a new TensorFlow version, all documentation links have been changed. 
We're working to fix the problem and hopefully have all of them fixed soon.

Thanks for reporting!

**Comment by clapollo** [comment]
I believe all broken links are now fixed or removed.
