### ISSUE TITLE
Lesson 16 Solution

### ISSUE THREAD

**Issue by jincongho** [udacity/dlnd-issue-reports#148]
8. Quiz: Tensorflow Math - the solution cause an error. tf.substract requires tf.int32, but tf.divide returns tf.float32. So we need casting: z = tf.subtract(tf.cast(tf.divide(x,y), tf.int32),tf.constant(1))

**Comment by clapollo** [comment]
Thanks for catching that! I've corrected this, as well as added some notes on casting and some comments in the solution file about various different ways to divide.
