### ISSUE TITLE
MNIST TFLearn error when extracting dataset

### ISSUE THREAD

**Issue by dereklei** [udacity/dlnd-issue-reports#149]
Has to do with TFLearn's dataset mnist.py file.

In Intro to TFLearn's "Handwritten Digit Recognition" exercise, mnist.py is not extracting data correctly, which caused me to see this error when running mnist.load_data(one_hot=True):

TypeError: only integer scalar arrays can be converted to a scalar index

Issue has been reported on TFLearn and a solution has been provided: https://github.com/tflearn/tflearn/issues/584

**Comment by clapollo** [comment]
Closing this issue as it's a problem with older versions of TFLearn and not our code. Using the latest TFLearn resolves the issue.
