### ISSUE TITLE
Incorrect value in perceptron lesson

### ISSUE THREAD

**Issue by tyleranton** [udacity/dlnd-issue-reports#15]

**Comment by tyleranton** [comment]
<img width="782" alt="screen shot 2017-01-27 at 8 10 40 pm" src="https://cloud.githubusercontent.com/assets/3586436/22393471/cc6c9132-e4cc-11e6-9f98-addfadc214c3.png">

The phrasing in question:

"In the university acceptance example above, we used the weights...are `positive` values, the activation function will never return a 1!"

I believe this should say `negative`.

**Comment by Brok-Bucholtz** [comment]
@tyleranton,

Thanks!  I changed it to "negative.
