### ISSUE TITLE
Explanattion about different activation functions

### ISSUE THREAD

**Issue by hhsecond** [udacity/dlnd-issue-reports#154]
Activation functions was a session in the ND foundation course. But it was not discriptive enough to convince the students that why should somebody use ReLu or something else rather than sigmoid

**Comment by bdelhaisse** [comment]
It seems that what you are looking for is described in Lesson 11: Intro to TFLearn, section 2 "ReLu and Softmax Activation Functions". Is it not?
Maybe, they could add more information in this section, about other activation functions such as tanh (which is used in LSTM),...

**Comment by Brok-Bucholtz** [comment]
Thanks for bringing this up.  We'll add it to the backlog.
