### ISSUE TITLE
Sentiment Analysis - Mini Project 5 solution - ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by thoughtexpress** [udacity/dlnd-issue-reports#156]
Hello Team,
I just ran the code for the "Sentiment Analysis - Mini Project 5 solution" provided as zip file. When i run it, it gives "ZeroDivisionError: float division by zero". 
The error is on line 133 in the code - 
reviews_per_second = i / float(time.time() - start)

**Comment by thoughtexpress** [comment]
here is the link on slack for the image - https://slack-files.com/T3Q738VV1-F475553Q9-d95b2d2393

**Comment by clapollo** [comment]
It seems you are getting the same value from `time.time()` as you saw when you assigned `start`. I'm guessing one of two things is happening. 1) Your machine is very fast. 2) On some systems, Python's `time.time()` function return values only with second-level precision. In that case, you very often get duplicate results. 

To get past this error, I would recommend replacing this with something like 
```
reviews_per_second = i / (float(time.time() - start) + 0.0001)
```

I'm going through the notebooks and updating them with some hints and other changes, so I'll do something for this as part of that update.

**Comment by clapollo** [comment]
Notebooks have been replaced with many changes, including this one.
