### ISSUE TITLE
Linear Regression - code won't work

### ISSUE THREAD

**Issue by kjmcall** [udacity/dlnd-issue-reports#157]

**Comment by kjmcall** [comment]
I hand typed my own code and I'm getting an invalid syntax error on the last line =

import pandas as pd
from sklearn.linear_model import LinearRegression

#read data
bmi_life_data = pd.read_csv('bmi_life_expectancy.csv')

#train model on data
bmi_life_model = LinearRegression()
bmi_life_model.fit(bmi_life_data[['BMI']], bmi_life_data[['Life expectancy']]

#visualize results
laos_life_exp = bmi_life_model.predict(21.07931)


any help???

**Comment by clapollo** [comment]
This isn't really the place to ask for help with syntax errors in your own code. But it looks like you are missing the closing parenthesis on you next-to-last line (the call to `fit`)

**Comment by kjmcall** [comment]
Thanks - apologies for posting to inappropriate place - learning my way around.

**Comment by clapollo** [comment]
It's ok, that's why I answered your question anyway. :) But for future reference, this board is for course bug reports and change requests.
