### ISSUE TITLE
Options not visible in quiz (Regularization quiz in L18, Deep Neural Networks)

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#159]
The quiz is introduced in a video. The video ends with the options we have to choose from. However, when the video ends, these options aren't visible.

Adding the options in text/image or modifying the video to show the options after it ends would help.

**Comment by oritavital** [comment]
@clapollo , do you know how to do it in coco?

**Comment by clapollo** [comment]
Yes, I can add a comment above the question showing the three formulas. Unfortunately, the actual quiz doesn't seem to use the same css as the rest of the page, so I can't include math formulas directly in the answers. Unless, is there a way to replace the answers with images? Then I could at least make images of the formulas and use those.

**Comment by oritavital** [comment]
We've added the image, so it's easier to complete the quiz
