### ISSUE TITLE
Deep Neural Networks lesson 4, optimizer

### ISSUE THREAD

**Issue by kid1412z** [udacity/dlnd-issue-reports#164]
`cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits, y))` need to be: `cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y))`  or will raise error: `ValueError: Only call softmax_cross_entropy_with_logits with named arguments (labels=..., logits=..., ...)`

**Comment by clapollo** [comment]
Yep. The old version used to work but TF 1.0 requires the argument names. Fixed.
