### ISSUE TITLE
Wording: Sentiment Analysis with TFLearn

### ISSUE THREAD

**Issue by Aamir-Raza** [udacity/dlnd-issue-reports#165]
'The last word in our vocabulary shows up in 30 reviews out of 25000..'

Minor issue but that seems to be an assumption, would be more accurate to say that the word has 30 instances in 25000 reviews (it could be present multiple times in a single review)

**Comment by clapollo** [comment]
Agreed.

**Comment by clapollo** [comment]
Fixed in the latest versions of the notebooks
