### ISSUE TITLE
Links from nd101 pointing to nd013 which is not accessible. Please provide accessible links to Deep Leaning course

### ISSUE THREAD

**Issue by vikrant2k** [udacity/dlnd-issue-reports#168]
In CNN chapter:

Here are a few more things worth reviewing:

TensorFlow Variables.
Truncated Normal Distributions in TensorFlow (you'll want to initialize your weights with a truncated normal distribution).
How to determine the dimensions of the output based on the input size and the filter size (shown below). You'll use this to determine what the size of your filter should be.

https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/1c06a07a-17d7-438e-b31f-2d86864410fc

**Comment by clapollo** [comment]
Hi, thanks for the report. However, it helps us find and fix issues if you can be specific about the issue. Which lesson contains the broken link? 

Also, I'm not sure what you mean by those "few more things". Are you saying those sections might have broken links, too, or are you saying you think there is something else about them that needs to change? If it's something else, please create separate waffle issues so we can easily track individual requests.

Thank you!

**Comment by vikrant2k** [comment]
Hi,

1) Go to chapter 19     (WEEK 6 - IMAGE CLASSIFICATION)
2) In chapter 19 , click on section 30 (Convolutional Network in TensorFlow)
3) In paragraph 3 (Get to Link/Text "Deep Neural Network in TensorFlow")
4) "Deep Neural Network in TensorFlow" Link is pointing to other nonodegree course, so it's not accessible.

There are couple of more of more links which are pointing to other nanodegree course. 

5)  chapter 19 --> Section 31 (Using Convolution Layers in TensorFlow)
      Look for point 1 and 2 link in (  1) TensorFlow Variables. 2) Truncated Normal Distributions i) --- These links are pointing to other nonodegree course.

Thanks

**Comment by clapollo** [comment]
Thanks! Should be fixed now.
