### ISSUE TITLE
Add environment YAML files

### ISSUE THREAD

**Issue by Kumuluzz** [udacity/dlnd-issue-reports#169]

**Comment by Kumuluzz** [comment]
In one of the very first lessons about Anaconda, we were taught how to handle environments with best practices, such as saving the current environment configuration into a YAML file.

I would suggest that you create such a configuration for all the remaining projects in order for us to train this best practice.

**Comment by oritavital** [comment]
Right now, we only support AWS and the integration is already set up.
We might do this in the future, thanks for the suggestions.
