### ISSUE TITLE
Misspelling in Multiple Linear Regression quiz

### ISSUE THREAD

**Issue by rconway242** [udacity/dlnd-issue-reports#17]
If you leave the value of prediction to None, the word "prediction" is misspelled as "preiction"

**Comment by rconway242** [comment]
In addition the the "prediction" misspelling, "Make" is misspelled as "Mak" in the quiz.py text box.

**Comment by Brok-Bucholtz** [comment]
@rc242,

Thanks for letting us know.  We fixed the spelling of "make" and "prediction".

**Comment by Adosha** [comment]
@Brok-Bucholtz 
There is still error with "Make" in the "solution" tab.
