### ISSUE TITLE
Sentiment Analysis with TFLearn - video looping issue

### ISSUE THREAD

**Issue by agoila** [udacity/dlnd-issue-reports#170]
The link is here: https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/e0ad6969-6321-437a-8279-d9b20a7cd00a/lessons/cec79d13-b41a-4c61-9441-eada5b39c9e6/concepts/c29b0417-7bef-48bd-b499-ed79676b7d02

The video by Mat, explaining the notebook, seems to loop around, starting at 1:38 to 1:52 mark, with repeated sentences. 

Just a minor video processing glitch that should perhaps be looked into.

**Comment by clapollo** [comment]
Added Jira issue DLND-567

**Comment by oritavital** [comment]
Issue is fixed.
