### ISSUE TITLE
Sentiment Classification missing labels parameter

### ISSUE THREAD

**Issue by kittle31** [udacity/dlnd-issue-reports#171]
The solutions to mini-project 5 and 6 are missing the 'labels' parameter in the pre_process_data function

Project 4:
def pre_process_data(self,reviews,labels):

Project 5:
def pre_process_data(self,reviews):

Project 6:
def pre_process_data(self,reviews, polarity_cutoff,min_count):

**Comment by clapollo** [comment]
Notebooks have been replaced with many changes, including this one.
