### ISSUE TITLE
Inverted images for image-classification tests

### ISSUE THREAD

**Issue by raphey** [udacity/dlnd-issue-reports#173]
test images are displayed inverted. I found this:
http://stackoverflow.com/questions/39925420/bizzare-matplotlib-behaviour-in-displaying-images-cast-as-floats
When I edited helper.py to take away the *255 on line 158, the images no longer displayed inverted.

**Comment by raphey** [comment]
Here's an example of an inverted test image, from a different student: https://www.dropbox.com/s/2vsijiycavmhcuy/Screenshot%202017-02-26%2021.40.54.png?dl=0

**Comment by raphey** [comment]
I found another fix, inspired by the info in that stackoverflow page. I changed line 158 to:
`axies[image_i][0].imshow((feature*255).astype(np.uint8))`

**Comment by clapollo** [comment]
This has been updated in the latest version of the notebook.
