### ISSUE TITLE
Sentiment Analysis - Mini Project 5 Issue

### ISSUE THREAD

**Issue by Gavsum** [udacity/dlnd-issue-reports#174]
Instruction was to modify code to fix optimization via multiplying weights by 1 = remove the mult operation, and 0 weights by doing nothing...

Answer in Trasks solution moved a bunch of other functionality into the train function to achieve this with no notification that students would have to do so.

****INCOMPLETE INSTRUCTIONS****

**Comment by clapollo** [comment]
The notebooks have been modified with many changes to add more guidance throughout.
