### ISSUE TITLE
Convolutional Network inaccessible link

### ISSUE THREAD

**Issue by xCASx** [udacity/dlnd-issue-reports#175]
In "Using Convolution Layers in TensorFlow" section of "Convolutional Network" lesson, there is a link to details about TensorFlow variables:
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/1c06a07a-17d7-438e-b31f-2d86864410fc
It leads to my classroom page with the next error:
"You are not allowed to access this Nanodegree Program. Is your subscription paused, or past due?"

**Comment by xCASx** [comment]
Oh, the same for the next link "Truncated Normal Distributions":
https://classroom.udacity.com/nanodegrees/nd013/parts/fbf77062-5703-404e-b60c-95b78b2f3f9e/modules/6df7ae49-c61c-4bb2-a23e-6527e69209ec/lessons/91cc6685-08df-4277-b53d-3a792b02420d/concepts/1c06a07a-17d7-438e-b31f-2d86864410fc

**Comment by xCASx** [comment]
And it appears that links are the same actually.

**Comment by clapollo** [comment]
I think these were fixed yesterday and you might be seeing a cached version. Can you refresh your page and let me know if they are still broken?

**Comment by xCASx** [comment]
Yes, now it's working fine. Thank you!
