### ISSUE TITLE
batch-size instructions in project 2 notebook

### ISSUE THREAD

**Issue by raphey** [udacity/dlnd-issue-reports#178]
I think this instruction should be modified:
"Set batch_size to the highest number that your machine has memory for."
I set the batch size to 256, but later I found out that setting it to smaller values led to noticeably better results. See this: http://stats.stackexchange.com/questions/164876/tradeoff-batch-size-vs-number-of-iterations-to-train-a-neural-network
On one hand, there are plenty of hyperparameters to worry about already, but it also seems good not to steer folks towards a less successful approach. Thank you!

**Comment by e7dud7e** [comment]
I agree, good point!
