### ISSUE TITLE
L23: RNN, sec1 - typo in video

### ISSUE THREAD

**Issue by bdelhaisse** [udacity/dlnd-issue-reports#179]
In Lesson 3 - RNN, section 1 "Intro to RNNs", there is a typo in the formula that appears at 2:02 in the video:
h_t = f(W_{hh} h_{t-1} + W_{x} h_{xt})
should be
h_t = f(W_{hh} h_{t-1} + W_{xh} x_{t})

**Comment by clapollo** [comment]
Created Jira issue DLND-600
