### ISSUE TITLE
cloud computing: 1.AWS typos

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#181]
"It's possible to purchase your own NVIDIA GPU, but there's more too it than just".  
Suggestion: Replace "too" with "to".

"In the next few sections, we'll go over the steps from nothing to running a neural network on a amazon server."

Suggestion: replace "a amazon server" with "an amazon server".

**Comment by clapollo** [comment]
Thanks! All fixed. :)
