### ISSUE TITLE
Link to removed Siraj YouTube video

### ISSUE THREAD

**Issue by jg1141** [udacity/dlnd-issue-reports#182]
On the page "1. How to Predict Stock Prices Easily"
the link to
https://www.youtube.com/watch?v=OU_Kp3aphVk
is a removed video.

Click *here* for Siraj's weekly live session about How to use Tensorflow time series.

https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/a8b3293a-bb3e-4247-927e-739fbf3f5515/lessons/bcb4df10-109b-4ffe-aa6e-b46255cabea8/concepts/c9fb29da-a5f6-48fe-b7c2-e9d0e1b5a503

**Comment by jg1141** [comment]
You probably want
https://youtu.be/hhJIztWR_vo

**Comment by clapollo** [comment]
Fixed. Thanks!
