### ISSUE TITLE
Deep Neural Networks section 4 explanation of reshape, flip dimensions

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#184]
In section 4 "Deep Neural Network in TensorFlow":

The explanation for the line: 
x_flat = tf.reshape(x, [-1, n_input])

"The tf.reshape() function above reshapes the 28px by 28px matrices in x into vectors of 784px by 1px"

Since the code reshapes x_flat to a 1 row by 784 column vector, I think it's more accurate for the text to say "vectors of 1px by 784px", since they're row vectors.

**Comment by clapollo** [comment]
I agree. I though the same thing when I read it. I'll make this change as soon as I get the chance.

**Comment by e7dud7e** [comment]
^_^
