### ISSUE TITLE
Convolutional NN Section 9 "Parameters": incorrect explanation of variables and units

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#185]
The following text from Section 9 "Parameters" incorrectly states:

"Given our input layer has a volume of W, our filter has a volume (height * width * depth) of F, we have a stride of S, and a padding of P, the following formula gives us the volume of the next layer: (W−F+2P)/S+1."

This is incorrectly stating that W is a volume, and that F is a volume by stating that F is the product of height, width, depth.

The formula (W−F+2P)/S+1 is actually just used for calculating the next layer's height based on the previous layer's height; likewise, it can be used to calculate the next layer's width based on the previous layer's width.

A correct explanation is in the cs231n's text, where it refers to W as input volume "size", and not volume itself.  It refers to "F" as the receptive field size, and does not state that F is equal to height * width * depth.

Here is the cs231n text below:
"We can compute the spatial size of the output volume as a function of the input volume size (W), the receptive field size of the Conv Layer neurons (F), the stride with which they are applied (S), and the amount of zero padding used (P) on the border. You can convince yourself that the correct formula for calculating how many neurons “fit” is given by (W−F+2P)/S+1(W−F+2P)/S+1."

**Comment by Brok-Bucholtz** [comment]
@e7dud7e 

It looks like this has been fixed.  Let us know if you still see the issue.
