### ISSUE TITLE
Miniflow wrong explanation for setting value

### ISSUE THREAD

**Issue by traveling-desi** [udacity/dlnd-issue-reports#186]
I am referring to this:

https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/269a4aad-9025-4354-a0ea-2623e889540a/lessons/b6deebe4-7f78-4947-b2c6-fc660ca942fb/concepts/9f4a9317-ce3b-4cf0-93c8-68080d2742f3

Specifically this portion:

> For the Input node, the forward method appears to set the value.
> 
> That's not the case with other node subclasses, though. For those subclasses, the value is set when you run topological_sort. See here:
> 
```
> def topological_sort(feed_dict):
>     ...
>     if isinstance(n, Input):
>         n.value = feed_dict[n]

```
This is wrong. As you can see above the values for the input nodes are set directly in the topological sort. While the values for all the other nodes are set in the forward_pass:

```
>    for n in sorted_nodes:
>         n.forward()
> 
```

Please check and correct.

**Comment by lcrucks** [comment]
Thanks for catching this; it's been fixed!
