### ISSUE TITLE
Project 2 Cannot do SSH

### ISSUE THREAD

**Issue by dundunee** [udacity/dlnd-issue-reports#187]
I typed in terminal "ssh to the carnd@x.x.x.x" and waited a few seconds but the result said "Connection timed out"
How do i solve this error?
Thanks

**Comment by clapollo** [comment]
Hello. This board is for posting bugs with the content, not for asking questions. However, I will answer this one while I'm here: your should be calling `udacity@x.x.x.x`, not "carnd"
