### ISSUE TITLE
Skip-Grams-Solution

### ISSUE THREAD

**Issue by jw6731** [udacity/dlnd-issue-reports#188]

**Comment by oritavital** [comment]
Can you add more information to the issue?

**Comment by jw6731** [comment]
Running Anna KaRNNA from Deep Learning/tensorboard.

After one iteration I got the error shown below.  I have tried it on two 
systems with and without gpu.

The other notebooks seem to run ok.  I searched the problem and found 
this possible fix:

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size,state_is_tuple=False) but 
it made no difference.

Also saw “/ValueError/:/Could not flatten dictionary/./Key 
had/2/elements/, but value/had/1/elements/.” There is an open issue on 
GitHub for this error.

Epoch 1/1  Iteration 1/178 Training loss: 4.4196 3.6244 sec/batch

---------------------------------------------------------------------------
ValueError                                 Traceback (most recent call last)
<ipython-input-14-2700c39b5d2e>  in<module>() 34 35 batch_loss, new_state, _ = sess.run([model.cost, 
model.final_state, model.optimizer], ---> 36feed_dict=feed) 37 loss += 
batch_loss38 end = 
time.time()/home/williamj/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py 
in run(self, fetches, feed_dict, options, run_metadata) 765 try:766 
result = self._run(None, fetches, feed_dict, options_ptr, --> 
767run_metadata_ptr) 768 if run_metadata:769 proto_data = 
tf_session.TF_GetBuffer(run_metadata_ptr)/home/williamj/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py 
in _run(self, handle, fetches, feed_dict, options, run_metadata) 912 # 
Validate and process feed_dict.913 if feed_dict:--> 914feed_dict = 
nest.flatten_dict_items(feed_dict)915 for feed, feed_val in 
feed_dict.items():916 for subfeed, subfeed_val in _feed_fn(feed, 
feed_val):/home/williamj/anaconda3/lib/python3.5/site-packages/tensorflow/python/util/nest.py 
in flatten_dict_items(dictionary) 185 "Could not flatten dictionary. Key 
had %d elements, but value had "186 "%d elements. Key: %s, value: 
%s."--> 187% (len(flat_i), len(flat_v), flat_i, flat_v)) 188 for new_i, 
new_v in zip(flat_i, flat_v):189 if new_i in flat_dictionary:ValueError: 
Could not flatten dictionary. Key had 4 elements, but value had 1 
elements. Key: [<tf.Tensor 'zeros:0' shape=(100, 512) dtype=float32>, 
<tf.Tensor 'zeros_1:0' shape=(100, 512) dtype=float32>, <tf.Tensor 
'zeros_2:0' shape=(100, 512) dtype=float32>, <tf.Tensor 'zeros_3:0' 
shape=(100, 512) dtype=float32>], value: [array([[[[ 0.03415707, 
-0.02438662, -0.01583979, ..., -0.01226605, -0.00209595, -0.0076588 ], [ 
0.01957864, -0.04630391, 0.04509495, ..., -0.05978125, -0.0168674 , 
0.03244058], [-0.02350887, -0.00221125, 0.00389434, ..., -0.00207166, 
0.0491391 , 0.00722346], ..., [ 0.01906215, -0.01510949, 0.0221403 , 
..., -0.07109054, 0.01100152, 0.02350834], [ 0.01322947, -0.02423264, 
0.02330558, ..., 0.01096372, 0.0354319 , 0.02087432], [ 0.00534444, 
-0.02822569, 0.0023931 , ..., 0.02517286, 0.02307322, -0.00535894]], [[ 
0.01656959, -0.01218898, -0.00784182, ..., -0.0061273 , -0.00104458, 
-0.00381749], [ 0.00997239, -0.02307073, 0.02223787, ..., -0.02947606, 
-0.00859914, 0.01660797], [-0.01155709, -0.00113522, 0.00191043, ..., 
-0.00104888, 0.02394134, 0.00355143], ..., [ 0.00946687, -0.00773091, 
0.01086994, ..., -0.03526407, 0.00544163, 0.01181741], [ 0.00661925, 
-0.01214675, 0.01188175, ..., 0.00536631, 0.01757672, 0.01030396], [ 
0.00271175, -0.01425989, 0.00119487, ..., 0.01248919, 0.0114154 , 
-0.00267548]]], [[[-0.00697695, -0.00221754, 0.01563704, ..., -0.0071672 
, 0.00661706, 0.00437892], [-0.00376317, 0.01952287, -0.00748795, ..., 
-0.01839129, 0.0006561 , -0.01050602], [-0.00940055, 0.01626366, 
0.00887249, ..., 0.01065583, -0.01511704, 0.01874907], ..., 
[-0.00748228, 0.01541634, 0.01510207, ..., -0.00181223, 0.00468891, 
0.00841329], [-0.01854297, -0.0145135 , 0.00255007, ..., -0.00780769, 
0.00846287, -0.02032904], [-0.01086794, 0.01909207, 0.00875651, ..., 
-0.01731759, -0.00533621, -0.01373287]], [[-0.00349085, -0.00110887, 
0.00784089, ..., -0.00356452, 0.00333135, 0.00217629], [-0.00189763, 
0.00985436, -0.00373902, ..., -0.00924777, 0.00033053, -0.00519075], 
[-0.00467782, 0.00813842, 0.00442396, ..., 0.00531289, -0.00750706, 
0.00932891], ..., [-0.00377989, 0.0077492 , 0.0076549 , ..., 
-0.00090228, 0.00235562, 0.00416948], [-0.00934922, -0.00727872, 
0.00126304, ..., -0.00389152, 0.0042359 , -0.01011412], [-0.00544385, 
0.00957915, 0.0043804 , ..., -0.00863541, -0.00268704, -0.00680509]]]], 
dtype=float32)].

**Comment by mcleonard** [comment]
I'm confused here. Is this about the Skip Grams code or Anna KaRNNa code from the tensorboard notebooks?
