### ISSUE TITLE
Can't access project 2 course

### ISSUE THREAD

**Issue by carefulguy** [udacity/dlnd-issue-reports#189]

**Comment by carefulguy** [comment]
Lesson 2 can't be accessed through syllabus.  Pends then returns to Syllabus.

**Comment by clapollo** [comment]
Which lesson exactly? Lesson 2 on Anaconda? Or the second lesson in "Project 2: Image Classification" (which is the one for the actual Project 2 assignment)?

I've tested them both and they seem to work for me. Can you copy the link you are trying to load and then I can test it? Also, do you have anything unusual about your connection to the interest, such as a proxy or VPN setup?

**Comment by e7dud7e** [comment]
I think they were referring to Project 2 Image classification.  I had the same problem today and yesterday, but now the link works again.

**Comment by efajard** [comment]
It's Project 2: Image Classification. There's only the submission webpage and no instructions to complete it (even when it was due two days ago I believe I can still do it)

**Comment by carefulguy** [comment]
Yes, it was in reference to project 2 course, but looks like the link works now.

**Comment by clapollo** [comment]
Oh, ok. I think I found out what the problem was, and it was a temporary mix up. So hopefully it should continue to work from here on out. Sorry for the inconvenience!
