### ISSUE TITLE
Intro to RNNs Transition Screen

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#190]
The screen before a lecture moves to another lecture isn't updated. 

![image](https://cloud.githubusercontent.com/assets/12501638/23826947/0fc3a98e-06ce-11e7-9aa8-5eac79240de6.png)

**Comment by clapollo** [comment]
I don't know what it was called "IntroToRNNs Render" , so I changed that. Is that what you were reporting about, or are you saying something else is wrong here?

**Comment by sahiljuneja** [comment]
@clapollo Yes. Sorry wasn't more descriptive with my issue. 

Just checked it in the lecture. Thanks for changing it! 👍
