### ISSUE TITLE
The output value in example of RNN seem to be wrong.

### ISSUE THREAD

**Issue by traveling-desi** [udacity/dlnd-issue-reports#191]
Hello!

I am referring to this video:

https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/a8b3293a-bb3e-4247-927e-739fbf3f5515/lessons/d74891dc-49c8-4569-9cab-6d508083e841/concepts/a10e7178-8abe-44bf-8c0a-6cc35dccb61a

The outputs for the first 'e' do not make sense.  The correct number is selected (and is green) but instead of it being -1, it should be the largest positive number so that the softmax probability for  it being an 'e' is the largest.

![screen shot 2017-03-11 at 6 48 41 pm](https://cloud.githubusercontent.com/assets/4754733/23828595/9b3e7338-068b-11e7-966e-080f334b7e8c.png)

Thanks

Edit1:
So, I followed the link (http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and the diagram has been taken from there. The diagram specifically is for a network still under training. Thats not clear from the udacity video, but the above diagram wouldn't be wrong for a network still under training. So you can ignore this issue if you want to or add an explanation.

**Comment by oritavital** [comment]
Thank you - we will take a look and maybe add a note as you mentioned

**Comment by Brok-Bucholtz** [comment]
@traveling-desi,

Thanks for spotting this.  We added a note at the bottom of the video for anyone else that might be confused.
