### ISSUE TITLE
Enhancement: Jupyter Notebook Code Walkthrough

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#192]
[Please let me know if this isn't the best way to request for enhancement to any current video/lecture]

I was going through the Character-wise RNN Walkthrough video. [I jumped from P1 to this set of videos, so haven't check any other walkthroughs, if any]

This suggestion isn't specific to just this video, it's for any future videos where we walk through the code in a jupyter notebook. 

In most cases, Mat discusses part of the code all verbally. I think those parts could have the explanation based on the output of that particular piece of code instead of just talking through it. 

Like here - 
![image](https://cloud.githubusercontent.com/assets/12501638/23828835/abd34fa6-0704-11e7-8268-c9db229bb0d6.png)

Instead of trying to explain verbally what that line of code does, it's better to have, let's say, a split screen where you can show what the output looks like and he can explain it visually as well.  I, personally, couldn't really understand the code till I started running and playing around with it. Which is good, but it then made the video kind of redundant for me. 

I think that would improve the learning experience for students. Open for discussion.

**Comment by mcleonard** [comment]
Hi there! Thanks for the feedback. We are actively working to improve how we're building these lessons with notebooks.
