### ISSUE TITLE
project 2: variable names should be prefixed "test_" instead of "train_"

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#194]
In the last cell under "Test Model", the variable names within the for loop are named "train_features_batch" and "train_labels_batch", even though they are batches from the "test_features" and "test_labels" data.  

I suggest changing the variable names to "test_features_batch" and "test_labels_batch" to accurately reflect the data that they are storing.

**Comment by Brok-Bucholtz** [comment]
Thanks for letting us know!  We changed the variable names to reflect they are test data.
https://github.com/udacity/deep-learning/pull/61
