### ISSUE TITLE
Sorry, there was en error licensing this video.

### ISSUE THREAD

**Issue by minimumnz** [udacity/dlnd-issue-reports#204]
I get this error when trying to playing the videos. It initially plays and this error comes up after ~20 seconds.

**Comment by oritavital** [comment]
Can you share a link to the video with the problem?

**Comment by oritavital** [comment]
Hi

I'm closing this issue since I didn't get a response. If the problem continues please attach a link here so wee can investigate.

Thank you!
Orit
