### ISSUE TITLE
Project 1: Your first neural networks says [HIDDEN] in the tab

### ISSUE THREAD

**Issue by rm51** [udacity/dlnd-issue-reports#205]
The tab says [HIDDEN] for the first project for the dlf nd.

https://classroom.udacity.com/nanodegrees/nd101/parts/8b03c7e1-308c-477a-bd21-28872f5fed78/modules/2afd43e6-f4ce-4849-bde6-49d7164da71b/lessons/9027814e-e801-44f5-a416-fff0504482ed/project

**Comment by clapollo** [comment]
Hi, I'm hoping this is fixed, but I want to check. Does this still say HIDDEN for you?

**Comment by rm51** [comment]
Yes it's fixed for me too. Thanks

**Comment by clapollo** [comment]
Great! Thank you!
