### ISSUE TITLE
File name has spaces in the dlnd-your-first-network.zip

### ISSUE THREAD

**Issue by rm51** [udacity/dlnd-issue-reports#206]
The jupyter notebook has spaces in the zip file making it. Please rename to have dashes instead such as dlnd-your-first-neural-network.ipynb

**Comment by raffu09** [comment]
Reasoning: Problems with some operating systems and confusing and at least I have used to use wildcards like "command DL*"  does not work (argV parsing). (quoting too)

**Comment by clapollo** [comment]
Latest commit to GitHub removed spaces from all filenames.
