### ISSUE TITLE
Typos in the "Data in NumPy" lesson

### ISSUE THREAD

**Issue by bbbeebbb** [udacity/dlnd-issue-reports#209]

**Comment by bbbeebbb** [comment]
"You can still perform math between ndarrays. __NumPy scalars, and normal Python scalars, though, as you'll see in the element-wise math lesson.__"

"You can access elements of matrices just like vectors, but using additional index values. So to __fine__ the number 6 in the above matrix, you'd access m[1][2]."

**Comment by clapollo** [comment]
Thanks for spotting those!
