### ISSUE TITLE
opencv installation

### ISSUE THREAD

**Issue by andy1li** [udacity/dlnd-issue-reports#21]
In lesson Flappy Bird of Applying Deep learning:

Actually, we don't need to downgrade to python 2.7 to install opencv on Mac just because the opencv build on the official conda repo only support numpy 1.7.

We could instead install opencv from conda-forge:

`conda install -c conda-forge opencv`

It worked for me with my python 3 on mac.

https://github.com/conda/conda/issues/2448

https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/aba54606-cf35-4a77-b643-efec6a90bfa1/lessons/0273757e-bd54-42b2-a099-2d9d8c6fb999/concepts/88972d8b-e8a9-4789-ae79-6077db50dad9

**Comment by andy1li** [comment]
actually, pygame does not work very well with python3 on mac...

**Comment by UkiDLucas** [comment]
$ python --version
Python 3.5.2  - WORKS WELL

$ conda install -c conda-forge opencv

$ python --version
Python 3.6.0  - DOES NOT WORK

  - opencv -> python 2.7*
  - python 3.6*
