### ISSUE TITLE
inaccurate code results in "Transposes in NumPy"

### ISSUE THREAD

**Issue by bbbeebbb** [udacity/dlnd-issue-reports#210]

**Comment by bbbeebbb** [comment]
The following code snippet shows an inaccurate value for `inputs.shape`:

```
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
inputs
# displays the following result:
# array([[-0.27,  0.45,  0.64,  0.31]])

inputs.shape
# displays the following result:
# (1, 3)
```

See below:
```
>>> import numpy as np
>>> inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
>>> inputs.shape
(1, 4)
```

This becomes particularly confusing when we read "If you try it like they are now, you get an error", because the matrix we're trying to multiply against, `weights` has `.shape` of `(3, 4)`

**Comment by clapollo** [comment]
Ack! Thanks for spotting that! :)
