### ISSUE TITLE
typos in "NumPy Quiz"

### ISSUE THREAD

**Issue by bbbeebbb** [udacity/dlnd-issue-reports#211]

**Comment by bbbeebbb** [comment]
The comments in the script indicate you should create an ndarray:

```
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to new_inputs
```

However using an ndarray causes issues with the script, and `solution.py` also shows using just `np.array()`.

We are instructed to use `new_inputs` twice (once for min and once for max), but in both cases, the variable isn't present. Once we see `inputs_minus_min` and once we see `inputs_div_max`.

```
    # TODO: find the minimum value in new_inputs and subtract that
    # value from all the elements of new_inputs. Store the
    # result back in new_inputs
```

This becomes confusing when, for `inputs_div_max`, we should be using the result of `inputs_div_min` instead of `input_array`.

**Comment by clapollo** [comment]
Ah, that comment was from an earlier version. I'll fix that. But np.array() *does* create an ndarray, it's just a helper function that ensures it gets initialized correctly. We only use the `np.array` in any of the examples, so I was hoping that would be how people did it.

**Comment by clapollo** [comment]
Ok, fixed those comments. You'll need to refresh the page and reset the quiz if you want to see the updates.
