### ISSUE TITLE
Tester for backprop exercise cites non existent variable

### ISSUE THREAD

**Issue by babazaroni** [udacity/dlnd-issue-reports#212]
When testing the backprop exercise, the test report says delta_w_i_o is wrong, but delta_w_i_o does not exist.  Delta_w_h_o and delta_w_i_h do exist.

**Comment by babazaroni** [comment]
This is for the first backpropagation exercise (15), not the implementing backpropagation exercise(16).   In fact, testing the provided solution gives the same error.

**Comment by babazaroni** [comment]
The provided solution also fails the 'submit answer'

**Comment by clapollo** [comment]
I was able to find a typo in the error message, but the provided solution works successfully for me. Are you absolutely sure you are running the provided solution exactly?

**Comment by babazaroni** [comment]
I just tried again and everything works now.   Maybe you made a fix that
fixed both problems.

**Comment by clapollo** [comment]
I really *think* only changed the string used in the error message, but that's good it works. Thanks for spotting that!
