### ISSUE TITLE
Gifs are cut off in one layout for dlf nd

### ISSUE THREAD

**Issue by rm51** [udacity/dlnd-issue-reports#214]

**Comment by rm51** [comment]
![dlfnd](https://cloud.githubusercontent.com/assets/7563076/24327175/3c64e21c-1198-11e7-8d3e-0c91476eb160.PNG)

**Comment by rm51** [comment]
It looks fine in the other layout
![img_2544](https://cloud.githubusercontent.com/assets/7563076/24327190/a3510dd4-1198-11e7-9454-b3048a4b4374.PNG)

**Comment by clapollo** [comment]
This one is for the mobile team, too, @oritavital

**Comment by oritavital** [comment]
Hi

Yes, this is a know issues and we are working on adjusting the images to fit the mobile format as well.
Thanks for reporting!
Orit
