### ISSUE TITLE
Wrong matrix dimensions in video

### ISSUE THREAD

**Issue by narviis** [udacity/dlnd-issue-reports#215]
Matrix Math and NumPy Refresher lesson from Week 1 contains a typo in video Matrix Transposes. At 5:41 the right matrix is labeled 3x2 when it's supposed to be 2x3.

**Comment by clapollo** [comment]
Yep. Thanks for catching that. We have a couple other errors in that video so we'll get them all fixed at once. For now, I'm going to add a correction note below the video.

**Comment by clapollo** [comment]
Fixed.
