### ISSUE TITLE
Matrix Transposes Video

### ISSUE THREAD

**Issue by jeffthardy** [udacity/dlnd-issue-reports#217]

**Comment by jeffthardy** [comment]
Around 2:19 while showing off transpose it looks like the number 94 got replicated?  Person 2 shows  203, 102, 94 but I think that 94 in row 2 col 3 should be 31.

**Comment by clapollo** [comment]
Thanks for spotting this! We'll fix this along with a few other errors in this video soon. Until then, I've added a note below the video.

**Comment by clapollo** [comment]
Fixed.
