### ISSUE TITLE
Slack "deep-learning-slack" offline

### ISSUE THREAD

**Issue by fesaab** [udacity/dlnd-issue-reports#218]
The "https://deep-learning-slack.udacity.com/" slack server is offline and the status page says everything is ok.

Could you please check it?

Please find attached images showing what I am going through.

![image](https://cloud.githubusercontent.com/assets/2200538/24334587/1112757e-1243-11e7-83a4-652021b245f5.png)

![image](https://cloud.githubusercontent.com/assets/2200538/24334588/15f8537e-1243-11e7-8d1b-f95d2daeb07b.png)

![image](https://cloud.githubusercontent.com/assets/2200538/24334592/278eba24-1243-11e7-92bb-0ec810d63ff0.png)

**Comment by oritavital** [comment]
The link is now fixed. thanks for your comment
