### ISSUE TITLE
Android mobile app offline mode doesnt play some videos

### ISSUE THREAD

**Issue by llealgt** [udacity/dlnd-issue-reports#219]
In the Android mobile app, when online click the download option ,and the progress bar is shown, after a while it shows it has finished, and you can see the videos on the device storage,, but when you are offline , not all videos can be played (the most important videos are not played) only some of them. For example Sirajs videos on regression, or the DeepTraffic video says "No connection" but after all why you need connection if you downloaded them?

**Comment by clapollo** [comment]
Another one for the mobile team, @oritavital

**Comment by llealgt** [comment]
Forgot to mention that for example in week one the "Sira'js Math Notations" unit, also has a download button, and a video, but nothing happens when you hit download.

**Comment by oritavital** [comment]
Thanks for reporting.
Siraj's videos are hosted on his channel and not on Udacity youtube channel, which probably causes these issues.
I've reported the issue to our mobile team.

Orit

**Comment by llealgt** [comment]
Hey ,i have a question, this issue was closed ,but it is still happening, is the team going to work on it ?

**Comment by oritavital** [comment]
Yes, our mobile team is working on that. I closed the issue to make sure our board is focused on DL issues, but this is known and the team is looking at that.

Orit

**Comment by jason-kilic** [comment]
FIx is going to be released on Monday
