### ISSUE TITLE
DLND homepage keeps resetting to top of page when returning from a lecture

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#221]
It would really help if we could improve the navigation experience of the DLND home page, to let us keep our scroll location within the page while exploring specific lectures.

When returning from any specific section back to the DLND home page, it resets to the very top of the page with the very first lesson.  This is getting disorienting as there are now 37 lectures listed on the home page.

Also, from the DLND home page, we can't open any lessons in a new tab.  Allowing us to open a lesson in a new tab (by right-click or by Command + click or Ctrl + click) would let us keep the original scroll location of the DLND home page while we explore the specific lecture in a new tab or window.

**Comment by oritavital** [comment]
We are about to launch a refresh to the classroom really soon. This should solve most of the issue you raised here.
Thanks for reporting and sorry for your inconvenience (I share your sentiment there :) )
