### ISSUE TITLE
Content for "Applying Models"

### ISSUE THREAD

**Issue by feltenberger** [udacity/dlnd-issue-reports#222]
copy/pasted from feedback i provided in the slack channel:

i think it's really, really important to have a lesson about applying models. what we're learning is great, but we also need some "applied ML/DL" lessons:
1) the pitfalls of serving models (common errors, how to avoid, etc.)
2) how to structure code in such a way that it's simple to apply models on new/unseen data
3) performance considerations (e.g., caching models)
4) practical tips to ensure model config is saved between training and inference time
and so on.

because without something like this, the DLND class is just an academic exercise showing how to build models but not actually use them

**Comment by mcleonard** [comment]
Hi there, thanks for the feedback! I'm not sure this is within the scope of the program. We are just trying to provide foundations for deep learning here. Students should take our job-ready programs such as the AI Nanodegree program to learn more about applying deep learning models.
