### ISSUE TITLE
Sentiment Prediction RNN video download has only one video

### ISSUE THREAD

**Issue by swaroopch** [udacity/dlnd-issue-reports#230]
Should have all 6? videos :)

**Comment by oritavital** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/59bc204f-b47f-482f-968c-543dc5adc545/lessons/34a24397-2b0f-4c04-9088-1cea220c03b8/concepts/6ea3be95-f4ee-460a-a69d-975d8a88b2a3

Thanks for the feedback. I'll follow up on that
EXP-2668

**Comment by oritavital** [comment]
this should be fixed now
