### ISSUE TITLE
Information about functions property in MiniFlow: 8. Sigmoid Function is misleading

### ISSUE THREAD

**Issue by navaro1** [udacity/dlnd-issue-reports#232]
In MiniFlow: 8. Sigmoid Function. There is a statement:
> The sigmoid function, Equation (3) above, replaces thresholding with a beautiful S-shaped curve (also shown above) that mimics the activation behavior of a perceptron while maintaining continuity, and thus differentiability.

Which is not true to best of my knowledge. Continuity of function does not imply its differentiability, it is other way around. There are functions which are continuous, but not differentiable. "Starting" with absolute values and "ending" with Weierstrass function.

**Comment by mcleonard** [comment]
Yeah, that's true. We use the sigmoid because it is differentiable, not continuous.
