### ISSUE TITLE
Hidden Scrollbar problem on Classroom Page

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#233]
On the Classroom Page (with all the Lesson Tiles), when I start scrolling down, the "header" drops down and it hides the scroll button on the left side. Hopefully, the image gives you an idea of what's happening.

![image](https://cloud.githubusercontent.com/assets/12501638/24613297/86c86f40-18a5-11e7-8201-43be1d52cacd.png)

As you can see it's partially hidden and is completely hidden in the image below.

![image](https://cloud.githubusercontent.com/assets/12501638/24613412/ddf286b6-18a5-11e7-97a6-9e25f0f42001.png)

So I have to either click somewhere on the scroll bar till it's visible or click on the arrow at the bottom.

Let me know it the above was clear to understand.

**Comment by oritavital** [comment]
Hi

We are just about to launched a refreshed look to the classroom. Hopefully it will resolve the scrollbar issue. 
Please report again if the issue still exists
