### ISSUE TITLE
Mistake in "Accuracy" lecture video in "Model Evaluation and Validation" Lesson

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#234]
In the video,

Luis says 

```
In this example, we can see that we have correctly classified 9000 patients. Which is a sum of 1000 Healthy and 8000 Sick ones.
```

The last sentence is incorrect since, in the table that we have 8000 Healthy and 1000 Sick ones.

I know insignificant mistake but thought of pointing out.

**Comment by oritavital** [comment]
Thanks for flagging. We will get that fixed.
DLND-748
