### ISSUE TITLE
Intro To Neural Networks: Logistic Regression Quiz

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#235]
The lecture contains a quiz which is dependent on the graph in the video and associate Student 3 details. 

I was about to attempt the quiz, but the video finished, and reset. So I had to run it again and go to the end to be sure of the values involved. 

The quiz is quite basic, but it would help if there was the image of the graph and Student 3 details from the video, above the quiz so that it's somewhat easier for students to be able to answer it.

**Comment by oritavital** [comment]
Thanks for the feedback. We've added an image for reference.
