### ISSUE TITLE
12 KFold Cross Validation example in video

### ISSUE THREAD

**Issue by GzuPark** [udacity/dlnd-issue-reports#236]
In the lecture, the sample code of KFold, it doesn't work due to miss typo. 
1. try `from sklearn.cross_validation import KFold`, but it is  a deprecation and will remove 0.20.0 version.
2. alt version
```
from sklearn.model_selection import KFold
X = range(12)
kf = KFold(3, shuffle=True)
for train, test in kf.split(X):
    print(train, test)
```

**Comment by oritavital** [comment]
Thanks for reporting, we'll review and fix.
DLND-788

Orit
