### ISSUE TITLE
Heaviside step function

### ISSUE THREAD

**Issue by dalex01** [udacity/dlnd-issue-reports#24]
Heaviside step function is incorrect in equation here:
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/5ab911d0-fe20-4113-852c-8a07fe9bdacc

it should be 1 if h is grater or equal to 0. Currently it is shown that it is 1 only if h is greater than 0. In text it is described correctly.

**Comment by dalex01** [comment]
The same is in similar formula (but with bias) below on this page and in formula in this link:
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/a17b90c3-27ff-446a-9276-10381f55c64e

**Comment by Brok-Bucholtz** [comment]
@dalex01,

Thanks for letting us know.  I made all the changes to use the correct formula.
