### ISSUE TITLE
Link to Khan Academy missing

### ISSUE THREAD

**Issue by skh** [udacity/dlnd-issue-reports#240]
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/3156ccf8-9bd0-4019-83b9-ab39c53bf541

The instructor points out that a link to Khan Academy's multi variable calculus lessons will be in the instructor notes, but there are no instructor notes.

**Comment by clapollo** [comment]
Fixed. Thanks!
