### ISSUE TITLE
Result of matrix multiplication in video is wrong

### ISSUE THREAD

**Issue by skh** [udacity/dlnd-issue-reports#241]
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/bd6228e5-42e6-43e4-beea-218fc5ad6ac2/concepts/d14678eb-f4cc-4474-9ffb-8d77befb50c4

At time 2:43, the 3x3 matrix given as the result of the second matrix multiplication is wrong. The correct solution is the transposed version of the one shown.

**Comment by clapollo** [comment]
I checked it again and the result in the video is correct.
