### ISSUE TITLE
Text is Missing from Lectures

### ISSUE THREAD

**Issue by zacwentzell** [udacity/dlnd-issue-reports#242]

**Comment by tomrogers3** [comment]
+1... I'm experiencing this too, plus multiple others as per the #feedback channel in Slack. Please help! Thanks, Tom

**Comment by cdulhanty** [comment]
+1 here too

**Comment by tomrogers3** [comment]
Seems to be working again for me now. Cheers

**Comment by clapollo** [comment]
I think this was some larger bug unrelated to this ND. I saw students in many nanodegress complaining about the same thing.
