### ISSUE TITLE
Miniflow 12: Gradient Descent Part 2: replace "better" with "between"

### ISSUE THREAD

**Issue by e7dud7e** [udacity/dlnd-issue-reports#246]
In Miniflow part 12 "Gradient Descent Part 2", the code comment says:
```
# Random number better 0 and 10,000. Feel free to set x whatever you like.
```

Replace `better` with `between`.

**Comment by e7dud7e** [comment]
This is part 11 in Deep Learning ND, part 12 in Car ND.

**Comment by lcrucks** [comment]
Done, thanks for pointing out the typo!
