### ISSUE TITLE
Error in submit on Lesson 7, video 7 (Linear Transform)

### ISSUE THREAD

**Issue by ghost** [udacity/dlnd-issue-reports#247]

**Comment by ghost** [comment]
The output is a giant error stack when you submit.  Test run is successful.  I'm certain the code is correct.

Error stack:

File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
  ValueError: No JSON object could be decoded
  Environment: {'executor_result': {u'vm_time': 0.17192387580871582, u'stdout': u'', u'vm_creation_time': 6.9141387939453125e-05, u'test_results': [], u'stderr': u'Traceback (most recent call last):\n  File "vm_main3.py", line 47, in \n    import main\n  File "/tmp/vmuser_jxodozpbfb/main.py", line 2, in \n    import aiMain\n  File "/tmp/vmuser_jxodozpbfb/aiMain.py", line 16\n    def init(self, inbound_nodes=[]):\n                                        ^\nIndentationError: unindent does not match any outer indentation level\n', u'exec_server_time': 0.18283295631408691, u'exec_status': u'error'}, 'grade_result': {'comment': 'Thank you for your submission!', 'feedback': '', 'completed': None, 'test_results': [], 'bin_codes': [], 'correct': False}, 'executor_status': u'error'}
  Submission: {'operation': 'REGRADE', u'nn.py': u'"""\nThe setup is similar to the prevous Linear node you wrote\nexcept you\'re now using NumPy arrays instead of python lists.\n\nUpdate the Linear class in miniflow.py to work with\nnumpy vectors (arrays) and matrices.\n\nTest your code here!\n"""\n\nimport numpy as np\nfrom miniflow import *\n\nX, W, b = Input(), Input(), Input()\n\nf = Linear(X, W, b)\n\nX = np.array([[-1., -2.], [-1, -2]])\nW = np.array([[2., -3], [2., -3]])\nb = np.array([-3., -5])\n\nfeeddict = {X: X, W: W, b: b}\n\ngraph = topological_sort(feed_dict)\noutput = forward_pass(f, graph)\n\n"""\nOutput should be:\n[[-9., 4.],\n[-9., 4.]]\n"""\nprint(output)', u'miniflow.py': u'"""\nModify Linear#forward so that it linearly transforms\ninput matrices, weights matrices and a bias vector to\nan output.\n"""\n\nimport numpy as np\n\n\nclass Node(object):\n    def init(self, inbound_nodes=[]):\n        self.inbound_nodes = inbound_nodes\n        self.value = None\n        self.outbound_nodes = []\n        for node in inbound_nodes:\n            node.outbound_nodes.append(self)\n\n    def forward():\n        raise NotImplementedError\n\n\nclass Input(Node):\n    """\n    While it may be strange to consider an input a node when\n    an input is only an individual node in a node, for the sake\n    of simpler code we\'ll still use Node as the base class.\n\n    Think of Input as collating many individual input nodes into\n    a Node.\n    """\n    def init(self):\n        # An Input node has no inbound nodes,\n        # so no need to pass anything to the Node instantiator\n        Node.init(self)\n\n    def forward(self):\n        # Do nothing because nothing is calculated.\n        pass\n\n\nclass Linear(Node):\n    def init(self, X, W, b):\n        # Notice the ordering of the input nodes passed to the\n        # Node constructor.\n        Node.init(self, [X, W, b])\n\n    def forward(self):\n        """\n        Set the value of this node to the linear transform output.\n\n        Your code goes here!\n        """\n        \n        X = self.inbound_nodes[0].value\n        W = self.inbound_nodes[1].value\n        b = self.inbound_nodes[2].value\n        \n        self.value = np.array(np.dot(X, W) + b)\n\n\ndef topological_sort(feed_dict):\n    """\n    Sort the nodes in topological order using Kahn\'s Algorithm.\n\n    feed_dict: A dictionary where the key is a Input Node and the value is the respective value feed to that Node.\n\n    Returns a list of sorted nodes.\n    """\n\n    input_nodes = [n for n in feed_dict.keys()]\n\n    G = {}\n    nodes = [n for n in input_nodes]\n    while len(nodes) > 0:\n        n = nodes.pop(0)\n        if n not in G:\n            G[n] = {\'in\': set(), \'out\': set()}\n        for m in n.outbound_nodes:\n            if m not in G:\n                G[m] = {\'in\': set(), \'out\': set()}\n            G[n][\'out\'].add(m)\n            G[m][\'in\'].add(n)\n            nodes.append(m)\n\n    L = []\n    S = set(input_nodes)\n    while len(S) > 0:\n        n = S.pop()\n\n        if isinstance(n, Input):\n            n.value = feed_dict[n]\n\n        L.append(n)\n        for m in n.outbound_nodes:\n            G[n][\'out\'].remove(m)\n            G[m][\'in\'].remove(n)\n            # if no other incoming edges add to S\n            if len(G[m][\'in\']) == 0:\n                S.add(m)\n    return L\n\n\ndef forward_pass(output_node, sorted_nodes):\n    """\n    Performs a forward pass through a list of sorted Nodes.\n\n    Arguments:\n\n        output_node: A Node in the graph, should be the output node (have no outgoing edges).\n        sorted_nodes: a topologically sorted list of nodes.\n\n    Returns the output node\'s value\n    """\n\n    for n in sorted_nodes:\n        n.forward()\n\n    return output_node.value'}

**Comment by clapollo** [comment]
Yep. There was a classroom mix up that seems to have broken this lesson. I think we have it fixed now.
