### ISSUE TITLE
DLND Project-4: Typo function name “process_encoding_input” should be “process_decoding_input” in Rubic

### ISSUE THREAD

**Issue by SatoshiShimura** [udacity/dlnd-issue-reports#248]
I found typo that the function name "process_encoding_input" should be "process_decoding_input" on Rubic and on the explanation of "Build the Neural Network" function in dlnd_language_translation.ipynb

**Comment by Brok-Bucholtz** [comment]
@SatoshiShimura,

Thanks for letting us know.  We changed the rubric!
