### ISSUE TITLE
Lesson 14: Sequence to Sequence -  1. Introducing Jay Alammar

### ISSUE THREAD

**Issue by Adosha** [udacity/dlnd-issue-reports#249]
"This is typically used in problems such as **machine learning**, where you'd feed in a sentence in English and get out a phrase in Arabic."

probably should be: "...in problems such as machine translation...."

**Comment by Adosha** [comment]
"This is typically used in problems such as **machine learning**, where you'd feed in a sentence in English and get out a phrase in Arabic."

probably should be:  "...in problems such as **machine translation**...."

**Comment by clapollo** [comment]
Fixed. Thanks!
