### ISSUE TITLE
OR Perceptron quiz of Intro to NN

### ISSUE THREAD

**Issue by zhaobaiyu** [udacity/dlnd-issue-reports#25]
In the question, "What change can you make to the AND perceptron to make an OR perceptron?",  I cannot understand why the bias should be decreased. As the bias is negative in the "AND" perceptron and being added to the formula, I think it should be increased.

And also, if I increase the weights proportionally, it can made an "OR" perceptron, so maybe "increase the weights" can be right, it is not rigorious.

**Comment by Zithrill** [comment]
I agree on this point, coming from the previous quiz where you would increase the bias value numerically (-1 to 0) which is actually decreasing the the bias (absolute distance from 0) is confusing.
Perhaps a rewording of the question, or a hint letting us know that moving towards zero decreases the bias and moving away from zero increases the bias would be helpful.

**Comment by Brok-Bucholtz** [comment]
@zhaobaiyu,

This was an oversight on our part.  Thanks for pointing it out.  We changed the quiz to accept both increasing bias and/or increasing weights.
