### ISSUE TITLE
missing pic

### ISSUE THREAD

**Issue by plouismarie** [udacity/dlnd-issue-reports#259]
lesson 9 - section 2

this image is not displayed successully, might be a cors header issue ( crossdomain issue with cloudfront not allowed ) :

https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58ae4386_two-layer-network/two-layer-network.png

**Comment by oritavital** [comment]
does the issue still exist?

**Comment by plouismarie** [comment]
nope solved by now - this waffle can be closed I think
