### ISSUE TITLE
No '<\s>' added to the 'target_ids' in the notebook in Sequence to Sequence lesson

### ISSUE THREAD

**Issue by myfunprograms** [udacity/dlnd-issue-reports#264]

**Comment by myfunprograms** [comment]
The bug is for the Character Sequence to Sequence notebook used in the Sequence to Sequence lesson. The URL of the code is as follows. 

https://github.com/udacity/deep-learning/blob/master/seq2seq/sequence_to_sequence_implementation.ipynb

In the code, we suppose to add '<\s>' at the end of each word in the target data to indicate the end of a word. But I can't find such code. 

Currently the  '<\s>' appears in two places in the code. The first place is where the mapping between letters and ints. (See the following code.)
...
def extract_character_vocab(data):
    special_words = ['<pad>', '<unk>', '<s>',  '<\s>']
...

The second place is where the infer decoder is defined. (See the following code.)
...
infer_decoder_fn = tf.contrib.seq2seq.simple_decoder_fn_inference(
        output_fn, enc_state, dec_embeddings, target_letter_to_int['<s>'],   target_letter_to_int['<\s>'], sequence_length - 1, target_vocab_size)
...

**Comment by myfunprograms** [comment]
(Please read this one. As a new waffle.io user, I messed it up a bit.)

The bug is for the Character Sequence to Sequence notebook used in the Sequence to Sequence lesson. The URL of the code is as follows. 

https://github.com/udacity/deep-learning/blob/master/seq2seq/sequence_to_sequence_implementation.ipynb

In the code, we suppose to add '<\s>' at the end of each word in the target data to indicate the end of a word. But I can't find such code. 

Currently the  '<\s>' appears in two places in the code. The first place is where the mapping between letters and ints. (See the following code.)
```
def extract_character_vocab(data):
    special_words = ['<pad>', '<unk>', '<s>',  '<\s>']
```

The second place is where the infer decoder is defined. (See the following code.)
```
infer_decoder_fn = tf.contrib.seq2seq.simple_decoder_fn_inference(
output_fn, enc_state, dec_embeddings, target_letter_to_int['<s>'],   target_letter_to_int['<\s>'], sequence_length - 1, target_vocab_size)
```

**Comment by mcleonard** [comment]
@jalammar Can you have a look at this?
