### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by skh** [udacity/dlnd-issue-reports#265]
https://classroom.udacity.com/nanodegrees/nd101/parts/f6d74d04-6d65-424a-9f3a-d58f4da7d406/modules/e0ad6969-6321-437a-8279-d9b20a7cd00a/lessons/b243672b-c123-43a2-a460-102ce38cd653/concepts/1b92472a-013d-4fa5-9764-724e7ce8b138

First sentence reads "As you follow along this lesson, it's extremely important that you open the Jupyter notebook and attempting the exercises. " -- "attempting" should be "attempt"

**Comment by oritavital** [comment]
Thanks for the feedback. Fixed
