### ISSUE TITLE
Lesson 11: 24. Question unclear

### ISSUE THREAD

**Issue by heresadam** [udacity/dlnd-issue-reports#266]
Says "Work from the top left to the bottom right" but doesn't say whether to work from top to bottom or left to right. Videos prior to quiz show the filter sliding from top to bottom first but answer accepted is for left to right first.

**Comment by heresadam** [comment]
Same for part 26. The solutions in parts 25 and 27 both say "we work from left-to-right and top-to-bottom" but not mentioned in the questions. Minor issues nonetheless!

**Comment by oritavital** [comment]
can you please include a link to the lesson you are referring to?

**Comment by mcleonard** [comment]
This is really old without a response so I'm closing it.
