### ISSUE TITLE
english french translation training set has errors

### ISSUE THREAD

**Issue by canbruce1234** [udacity/dlnd-issue-reports#267]
Not sure if someone has already mentioned this, but the french translations of the english sentences (project 4 training set) are not very good. I admit that for the purpose of learning how to program a translation neural network it doesn't matter. But just FYI, here are a few cringy examples and their more acceptable versions:

EN: california is never freezing during october , but it is usually quiet in june .
!FR: la californie est jamais le gel en octobre , mais il est généralement calme en juin .
FR: la californie n'est jamais engelé en octobre, mais elle est généralement calme en juin .

EN: he dislikes grapefruit , mangoes , and lemons.
!FR: il n'aime pamplemousse , mangues et citrons .
FR: Il n'aime pas le pamplemousse, les mangues et les citrons

EN: the lime is her least liked fruit , but the banana is my least liked .
!FR: la chaux est son moins aimé des fruits , mais la banane est mon moins aimé .
FR: le lime est son fruit moins aimé, mais la banane est mon moins aimée .

EN: the grapefruit is our least favorite fruit , but the orange is your least favorite .
!FR: le pamplemousse est notre fruit préféré moins , mais l'orange est votre préféré moins .
FR: le pamplemousse est notre fruit le moins favori, mais l'orange est votre moins favori .

EN: i like grapefruit , limes , and pears .
!FR: i comme le pamplemousse , citrons verts , et les poires .
FR: J'aime le pamplemousse, les citrons verts, et les poires .

**Comment by Ortalarel** [comment]
Translations in these stages of learning are usually not that accurate.

**Comment by mcleonard** [comment]
Yeah, I agree. The problem is that to get machine translation to work well, you need a huge data set and lot of compute time. It's not really possible to train a good model in a couple hours and we don't want to make our students pay for days worth of GPU time.

Thanks for your feedback though! We'll look into how we can make this project better.

**Comment by canbruce1234** [comment]
Hi,

 

The problem I had raised was not about machine translation and needing compute time. It is that the training set is not well prepared. The person who prepared the French sentences obviously does not know French. If you don’t have a French speaker on your staff perhaps you could create a training set in a different language?

 

Can
