### ISSUE TITLE
Extra scroll bars in new UI

### ISSUE THREAD

**Issue by saulthu** [udacity/dlnd-issue-reports#268]
Since the new UI was launched there have been extra scroll bars when viewing the lessons. Only occurs on my desktop Windows 10, 4k monitor, display set to 150% text size, happens on both latest Chrome and partially on MS Edge.

**Comment by saulthu** [comment]
Example image from Chrome: https://snag.gy/vDJUhj.jpg

**Comment by oritavital** [comment]
Thanks, we've reported to our classroom team
EXP-2982
