### ISSUE TITLE
XOR perceptron

### ISSUE THREAD

**Issue by dalex01** [udacity/dlnd-issue-reports#27]
There is no connection between A-C and C-D perceptrons on image here: https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/7e892a87-83fc-42f0-8bd5-4f7c4ad4e25a

But as I understand from text there should be thin lines between them.

**Comment by Adosha** [comment]
@dalex01 There are lines, bro.
But they are sooooo thin that you can see them only if you tilt monitor away from you.  May be on retina display it's ok...
And yes, this is confusing.
