### ISSUE TITLE
GANs L1.3 - How GANs work couple of issues

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#270]
The first is around 3:36

Ian says
```
Eventually, the generator's distribution matches the real distribution and the discriminator has to output the probability of one-half everywhere because every point is equally likely to be generated by the real dataset has to be generated by the model the two densities are equal.
```

Honestly, I don't understand the last part of the above sentence. It seems.. broken to me. I don't think I misheard anything here, but a quick clarification could help somehow? Let me know if I misunderstood the above somehow.

Second is the video from 4:24 onwards

It seems there was a frame you were planning to introduce, but which was removed, but there was a "Z" leftover on the frames till the end. I can provide a screenshot if required.

**Comment by oritavital** [comment]
for the 2nd issue: DLND-872

**Comment by clapollo** [comment]
What Ian says is correct, but I think the way you've punctuated your transcription makes it more confusing. It should be "every point is equally likely to be generated by the real dataset **as** to be generated by the model – the two densities are equal."

That is, the probability of being real equals the probability of being fake.

To explain it further, the generator is trying to create data that looks like it came from the "real" dataset. The discriminator is returning a probabilities of whether the data is real or fake. Eventually it should not be able to tell the difference, so it gets to a 50/50 toss up situation where it's never sure one way or the other. At that point, the discriminator is always returning a probability of .5.

I hope that clears it up, but just message me on Slack if you want to discuss it further.

**Comment by sahiljuneja** [comment]
Yes, that "has" was based on the captions since I wasn't sure on whether it was "as" or "has".

And when you write it out like that, it makes slightly more sense, but not too much when you hear it. Especially the last part " the two densities are equal". It doesn't seem to flow well when you hear it as per me. I know my English isn't that bad, but I was just wondering if it might confuse any more non-native speakers a bit or not. Hence the suggestion. Let me know what you think on that. I will try to go through it again and see if I am just overthinking on it or not. Thanks for the reply!
