### ISSUE TITLE
GANs L1.4 - Games & Equilibria

### ISSUE THREAD

**Issue by raphey** [udacity/dlnd-issue-reports#275]
I believe the function written to the left of the graph is incorrect, which adds some confusion. I think you want x^2 - y^2 = z and -x^2 + y^2 = z, instead of x^2 + y^2 = z for both of them.

**Comment by rahul-ahuja** [comment]
To back up @raphey 's comments i have done some visualizations;
https://discussions.udacity.com/t/lession-4-games-and-equillibria-the-saddle-point-of-function/245430/2

**Comment by Brok-Bucholtz** [comment]
At 3:27 to 4:00 - The equation is correct, but the graph is incorrect
The graph should be for x^2 + y^2 = z
At 4:00 to 4:08 - The function is not correct, but the graph is correct
The function should be x^2 - y^2 = z
At 4:23 to 4:40 - The function is not correct, but the graph is correct
The function should be x^2 - y^2 = z

**Comment by oritavital** [comment]
DLND-873

**Comment by mcleonard** [comment]
Resolved
