### ISSUE TITLE
Broken link: seq2seq

### ISSUE THREAD

**Issue by georgeliu1998** [udacity/dlnd-issue-reports#276]
Link to tf.contrib.seq2seq.dynamic_rnn_decoder is broken in lesson 14.7   https://classroom.udacity.com/nanodegrees/nd101/parts/4f636f4e-f9e8-4d52-931f-a49a0c26b710/modules/c1558ffb-9afd-48fa-bf12-b8f29dcb18b0/lessons/43ccf91e-7055-4833-8acc-0e2cf77696e8/concepts/9992eebb-f711-4d21-aa3a-4e6846127f4c

**Comment by oritavital** [comment]
thanks, fixed
