### ISSUE TITLE
Intro to NN - 5. Neural Networks - small error in video

### ISSUE THREAD

**Issue by Adosha** [udacity/dlnd-issue-reports#28]
https://youtu.be/xFu1_2K2D2U?t=1m57s

The right answers is "No", "Yes", "No", "No" - how it is written in the video. 

Maybe you can change subtitles and add annotation at this place.

**Comment by Brok-Bucholtz** [comment]
@oritavital,

This problem still exists https://www.youtube.com/watch?v=Mqogpnp1lrU.  Who should I talk to to get this fixed?

**Comment by Brok-Bucholtz** [comment]
@Adosha,

This has been fixed!  Thanks for letting us know.
