### ISSUE TITLE
Confusing batch_size variable name in Anna_KaRNNa Exercise

### ISSUE THREAD

**Issue by vjp23** [udacity/dlnd-issue-reports#280]
In the Anna_KaRRNa_Exercises notebook exploring recurrent neural networks, an image- shown below- suggests that the batch size property of an LSTM cell refers to the number of samples analyzed in parallel:

![sequence_batching 1x](https://cloud.githubusercontent.com/assets/20172859/25906434/9b5c32c2-3572-11e7-8cdb-405aa2bf9510.png)

However, in the `get_batches()` method just below this image, which the student is to implement, there is a variable named `batch_size` which contains the number of data points contained within each batch:

`batch_size = n_seqs * n_steps`

In effect, the notebook uses the same word, batch size, to refer to both the number of _samples_ in each batch, and the number of _total data points_. While on the image, batch size = 2, using the multiplication shown in the `get_batches()` method on the same data would return batch size = 6.

Perhaps changing the first reference to "batch size" to "number of sequences" or "number of batches" would be more clear.

See [this discussion](https://discussions.udacity.com/t/difference-between-batch-size-and-num-steps/240711/7) in the Udacity forums.

**Comment by clapollo** [comment]
Change variable name
