### ISSUE TITLE
Leaky RELU in GAN_MNIST helper exercise

### ISSUE THREAD

**Issue by traveling-desi** [udacity/dlnd-issue-reports#288]
Hi!

In one of the GAN helper notebook, we have to implement leaky RELU in the generator and discriminator.

We are asked to implement it as  tf.maximum(alpha * x, x)

However, a better implementation that uses less memory is proposed here:
https://github.com/tensorflow/tensorflow/issues/4079

```
def lrelu(x, leak=0.2, name="lrelu"):
     with tf.variable_scope(name):
         f1 = 0.5 * (1 + leak)
         f2 = 0.5 * (1 - leak)
         return f1 * x + f2 * abs(x)
```

I thought it was nifty code. In case you want to incorporate it in your notebook.

**Comment by lcrucks** [comment]
Considering it's part of a notebook meant for learning and not production code, I don't think the extra memory efficiency is worth the trade-off in readability.  Thanks for the suggestion, though!
