### ISSUE TITLE
Subtitle error

### ISSUE THREAD

**Issue by PoBlue** [udacity/dlnd-issue-reports#29]
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/9e9ed61d-20c3-4431-95aa-a1099f28d601/concepts/b08dcd92-c3a0-43a0-b133-0deaf3d6f5cd

**Comment by dhruvp** [comment]
Fixed now!
