### ISSUE TITLE
Content not accessible after graduation

### ISSUE THREAD

**Issue by kulshekhar** [udacity/dlnd-issue-reports#290]
All 4 sections are locked

**Comment by clapollo** [comment]
This bug may be fixed now. Some students are still having problems, but that may be related to caching issues. We will continue to investigate.

**Comment by kulshekhar** [comment]
It's not a (browser) caching issue, at least at my end. Despite refreshing, logging out and back in and deleting all cookies, local storage & indexeddb, the content is still locked

**Comment by kulshekhar** [comment]
Here's a complete rundown of what I've tried so far:

Web:
I usually use Chrome to access the classroom. I've tried clearing all local storage (cookies/dbs/etc) and logging in again. The content remains locked.
I've tried doing the same in incognito mode with the same result.
I also tried using Firefox but the content was locked there as well.
So this doesn't seem like a caching issue.

Android:
I was able to access the classroom and browser the course content 4-5 days after graduation on the Android app. This was just a short session (< 10-15 minutes). While this worked, the nanodegree wasn't available in my list of enrollments. I had to search through your catalog and access the classroom from there.

When trying again the next day, this didn't work. I wasn't even able to see the syllabus page of the course on the Android app.

Could this issue have something to do with the registration/login method? I had signed up on Udacity using my Google account and continue to login using that.

**Comment by kulshekhar** [comment]
Two hacks independently get this working for me

- modifying a graphql query sent from the client
- patching the response sent from the server

It does look like some sort of a caching issue. Not sure if this is relevant but the classroom pages are being served with `Last-Modified` set to `Thu, 27 Apr 2017 18:30:48 GMT`.

That was all the info I have to help you debug/fix this issue. 

Anyway, now that I've got this working, in a way, should I close this or leave it open till this is really fixed?

**Comment by kulshekhar** [comment]
This seems to be fixed, at least for me, now. Would it be possible for you to share what was the issue? It seems worthwhile learning more about a bug that was hard to find :)

**Comment by oritavital** [comment]
Issue has been solved now. 
If you still have a problem, please email deeplearning-support@udacity.com
