### ISSUE TITLE
Some Quizzes Already Have the Solutions in the Quiz Part

### ISSUE THREAD

**Issue by beliu** [udacity/dlnd-issue-reports#293]
Hi, for the lessons in the second project, I find that many code and answer quizzes already have the solution written out in the quiz section (I mean separate from the solution section).

**Comment by clapollo** [comment]
Can you please name the specific sections and lessons you mean? Or provide links to the pages? Thanks!

**Comment by beliu** [comment]
I most recently came across them in the CNN lectures. From memory, the answer was already present here:

https://classroom.udacity.com/nanodegrees/nd101/parts/8f87ac5c-3036-4102-9bcf-1c3a5d34c0a6/modules/7dbf2d76-9ec6-494c-b9ce-34ea968347cf/lessons/bd73c076-7661-4947-9f73-7020d313eb6f/concepts/d5cf4454-1324-4524-9e2c-0ecca1f5c40e

https://classroom.udacity.com/nanodegrees/nd101/parts/8f87ac5c-3036-4102-9bcf-1c3a5d34c0a6/modules/9bb24411-38e1-4b51-98dd-c464d158c87a/lessons/2fd24529-215c-47b5-a644-2c23650493f6/concepts/4f028128-6c6a-41e1-80cd-58f54189615d

https://classroom.udacity.com/nanodegrees/nd101/parts/8f87ac5c-3036-4102-9bcf-1c3a5d34c0a6/modules/9bb24411-38e1-4b51-98dd-c464d158c87a/lessons/2fd24529-215c-47b5-a644-2c23650493f6/concepts/99df67c6-a4a1-4149-8271-be731155becc

There may be others prior to these but I do not remember the specific quizzes.

**Comment by clapollo** [comment]
I just went to each of those with a fresh account and there are not answers. Are you sure you did not do them before? The answers will be cached so next time you view a quiz again your answers will still be there.
