### ISSUE TITLE
Project 2 - One-Hot Encode Test Incorrect

### ISSUE THREAD

**Issue by johannesgiorgis** [udacity/dlnd-issue-reports#295]

**Comment by johannesgiorgis** [comment]
Under the One-Hot Encode portion of Project 2 - Image Classification, I found a bug. While playing around with the code and running the cell, I found that initializing a numpy array with all zeros and returning it results in the tests passing. This is incorrect as the one-hot encoding portion has not been applied yet. The test should have failed.

For verification, I did restart the kernel and re-run all the cells. I was able to reproduce the bug. I had a friend also reproduce the bug as well. Could you please look into it? Thanks!

**Comment by clapollo** [comment]
Added some more tests to check for encodings
