### ISSUE TITLE
Broken link: slack's form

### ISSUE THREAD

**Issue by dennys-bd** [udacity/dlnd-issue-reports#297]
When I go in Lesson 1. part 6 theres a link to sign in for slack community

This link is broken
https://dlf-slack.udacity.com/

**Comment by ciniro** [comment]
In fact, it is broken.

**Comment by RicardoCostaBRRJ** [comment]
Same issue here. Found https://deep-learning-slack.udacity.com/ but I don't know if this is the right place.

**Comment by valeriow** [comment]
confirmed

**Comment by ghost** [comment]
Same here. Waiting for the right link.

**Comment by oritavital** [comment]
Yes - this is the right link:  https://deep-learning-slack.udacity.com

The place I see in the classroom is updated. if you find place where it's not - can you please link the classroom URL of it here?

Thanks

**Comment by dennys-bd** [comment]
It's the Brazilian Portuguese version that I see broken

https://classroom.udacity.com/nanodegrees/nd101/parts/cd43532d-a5e9-4358-8791-4eea558b67f2/modules/53595ccf-5a74-4477-9851-61243825348a/lessons/fb47e99f-bd1f-43d9-90c9-b5790eaa4598/concepts/f1736606-197b-4926-877c-

It's something like this: \/

![captura de tela 2017-05-26 as 16 33 49](https://cloud.githubusercontent.com/assets/8262459/26509896/3e65712a-4231-11e7-9708-e08a83c0a0ee.png)

**Comment by RicardoCostaBRRJ** [comment]
@oritavital The broken link is in the Brazilian Portuguese content, Lesson 1, Chapter 6, which talks about the Slack Community. 

URL: https://classroom.udacity.com/nanodegrees/nd101/parts/cd43532d-a5e9-4358-8791-4eea558b67f2/modules/53595ccf-5a74-4477-9851-61243825348a/lessons/fb47e99f-bd1f-43d9-90c9-b5790eaa4598/concepts/f1736606-197b-4926-877c-240213896b36

**Comment by oritavital** [comment]
oh :) 
Fixed!
