### ISSUE TITLE
 Lesson 4 - Video missing in Degree Resources

### ISSUE THREAD

**Issue by valeriow** [udacity/dlnd-issue-reports#298]
Hey there!
Although there is a video in "Lesson 4 - 3.DeepTraffic", there is no link to download it in resources.

![image](https://cloud.githubusercontent.com/assets/115977/26434605/f86ec5ec-40df-11e7-9f90-5e2a3dce0e3a.png)

**Comment by lcrucks** [comment]
This seems to have been fixed.
