### ISSUE TITLE
Lesson 4 - Style Transfer - Anaconda's tutorial link is broken

### ISSUE THREAD

**Issue by valeriow** [udacity/dlnd-issue-reports#299]
Lesson 4 - Style Transfer - Anaconda's tutorial link is broken

![image](https://cloud.githubusercontent.com/assets/115977/26434939/17ba3196-40e2-11e7-9409-ddd1aeecc8ce.png)

![image](https://cloud.githubusercontent.com/assets/115977/26434846/78c425f6-40e1-11e7-98da-8a94f9bc766c.png)

**Comment by oritavital** [comment]
@kadu-vido I fixed this on the english version - can you fix on the br-pt one?

**Comment by kadu-vido** [comment]
This is fixed =]
