### ISSUE TITLE
No slack acces, where could I find my link?

### ISSUE THREAD

**Issue by Martijnde** [udacity/dlnd-issue-reports#3]

**Comment by Martijnde** [comment]
Following the link Slack States:

Don't have an account on this team yet?
Contact the team administrator for an invitation

**Comment by samuelhavard** [comment]
Message on slack sign in site is:

"Don't have an account on this team yet?
Contact the team administrator for an invitation"

**Comment by Martijnde** [comment]
True, who is the team administrator?

**Comment by adarsh0806** [comment]
Auto inviter link - https://deep-learning-slack.udacity.com/

**Comment by oritavital** [comment]
The link in the classroom was fixed to take you to the auto-inviter

**Comment by Martijnde** [comment]
Thanks, worked out well!
