### ISSUE TITLE
ImportError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by usefuldata** [udacity/dlnd-issue-reports#30]
Hi, I am trying this out :

python evaluate.py --checkpoint ./rain-princess.ckpt --in-path <path_to_input_file> --out-path ./output_image.jpg

with a genuine value for <path_to_input_file>

Its here: 
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/aba54606-cf35-4a77-b643-efec6a90bfa1/lessons/0273757e-bd54-42b2-a099-2d9d8c6fb999/concepts/7991da18-bbd0-4606-83e5-3bc5ce558e70

However running the same produces error saying : ImportError: No module named 'tensorflow'. 

Could you please check if anything in the fast-style-transfer-master directory is missing? The code is executed blindly with the instructions provided.

**Comment by Brok-Bucholtz** [comment]
@usefuldata,

Did you follow the previous steps to setup your environment?  For example, the Windows instructions are the following:
```sh
conda create -n style-transfer python=3.5
activate style-transfer
conda install -c conda-forge tensorflow=0.12.1
conda install scipy pillow
```

**Comment by usefuldata** [comment]
Yes, I did....

**Comment by usefuldata** [comment]
I think, the problem is running the 4 lines together. It asked for confirmation and stopped....
However when I executed one line at once it was solved....

Thank you!!!!!!!!!! :)

**Comment by Brok-Bucholtz** [comment]
Welcome!!

**Comment by jeskarha** [comment]
@Brok-Bucholtz What are the corresponding commands on Mac OSX 10.5.5 for the same ImportError: No module named 'tensorflow' error?  Thanks!
