### ISSUE TITLE
Regression env issue

### ISSUE THREAD

**Issue by RicardoCostaBRRJ** [udacity/dlnd-issue-reports#301]
In Lesson 5/2 (getting ready for Siraj's video), the material guides us to create an environment using Python 2 (>>conda create -n siraj-regression python=2).

When I ran his 'Brain Weight/Animal Weight' code, I got INTEL MKL ERROR. I did everything possible to fix it, but no success.

I created an environment using Python 3x, and the code ran perfectly. As a suggestion, the material should guide students to create a Python 3x environment (not Python 2, as it is now).

**Comment by lcrucks** [comment]
The code here (https://github.com/llSourcell/linear_regression_demo) works on both Python 2 and Python 3 without errors, if you have the proper libraries installed.
