### ISSUE TITLE
SnK teaching style endorced by more teachers

### ISSUE THREAD

**Issue by plouismarie** [udacity/dlnd-issue-reports#302]
Sebastian and Katie should give a name to that training method they are using , and then when a new training is available we can see this SnK style logo to confirm we will have this same great learning experience again. The system they use to draw and speak at the same , and pause the video to switch to interactive mode during the drawing is phenomenal ! They should encourage each and single udacity teacher to use it again and again. It is like a whiteboarding experience for any idea they want to teach to the student in a very stylish way. I really hope to get more and more teachers using that technique. It might not be the best spot to promote the idea, but at least it is a 1st step.

**Comment by mcleonard** [comment]
Thanks for your feedback! We've actually moved away from the drawing and speaking videos recently. A lot of instructors have poor handwriting or the drawings get too cluttered too easily. It ends up being a poor learning experience for a lot of students. We're trying to make engaging animations to replace those videos.
