### ISSUE TITLE
GAN-MNIST

### ISSUE THREAD

**Issue by sashank06** [udacity/dlnd-issue-reports#303]
n_units is not defined in build the network section.

NameError                                 Traceback (most recent call last)
<ipython-input-7-6426fea9cab4> in <module>()
      4 
      5 # Build the model
----> 6 g_model = generator(input_z, input_size, n_units=n_units, alpha=alpha)
      7 # g_model is the generator output
      8 

NameError: name 'n_units' is not defined

**Comment by mcleonard** [comment]
This issue has been fixed since the ticket was created
