### ISSUE TITLE
Coding Session dates - outdated?

### ISSUE THREAD

**Issue by adrianstaniec** [udacity/dlnd-issue-reports#304]
Week 1 (3/29): Linear Regression
Week 2 (4/5): How to Use Tensorboard
Week 3 (4/12): Reinforcement Learning with
...

**Comment by atannir** [comment]
I second this report, if that is a thing that one does in Waffle.

**Comment by lcrucks** [comment]
Where exactly is this?  (It seems like something that would have been taken care of already, but I'd like to double check).

**Comment by adrianstaniec** [comment]
Sorry, I can't find it anymore
