### ISSUE TITLE
Forum link private or missing

### ISSUE THREAD

**Issue by atannir** [udacity/dlnd-issue-reports#305]
Lesson 1 Section 6 link to forums Q&A (.../nd101-Project-1/) returns error "Oops! That page doesn’t exist or is private.".

**Comment by swnicholson** [comment]
+1

**Comment by nm1291** [comment]
Same here

**Comment by chelseapettigrew** [comment]
@atannir @swnicholson @nm1291 Hi all! Sorry about the issues you're having accessing the forums. Please write in to deeplearning-support@udacity.com and we'll take a look at your accounts to make sure you have the correct permissions. Thanks!

**Comment by chunkimonkey** [comment]
@atannir @swnicholson @nm1291 Hi all! As @chelseapettigrew mentioned above, if it is forums related, please write into deeplearning-support@udacity.com and we'll take a look. I will close this issue since Chelsea and her team will be able to help you out. Thanks!
