### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by georgeliu1998** [udacity/dlnd-issue-reports#309]
Broken Links at the bottom of Lesson 11: Sentiment Prediction RNN (Intro)

The links at the bottom of the first lesson of 
Lesson 11: Sentiment Prediction RNN

https://classroom.udacity.com/nanodegrees/nd101/parts/4f636f4e-f9e8-4d52-931f-a49a0c26b710/modules/59bc204f-b47f-482f-968c-543dc5adc545/lessons/34a24397-2b0f-4c04-9088-1cea220c03b8/concepts/5904c93a-0dbc-4900-80ec-3e5523b56c70

**Comment by oritavital** [comment]
The content links to 2 github files that don't exist:
https://github.com/udacity/deep-learning/blob/master/sentiment_network/labels.txt
https://github.com/udacity/deep-learning/blob/master/sentiment_network/reviews.txt

**Comment by mcleonard** [comment]
Fixed!
