### ISSUE TITLE
Part 3: RNNs - Lesson 3: Hyperparameters - error in number of layers

### ISSUE THREAD

**Issue by bdelhaisse** [udacity/dlnd-issue-reports#310]
Hi, there is an error in the video at ~1:55, you talk about a 3 layers NN but show a 4 layers NN.
Nb of layers = nb of hidden layers + 1 (for the output layer)
You can check this in the source you are refering: https://cs231n.github.io/neural-networks-1/#power

**Comment by Ortalarel** [comment]
I believe the teacher is talking about the number of weights to the single hidden layer of the model.

**Comment by bdelhaisse** [comment]
Hi. To be sure that we are talking about the same thing, the error is in the video in section 6 "Number of Hidden Units / Layers". If you check this video around 1:55, the teacher is clearly talking about the number of layers. Here is the quote: "In practice it is often the case that 3-layer neural networks will outperform 2-layer nets, but going even deeper (4,5,6-layer) rarely helps much more". A 3-layers NN is a NN which has 2 hidden layers and 1 output layer, but in the video a 4-layers NN (3 hidden layers + 1 output layer) is depicted.

**Comment by Ortalarel** [comment]
Thank you for the clarification. 
We are in the process or revisiting this video.
