### ISSUE TITLE
Part 4: GAN - Lesson 1: GANs - Section 5 - Practical Tips and Tricks for training GANs - error in audio

### ISSUE THREAD

**Issue by bdelhaisse** [udacity/dlnd-issue-reports#311]
In the video, the audio segment from 3:15 to 3:35 and the one from 3:35 to 3:55 are the same; you are repeating yourself...

**Comment by oritavital** [comment]
we have an issue for that (https://waffle.io/udacity/dlnd-issue-reports/cards/5909bfee8848b40092040e14)
closing this one
