### ISSUE TITLE
Lesson 4- Intro to Neural Nets -> 5. Perceptron --> Text and translation problem

### ISSUE THREAD

**Issue by valeriow** [udacity/dlnd-issue-reports#313]
Lesson 4- Intro to Neural Nets -> 5. Perceptron -> PT-BR Translation problem

In english:
"Now that you have a good understanding of perceptions, let's put that knowledge to use. In the next section, you'll create the AND perceptron from the Neural Networks video by setting the values for weights and bias."

In portuguese:
"Agora que você tem uma boa compreensão sobre perceptrons, vamos utilizar esse conhecimento. Na próxima seção, você criará o perceptron do E a partir do vídeo Redes Neurais ao ajustar os pesos e viés."

I suggest:

1) "Now that you have a good understanding of *perceptrons*, ..."

It's ok in portuguese.

2) "...Na próxima seção, você criará o perceptron *AND* a partir do ...."

**Comment by oritavital** [comment]
thanks for flagging - you're right and it should be fixed now
