### ISSUE TITLE
Environments for win-64 machines

### ISSUE THREAD

**Issue by ryanworsley** [udacity/dlnd-issue-reports#315]
For most of the projects, in particular project-3.  The supplied requirements.txt is not compatible with win-64 based machines.  At the very least the notebooks should run on the most popular operating systems as this severely impacts the ability of students to submit assignments on time.

**Comment by mcleonard** [comment]
Yep, I know. It's really unfortunate that conda environment files aren't cross-platform. We need to make environment files for each operating system. I need to update the files anyway to tensorflow-1.2. I'll put this on my todo list for tomorrow.

**Comment by mcleonard** [comment]
Tracking internally: DLND-991
