### ISSUE TITLE
Sentiment Prediction RNN has the wrong links to the dataset on github

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/dlnd-issue-reports#316]
https://classroom.udacity.com/nanodegrees/nd101/parts/4f636f4e-f9e8-4d52-931f-a49a0c26b710/modules/59bc204f-b47f-482f-968c-543dc5adc545/lessons/34a24397-2b0f-4c04-9088-1cea220c03b8/concepts/5904c93a-0dbc-4900-80ec-3e5523b56c70

The above lesson has the wrong links to "The Data".

**Comment by mcleonard** [comment]
I believe I fixed this. Thanks!
