### ISSUE TITLE
Lesson 2.4.16 Implementing backpropagation

### ISSUE THREAD

**Issue by adrianstaniec** [udacity/dlnd-issue-reports#318]
Implementing backpropagation

section states:

"Now we've seen that the error in the output layer is

δ​​ =(y−​y​^​​ )f​′(a) "

I don't think that correct. I think the error is just = y-y^

So either description or formula is wrong.
Similar issue with the next formula.

**Comment by lcrucks** [comment]
This would be the error term (as opposed to error, which is indeed y-y^); I've updated that section.  Thanks for pointing this out!
