### ISSUE TITLE
TFLearn_Sentiment_Analysis_Solution Showing Different Results

### ISSUE THREAD

**Issue by chin9699** [udacity/dlnd-issue-reports#319]
The displayed results in TFLearn_Sentiment_Analysis_Solution notebook from GitHub does not match the run results.

When I view the TFLearn_Sentiment_Analysis_Solution notebook, the cell to create and display the training data is different from its actual execution.  The solution notebook, as downloaded from GitHub, shows the training data as such:
![image](https://user-images.githubusercontent.com/23508451/27060828-70c19fde-4f94-11e7-944f-ef5838d5214e.png)

But when I actually execute the cells, the data is different:
![image](https://user-images.githubusercontent.com/23508451/27060861-ae523cbe-4f94-11e7-8bc3-221bcc9dbfe4.png)

Subsequently, after I run the TFLearn_Sentiment_Analysis_Solution notebook to the end, it calculates "Test accuracy: 0.518", instead of "Test accuracy: 0.8504".  This lower accuracy actually matches what my exercise notebook calculates.  So is the problem with the training data?

Thanks,
Ben

**Comment by mcleonard** [comment]
We've removed this lesson from the curriculum so it no longer applies
