### ISSUE TITLE
Instruction to run 1st project ipython notebook different from git file name

### ISSUE THREAD

**Issue by ghost** [udacity/dlnd-issue-reports#321]
On "Your first project", step 2. Project: Your first neural network, there is a instruction to run the jupyter (7.) notebook with "jupyter notebook dlnd-your-first-neural-network.ipynb", but the jupyter file, downloaded from git, has the name "Your_first_neural_network.ipynb", so it's needed to run the command "jupyter notebook Your_first_neural_network.ipynb"

**Comment by lcrucks** [comment]
The directions themselves long ago changed, but there was still a reference to the old jupyter notebook name; that has now been fixed.
