### ISSUE TITLE
Forward-references to sklearn

### ISSUE THREAD

**Issue by nusco** [udacity/dlnd-issue-reports#323]
Part 2, Lesson 7 ("Model Evaluation and Validation") contains multiple references to scikit-learn, which has barely ever been mentioned so far in the training. Maybe it would be good to change the order of topics so this lesson comes after a deeper intro to scikit-learn - or at least, to add a note about installing scikit-learn in the training's conda environment.

**Comment by nusco** [comment]
Part 2, Lesson 7 ("Model Evaluation and Validation") contains multiple references to scikit-learn, which hasn't ever been mentioned so far in the training.

**Comment by mcleonard** [comment]
Thanks for the feedback! We're actually just about to beef up our content for that lesson which will include more scikit-learn material.

**Comment by nusco** [comment]
Good to hear!
