### ISSUE TITLE
Broken environment in "Intro to TensorFlow"

### ISSUE THREAD

**Issue by nusco** [udacity/dlnd-issue-reports#327]
The lab that closes the "Intro to TensoFflow" lesson asks to create a Conda environment named dlnd-tf-lab from an environment.yml file, and then launch a Jupyter notebook in it - but the Jupyter kernel keeps dying as soon as you restart it. Here is the output of "conda list -v" in this broken environment:

# packages in environment at /Users/nusco/Applications/anaconda3/envs/dlnd-tf-lab:
#
appnope                   0.1.0                     <pip>
backports.weakref         1.0rc1                    <pip>
bleach                    1.5.0                     <pip>
cycler                    0.10.0                    <pip>
decorator                 4.0.10                    <pip>
entrypoints               0.2.2                     <pip>
html5lib                  0.9999999                 <pip>
ipykernel                 4.5.0                     <pip>
ipython                   5.1.0                     <pip>
ipython-genutils          0.1.0                     <pip>
ipywidgets                5.2.2                     <pip>
Jinja2                    2.8                       <pip>
jsonschema                2.5.1                     <pip>
jupyter                   1.0.0                     <pip>
jupyter-client            4.4.0                     <pip>
jupyter-console           5.0.0                     <pip>
jupyter-core              4.2.0                     <pip>
Markdown                  2.2.0                     <pip>
MarkupSafe                0.23                      <pip>
matplotlib                1.5.3                     <pip>
mistune                   0.7.3                     <pip>
nbconvert                 4.2.0                     <pip>
nbformat                  4.1.0                     <pip>
notebook                  4.2.3                     <pip>
numpy                     1.11.2                    <pip>
openssl                   1.0.2j                        0  
pexpect                   4.2.1                     <pip>
pickleshare               0.7.4                     <pip>
Pillow                    3.4.2                     <pip>
pip                       9.0.1                    py35_1  
prompt-toolkit            1.0.8                     <pip>
protobuf                  3.1.0.post1               <pip>
psutil                    4.4.1                    py35_0  
ptyprocess                0.5.1                     <pip>
Pygments                  2.1.3                     <pip>
pyparsing                 2.1.10                    <pip>
python                    3.5.3                         1  
python-dateutil           2.5.3                     <pip>
pytz                      2016.7                    <pip>
pyzmq                     16.0.0                    <pip>
qtconsole                 4.2.1                     <pip>
readline                  6.2                           2  
scikit-learn              0.18                      <pip>
scipy                     0.18.1                    <pip>
setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>
sklearn                   0.0                       <pip>
sqlite                    3.13.0                        0  
tensorflow                1.2.0                     <pip>
terminado                 0.6                       <pip>
tk                        8.5.18                        0  
tornado                   4.4.2                     <pip>
tqdm                      4.8.4                     <pip>
traitlets                 4.3.1                     <pip>
wcwidth                   0.1.7                     <pip>
Werkzeug                  0.12.2                    <pip>
wheel                     0.29.0                   py35_0  
widgetsnbextension        1.2.6                     <pip>
xz                        5.2.2                         1  
zlib                      1.2.8                         3

**Comment by mcleonard** [comment]
Will fix environment files. Internal tracking: DLND-991
