### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by kingkastle** [udacity/dlnd-issue-reports#333]
in Object Classification rubric box, the link is not working:

Again, It looks like one version of tf.contrib.layers.fully_connected use ReLU activation by default, while another (1.0) doesn't; ask students to explicitly define their activation function here.

**Comment by kingkastle** [comment]
![Selection_402.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a15a92e39c9a2000d1dc2b/125516c66e82c728ace21e0d46db9196268197a080e78017f40fb2d86b56357c2301a03f32dfa17de71a23075b5647fd105b5746a9ffdd2ba7b76a7883590fffcd7f1d2598694ef1e1c84afd13b032884e8fb7b88344c9e13b26e1828a46390c48.png)

**Comment by kingkastle** [comment]
Probably, this should be the url now: https://www.tensorflow.org/api_docs/python/tf/contrib/layers/fully_connected

**Comment by lcrucks** [comment]
This has now been updated appropriately.  Since the tensorflow version that worked differently is now sufficiently old that few students should have even seen it, I've updated the rubric to reflect the ReLU default activation as well.
