### ISSUE TITLE
test_get_init_cell

### ISSUE THREAD

**Issue by kingkastle** [udacity/dlnd-issue-reports#334]
To prevent the error: prefix tensor must be either a scalar or vector, but saw tensor: Tensor("Placeholder:0", dtype=int32)

In test_get_init_cell, it should be used: test_batch_size_ph = tf.placeholder(tf.int32, []) as here suggested: https://github.com/tensorflow/tensorflow/issues/10213

**Comment by lcrucks** [comment]
Where is this error?

**Comment by kkaneda** [comment]
I got this error from `tv-script-generation` when running with TensorFlow 1.2. My PR is https://github.com/udacity/deep-learning/pull/169, but I'm not totally sure that's the right fix..

**Comment by lcrucks** [comment]
See if this helps https://udacity.atlassian.net/browse/DLND-1148
