### ISSUE TITLE
Passed-in parameter value is overwritten

### ISSUE THREAD

**Issue by ianhamilton117** [udacity/dlnd-issue-reports#335]
In DCGAN Notebook, under the "Building the Model" header, the __init__() function of the GAN class takes a parameter called "alpha" with a default value of 0.2. Several lines down, alpha is passed into the model_inputs() function, but the alpha parameter is reset to 0.2, so the original value of alpha doesn't get used.

**Comment by lcrucks** [comment]
This is correct; alpha is overwritten by 0.2, regardless of what the input parameter is.  The can be rectified by simply removing the '=0.2' from 'self.d_loss, self.g_loss = model_loss(self.input_real, self.input_z,
                                              real_size[2], alpha=0.2)' in block 13 of the notebook [here](https://github.com/udacity/deep-learning/blob/master/dcgan-svhn/DCGAN.ipynb).

**Comment by ianhamilton117** [comment]
Yes, but isn't it misleading to ask the student to choose a value for alpha (in block 16), and then overwrite that value without mentioning it? None of the other hyperparameters are overwritten, as far as I'm aware.

**Comment by lcrucks** [comment]
@ianhamilton117 I was agreeing with you, and letting Mat know what needs to be done to change the notebook.

**Comment by mcleonard** [comment]
Thanks for the feedback. Updating it now.

**Comment by mcleonard** [comment]
Fixed!
