### ISSUE TITLE
Floydhub github page needs updating

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#337]

**Comment by lcrucks** [comment]
Make sure these two pages have matching information:
https://www.floydhub.com/pricing
https://github.com/udacity/deep-learning/blob/master/image-classification/README.md

**Comment by lcrucks** [comment]
Here:
https://github.com/udacity/deep-learning/blob/master/image-classification/README.md

Replace:

Create an account on floydhub.com (don't forget to confirm your email). You will automatically receive 100 free GPU hours.

With

Create an individual account on floydhub.com (don't forget to confirm your email). (You won’t be able to finish most projects in the one hour allowed for free trials).  Prices for floydhub.com are currently $0.432 / hour of GPU use, and most of your projects will run in around 2 - 3 hours.  In order to minimize cost, you may want to try to both debug as much as possible on your local computer and make sure that you end your jobs soon after they finish.

**Comment by mcleonard** [comment]
Do you have this one @lcrucks or want me to change it?
