### ISSUE TITLE
P1 link gives wrong version of project

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#338]

**Comment by lcrucks** [comment]
A student reports that they get the wrong version of the project when they use the download files (e.g. use this link: https://d17h27t6h515a5.cloudfront.net/topher/2017/February/589fdfd3_dlnd-your-first-network/dlnd-your-first-network.zip)

We'll need to update wherever that's kept to match the Github; we've already told students to use Github if they can to avoid this issue.

**Comment by mcleonard** [comment]
Okay, I just removed that link so students will always get the most up to date version.
