### ISSUE TITLE
Live Help Terminated

### ISSUE THREAD

**Issue by adrianstaniec** [udacity/dlnd-issue-reports#339]
During chatting on the live help, suddenly a button shows up to rate feedback. It is no longer possible to enter any message and continue the conversation with the expert. Happend to me twice already.

**Comment by adrianstaniec** [comment]
actually buttons says "Rate Expert" and it happened once again

**Comment by lcrucks** [comment]
This would be because the live help mentor ended the conversation, which can happen if you haven't responded for 10 minutes.   This should not happen suddenly and without warning shortly after you have responded, though; if that happened, feel free to rate the expert accordingly.
