### ISSUE TITLE
Small factual error in "Skip-gram word2vec"

### ISSUE THREAD

**Issue by nusco** [udacity/dlnd-issue-reports#340]
The solution code (and video number 5) state that random.randint() is not inclusive, so the range chosen must be 1 to (window_size+1). Actually, randint() is inclusive - just try random.randint(1, 2) multiple times to see a few 2s come up. So the range should be 1 to window_size.

**Comment by mcleonard** [comment]
Are you sure? Looking at the [documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html), the high value is indeed exclusive. It says 

> Return random integers from the “discrete uniform” distribution of the specified dtype in the **_“half-open” interval [low, high)_**. If high is None (the default), then results are from [0, low)."

**Comment by nusco** [comment]
Oh, my. My confusion was that I didn't realize this was numpy's _random.randint()_. Instead, I thought it was Python's _random.randint()_, which [is inclusive on both values](https://docs.python.org/2/library/random.html). Sorry for the false alarm. 😃
