### ISSUE TITLE
DLNDF issue with tflearn for sentiment analysis

### ISSUE THREAD

**Issue by svijay1973** [udacity/dlnd-issue-reports#342]

**Comment by svijay1973** [comment]
Please refer the issue discussion in the below link...following the given "solution" produces a "very" different result, i.e., a much inferior accuracy

https://discussions.udacity.com/t/v-poor-train-validate-accuracy/314137/8

**Comment by mcleonard** [comment]
We removed that content since it didn't fit in with the rest of the program very well. It was built to support a video Siraj made, but I decided the content works better without that video, so didn't need the TFLearn content anymore.
