### ISSUE TITLE
Subtitles Missing

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#344]
From a student: Subtitles are missing from the lessons 3 and 5 of the Part 4 (Generative Adversarial Networks) of the Deep Learning Nanodegree Foundation.

**Comment by lcrucks** [comment]
Again from the student, clarifying: To be precise, transcripts are missing from the download. In the related videos the subtitles are present.

**Comment by chunkimonkey** [comment]
JIRA ticket open for classroom engineers to fix this issue: https://udacity.atlassian.net/browse/EXP-3448

**Comment by chunkimonkey** [comment]
Student email: umberto.biscotti@gmail.com

**Comment by chunkimonkey** [comment]
Lesson 3 transcripts are present.

**Comment by mcleonard** [comment]
Resolved
