### ISSUE TITLE
P3 original solution no longer runs

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#349]
Original solution gives an error (ValueError: prefix tensor must be either a scalar or vector, but saw tensor: Tensor("Placeholder:0", dtype=int32)) for 'Build RNN Cell and Initialize' cell; check to see if this is because of a tensorflow change and if this would affect students who haven't already completed this section.

**Comment by mcleonard** [comment]
Yeah, TensorFlow has been updated twice since we built this originally. Might not be working in TF 1.2. I'll check
