### ISSUE TITLE
Intro to NN - 15. Implementing backpropagation - some comment for testers?

### ISSUE THREAD

**Issue by Adosha** [udacity/dlnd-issue-reports#35]
There is Note:

Note: If not, this is why we are testing so I can see what sort of reminders need to go here.

just can't understand..
isn' t it some comment for testers?

**Comment by Brok-Bucholtz** [comment]
@Adosha,

Thank for letting us know.  We removed it.

@mcleonard,

Heads up, I removed this reminder.  Not sure if you want to replace it with anything.
