### ISSUE TITLE
Started a Nanodegree before it started

### ISSUE THREAD

**Issue by noamalffasy** [udacity/dlnd-issue-reports#350]
I went to the classroom homepage and then clicked on "Resume learning" and it got me to the beginning of the Nanodegree.
Just to note the Nanodegree was supposed to start a hour later.

**Comment by mkturner** [comment]
Perhaps it could be a time zone issue? Especially so if the timer is based on client time rather than system time. Just a thought.

**Comment by mcleonard** [comment]
Thanks for the feedback. We'll check what caused this.
