### ISSUE TITLE
Replace the word 'understand' to its gerund form

### ISSUE THREAD

**Issue by PabbyG** [udacity/dlnd-issue-reports#351]
Lesson 1 section 4, Program Structure. I think gerund form of the word "understand" should be used in the following sentence: "Generative adversarial networks (GANs) are one of the newest and most exciting deep learning architectures, showing incredible capacity for understand real-world data."

Or, replace the 'for' preceding 'understand' with 'to'.

**Comment by lcrucks** [comment]
Fixed
