### ISSUE TITLE
Update the Project Dates listed under Lesson 1/Projects You will Build

### ISSUE THREAD

**Issue by farsyd** [udacity/dlnd-issue-reports#352]

**Comment by farsyd** [comment]
Or perhaps list the dates in some other way so that they don't have to be manually updated every time a new batch starts.

**Comment by farsyd** [comment]
![Comment.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5985114f306630001f9a6914/125516c66e82c728ace21e0d46cb9b972e878dbdcda5fd53b652fa912a5265296b51fb732883b771e6437a52575d1baa15585e45aaf1802ea2a42062c80d55b98e30063e937f03a6aa8019b500bf208a478cb5bf824fc6ed3437aa.jpeg)

**Comment by mcleonard** [comment]
Thanks! I removed the dates and linked to a file with the deadlines.
