### ISSUE TITLE
Equation in Lesson 2: Neural Nets, Section 14 Multilayer Perceptron wrong

### ISSUE THREAD

**Issue by abhijitapte** [udacity/dlnd-issue-reports#355]
The equation for 
o_k should be sigmoid(sumoverj(w_jk * a_j + b_k)

**Comment by abhijitapte** [comment]
<img width="995" alt="screen shot 2017-08-05 at 6 50 42 pm" src="https://user-images.githubusercontent.com/2939847/28995764-64d74d18-7a0f-11e7-89fe-31365382242f.png">

**Comment by mcleonard** [comment]
Internal tracking: DLND-1158
