### ISSUE TITLE
Dataset points to 404 error

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#358]
Convolutional Neural Networks > Cloud Computing > FloydHub and Data > "the public dataset list here" http://docs.floydhub.com/guides/datasets/​

**Comment by mcleonard** [comment]
looking into this now

**Comment by mcleonard** [comment]
Okay, looks like FloydHub has changed the UI and how you get to data now. So I'll need to go back and fix that.

**Comment by mcleonard** [comment]
Internal tracking: DLND-1149
