### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by madhancr** [udacity/dlnd-issue-reports#359]
Creators of this ND should really take a look at Andrew Ng's new DL course in Coursera. He takes the time to explain all the important concepts. He even takes the time to explain things like numpy broadcasting with examples instead of point to some reference docs. 

Most of the important content in Udacity course in text form. One can just buy books instead. Videos are very brief and some are like commercials racing to finish the concept in 1 min. I don't understand whats the hurry and why videos are so short.  plus, course does not flow well from section to section. I really struggled a lot to finish the first project here. In the end, with help of code posted in forums, was able to submit it. yet, not fully understanding what I just did. Compare this to first project in Andrew Ng's - it prepares you well for the programming assignment and I fully understood what I was doing.  No curve balls like in the first project where the class example used sigmoid for output layer, but project was a regression problem and you are not supposed to use that!

**Comment by mcleonard** [comment]
Thanks for the feedback!
