### ISSUE TITLE
Intro to Neural Networks - OR & NOT Perceptron Quiz

### ISSUE THREAD

**Issue by heyzooi** [udacity/dlnd-issue-reports#36]
I believe there's one wrong value in the correct_outputs variable

now is:

test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]

and I believe should be:

test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, False, False]

notice the 3rd value should be False instead of True

**Comment by Brok-Bucholtz** [comment]
@heyzooi,

I currently see:
```python
# DON'T CHANGE ANYTHING BELOW
# Inputs and outputs
test_inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]
correct_outputs = [True, False, True, False]
outputs = []
```
Try clicking the "RESET QUIZ" button.  That should fix it.  If that doesn't fix it, reopen this issue and let us know.
