### ISSUE TITLE
Quiz Warning

### ISSUE THREAD

**Issue by kingkastle** [udacity/dlnd-issue-reports#362]

**Comment by kingkastle** [comment]
It seems there is an error if parameters are included as ints:
![Selection_142.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a15a92e39c9a2000d1dc2b/125516c66e82c728ace21e0d46db9196268197a080e78012f00fb2d86b56357c2301a03f32dfa17de71a23075b5647fd105b5746a9ffdd2ba7b76a7883590fffcd7f1d2598694ef1e1c84afd13b032884d83b5b68b49c0ea342de48c88463c19040ac4.png)

**Comment by lcrucks** [comment]
I'm having trouble finding this; what cohort are you in (e.g. March, June, August), and where precisely is this?  (Knowing the cohort will help us find the version.)

**Comment by lcrucks** [comment]
No longer relevant (material has been updated)
