### ISSUE TITLE
Add requirements.txt also for Project 5

### ISSUE THREAD

**Issue by ltpitt** [udacity/dlnd-issue-reports#364]
requirements.txt is also missing for Project 5 (in case you want to run it on your computer).

I tried using the same environment for Project 4 but it misses pil.

I tried installing pil with conda and I get:
UnsatisfiableError: The following specifications were found to be in conflict:

pil -> python 2.6*
python 3.5*
Use "conda info " to see the dependencies for each package.
Please provide a working requirements.txt or pointers to solve the issue.

**Comment by mcleonard** [comment]
Thanks! I'll fix this.

**Comment by mcleonard** [comment]
Tracking internally: DLND-991
