### ISSUE TITLE
Anna KaRNNa with 3 number of layers 

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#367]
I tried and agree with the student. Please see the link to discussion thread below. Thanks!

https://discussions.udacity.com/t/ran-sample-got-gibberish-after-only-changing-the-layers-to-3/369090

**Comment by mcleonard** [comment]
Interesting! I'll check this out.

Internal tracking: DLND-1156

**Comment by wallali** [comment]
Hi @lcrucks,

Any reason why this issue was closed? Leaving the issue open while it is being looked at helps other students who try the same thing and realise it is not something they are doing that is causing the strange behaviour.

Thanks
