### ISSUE TITLE
typo in intro to nn: perceptrons

### ISSUE THREAD

**Issue by ltelwest** [udacity/dlnd-issue-reports#37]

**Comment by ltelwest** [comment]
<img width="1261" alt="screen shot 2017-01-29 at 11 37 12" src="https://cloud.githubusercontent.com/assets/7994920/22403436/6d820a16-e617-11e6-8a77-1691d8cd08eb.png">

should be:
Now with this value, we have a complete perceptron formula:

**Comment by Brok-Bucholtz** [comment]
@lennart-telwest,

Thanks for letting us know.  We removed the redundant "now".  Let us know if you see anything else.
