### ISSUE TITLE
Definition of MSE not same in lectures and projects

### ISSUE THREAD

**Issue by ivanbgd** [udacity/dlnd-issue-reports#370]
Hi everyone!

This is a copy from: https://discussions.udacity.com/t/mean-square-error/377598

In the first project, MSE is defined as np.mean((y-Y)**2), but shouldn’t it be 0.5*np.mean((y-Y)**2) instead, like the lecture says?

From Part 2, Lession 2, section 13 (Implementing gradient descent):

https://classroom.udacity.com/nanodegrees/nd101/parts/a66f046b-4885-498e-b036-37ba7d7b0e24/modules/2afd43e6-f4ce-4849-bde6-49d7164da71b/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/4b167ce0-9d45-45e1-bfe6-891b2c68ac94

It is defined as one half there, and I’ve seen in some literature also 1/2. I think it’s because when you derive it, the two '2’s cancel out.

It begins with SSE, from section 10:

https://classroom.udacity.com/nanodegrees/nd101/parts/a66f046b-4885-498e-b036-37ba7d7b0e24/modules/2afd43e6-f4ce-4849-bde6-49d7164da71b/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/7d480208-0453-4457-97c3-56c720c23a891

I think it can be defined both ways, but we should settle on one here, and not have two different definitions in lectures and projects.

**Comment by ivanbgd** [comment]
Sorry, does the "ready" label mean I can close this issue, or something else?

**Comment by Ortalarel** [comment]
The MSE is defined as (x-y)^2, but can also be multiplied by a constant. in this case is 0.5. 0.5 is usually used because of simplification of the BP process.
