### ISSUE TITLE
TensorFlow 1.3 Compatibility Issue

### ISSUE THREAD

**Issue by JSAustin** [udacity/dlnd-issue-reports#373]
https://discussions.udacity.com/t/tensorflow-1-3-unit-test-issues/354168
![image](https://user-images.githubusercontent.com/30268068/31532874-a65b02a0-afa4-11e7-9ccc-04e956a446f3.png)

Can the public github file be updated for tensorflow 1.3? I’d rather learn how to develop RNNs with the current version of Tensor Flow as opposed to an outdated version.  The current version of the file generates an error when running tests for build_nn with TF 1.3.

**Comment by lcrucks** [comment]
Moving this to high priority; this also causes headaches for running the 3rd project that are completely unnecessary.

**Comment by lcrucks** [comment]
https://udacity.atlassian.net/browse/DLND-1148

**Comment by lcrucks** [comment]
Original solution gives an error (ValueError: prefix tensor must be either a scalar or vector, but saw tensor: Tensor("Placeholder:0", dtype=int32)) for 'Build RNN Cell and Initialize' cell; may be also due to this

**Comment by bartmate** [comment]
I agree, this is really annoying and it takes a long time to downgrade tensorflow, if you do it for the first time. I am sure that this is not engaging student to Udacity. :(

**Comment by EibrielInv** [comment]
Hi, any news about this issue? Some students are reaching this projects and loosing tons of time on `build_nn` (Also they are starting to use Tensorflow 1.4)
