### ISSUE TITLE
DeepTraffic has Wrong URL

### ISSUE THREAD

**Issue by xevrem** [udacity/dlnd-issue-reports#374]
deep traffic link in course url: https://classroom.udacity.com/nanodegrees/nd101/parts/bc6e1adc-6149-4d81-a96e-68baf31c1810/modules/1a8f9ad8-4c56-451b-b1d8-0600424a8a67/lessons/0273757e-bd54-42b2-a099-2d9d8c6fb999/concepts/7e3a8e79-acc0-4f77-8eb2-81513d3d1b0d

has wrong URL...

should be: https://selfdrivingcars.mit.edu/deeptrafficjs/

**Comment by mcleonard** [comment]
Fixed!
