### ISSUE TITLE
2NN/L1/5/1:41 - Missing “...”

### ISSUE THREAD

**Issue by bartmate** [udacity/dlnd-issue-reports#377]
2. Neural Network
Lesson 1
5. Higher dimensions
1:41
Right side, under label Boundary:
Missing “...” in formula “w1*x1+w2*x2+wn*xn”

**Comment by Ortalarel** [comment]
Can you please direct us to the specific lesson you are referring to?

**Comment by bartmate** [comment]
2NN/L1/5/1:41:
2.Neural Networks / Lesson 1 - Introduction to Neural Networks / 5. Higher Dimensions / Video: 1:41

**Comment by bartmate** [comment]
See my new comment.

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.
