### ISSUE TITLE
AND Perceptron Quiz: hint mistake

### ISSUE THREAD

**Issue by ltelwest** [udacity/dlnd-issue-reports#38]

**Comment by ltelwest** [comment]
![perceptron formular](https://d17h27t6h515a5.cloudfront.net/topher/2017/January/588bdead_screen-shot-2017-01-27-at-3.58.20-pm/screen-shot-2017-01-27-at-3.58.20-pm.png "perceptron formular")

but the hint says:

```
output = 1, if  weight1*input1 + weight2*input2 + bias >= 0
or
output = 0, if  weight1*input1 + weight2*input2 + bias < 0 
```

while =0 would not output 1 in the quiz code, so it should be:

```
output = 1, if  weight1*input1 + weight2*input2 + bias > 0
or
output = 0, if  weight1*input1 + weight2*input2 + bias =< 0
```

**Comment by Brok-Bucholtz** [comment]
@lennart-telwest,

Thanks for letting us know!  We changed the comparison signs.
