### ISSUE TITLE
Misleading installation steps in Lesson 2, Section 3

### ISSUE THREAD

**Issue by xiatao123** [udacity/dlnd-issue-reports#381]
Following the steps below will install software with much newer version of the python libs. May need to revise the steps.

OS X and Linux
For OS X and Linux, you'll need to install TensorFlow 0.11.0, Python 2.7.9, Pillow 3.4.2, scipy 0.18.1, and numpy 1.11.2.

In your terminal, enter this commands line by line:

conda create -n style-transfer python=2.7.9
source activate style-transfer
pip install tensorflow
conda install scipy pillow

**Comment by Ortalarel** [comment]
Can you please point us to the specific lesson you are referring to?

**Comment by Ortalarel** [comment]
Thank you for your notes
