### ISSUE TITLE
Wrong graphic for Lesson 3, Section 10: Recall

### ISSUE THREAD

**Issue by elberman** [udacity/dlnd-issue-reports#382]
The graphic (rendered on safari) shows 5 correct blue points and 1 incorrect blue point. The answer assumes 6 correct blue points and 1 incorrect blue point.

**Comment by Ortalarel** [comment]
Can you please point us to the specific lesson you are referring to?

**Comment by elberman** [comment]
I just went back to it and it was fixed with a new caption on it. I mislabeled the Lesson, it was Lesson 4, Section 10: Recall. The graphic in the “Recall Quiz"

**Comment by Ortalarel** [comment]
👍
