### ISSUE TITLE
Wrong matrix size

### ISSUE THREAD

**Issue by bartmate** [udacity/dlnd-issue-reports#386]
2.NN/L4/18/General case
It is written that the weights adds up an nxn matrix, however there is only one weight for each dimension, so it should be only a vector (or an nx1 matrix).
If it would be a square matrix, then in E(W) the partial formula (XW)^T-y^T would be problematic, because the first one would be a matrix while the second one is a vector.

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.
