### ISSUE TITLE
3.10 - Quiz image

### ISSUE THREAD

**Issue by jbell303** [udacity/dlnd-issue-reports#387]
The quiz image shows 6 blue dots, with 5 above the prediction line.  There should be 7 total dots, with 6 above the prediction line.  Add a blue dot above the prediction line.

**Comment by Gaasmann** [comment]
I confirm the issue. The graph showed on the question is not identical to the graph showed on the answer.
![question.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a10fcdc1c2c5c00140ed2da/125516c66e82c728ace21e0d46f9819f30968aa681abf301b44fff9e2c4533317346f67328dde57ce61b7a005c574cf9470c5f45fdaf8122a3b22e6c981e5ab38532022d8c6853beb2901eb60bbb258a4e85b0be8349c5e93f22f5c6.png)
![answer.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a10fcdc1c2c5c00140ed2da/125516c66e82c728ace21e0d46e99a89348791ebc3abaf51ab57f5973d047d317c5cfb7376d1ba71be4328595d0a48f841595e12f4f08c2fb4aa2e32db025fb28c341521842f1bbeb98b15be04bb218b4986b6bc824cc9e02f68.png)

**Comment by lcrucks** [comment]
https://udacity.atlassian.net/browse/DLND-1159

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.
