### ISSUE TITLE
Gradient Decent Video typo

### ISSUE THREAD

**Issue by kav** [udacity/dlnd-issue-reports#388]
Y hats are missing their hats

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.

**Comment by Ortalarel** [comment]
Can you please let us know which video specifically?

**Comment by kav** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/0d92455b-2fa0-4eb8-ae5d-07c7834b8a56

**Comment by Ortalarel** [comment]
Thank you
