### ISSUE TITLE
Improper Structure of content

### ISSUE THREAD

**Issue by thoughtexpress** [udacity/dlnd-issue-reports#39]

**Comment by thoughtexpress** [comment]
Hello Team
I am reaching out to you so that i can provide a feedback to the current Udacity Deep learning course. I am on the third lesson where Siraj has already shared coding about Regression. Although it seems that prior to this lesson, there has been no guide /slide about what environment / python versions etc Technical Requirements should be made to proceed with the course without any issues.
There was an 'Anaconda' titled lesson I saw during the proceeding of the first 2 lesssons, but when I rolled back to check, could not find any. 
Can you please help with this issue or point me to the right person to talk to about this.

Thanks,
Ankit

**Comment by dhruvp** [comment]
Hi @thoughtexpress. I've addressed your feedback. If you refresh your classroom you'll see Anaconda and Jupyter are now lessons 2 and 3. Moreover, we moved our introduction to Neural Networks before Siraj's to give you a stronger overview.
