### ISSUE TITLE
Project 1 - Inconsistent description

### ISSUE THREAD

**Issue by bartmate** [udacity/dlnd-issue-reports#390]
In the jupyter notebook of project 1 (Your_first_neural_network.ipynb) it is written that 

"We've built out the structure and the backwards pass. You'll implement the forward pass through the network."

However the backward pass is not fully implemented, it should be finished as part of the project.

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.

**Comment by lcrucks** [comment]
Fixed
