### ISSUE TITLE
Project 1 - Misleading rubric point

### ISSUE THREAD

**Issue by bartmate** [udacity/dlnd-issue-reports#391]
The last but one rubric point for project 1 says:

"he number of output nodes is properly selected to solve the desired problem."

However it seems that the only-one output node is hardwired in the notebook (Your_first_neural_network.ipynb), the test code and the graphs are based on a network having exactly one output node. It seems that there is no decision point in this regard.

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.

**Comment by lcrucks** [comment]
The idea was that it was something that had an absolute correct answer (it's a regression with one value, so the number of output nodes needs to be one), but that we didn't give to the student ahead of time.   Hence, a number that is 'properly selected to solve the desired problem' is 1.
