### ISSUE TITLE
Lesson 4.6 video not showing in Firefox

### ISSUE THREAD

**Issue by kimmw** [udacity/dlnd-issue-reports#394]
The markdown+cells mp4 video at the end of the Markdown cells lesson doesn't show up in Firefox 57.0 on Ubuntu.

**Comment by lcrucks** [comment]
It's showing up in Firefox 55.0.2 (or 57.0, or in various other browsers) on OS X; I'm not sure how to reproduce this.  If the problem is with Ubuntu itself, I'm not sure what can be done to fix it on our end either.
