### ISSUE TITLE
Math typo in Lesson 5.20

### ISSUE THREAD

**Issue by jtsaich** [udacity/dlnd-issue-reports#396]

**Comment by jtsaich** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a17471304c93700149e54f6/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb732883b771e6437a52575d1baa15585e45aaf1802ea2a42062c80d55b98e30063e937f03a6aa8317b500bf218a4b82b3be8d4fc8ec3c37aa.PNG)

Looks like the math here has a typo, x should be y?

**Comment by mcleonard** [comment]
Fixed!
