### ISSUE TITLE
student reported issue

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#402]
In the description of this video. 
https://classroom.udacity.com/courses/nd101-preview/lessons/7cb11162-03a5-4ac7-a205-3b72a6bb33b4/concepts/7e3a8e79-acc0-4f77-8eb2-81513d3d1b0d 
There is a link on the word "here" and it's wrong instead of 
https://selfdrivingcars.mit.edu/deeptrafficjs/ 
the link point to 
https://selfdrivingcars.mit.edudeeptrafficjs/ 
so there is a missing / in the url

**Comment by lcrucks** [comment]
https://udacity.atlassian.net/browse/DLND-1186

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.
