### ISSUE TITLE
student reported issue again

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#403]
It’s at 
Deep Learning Foundation 
Lesson 1: Introduction to Neural Network 
Section 19. Cross-Entropy1, at position 2:17

The picture on the right, -log(0.2) is a typo. It should be -log(0.7)

**Comment by lcrucks** [comment]
https://udacity.atlassian.net/browse/DLND-1185

**Comment by Ortalarel** [comment]
Than you for the note. We are looking into the issue.
