### ISSUE TITLE
The link of Ruder’s blog is out of date

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#405]

**Comment by hidehiro98** [comment]
This is new one.

http://ruder.io/optimizing-gradient-descent/index.html#rmsprop

This blog post looks at variants of gradient descent and the algorithms that are commonly used to optimize them.
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/bb1f6b73-b886-4ed5-ba63-a992faf7d873

**Comment by lcrucks** [comment]
I can't locate the old out of date link.  Has it since been removed?

**Comment by hidehiro98** [comment]
@lcrucks The link is in this page. The link above was wrong. Sorry..
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/ff0ab4d8-5441-4d00-baa3-88735b503b76

**Comment by lcrucks** [comment]
It looks like someone fixed it since we last looked.  Thanks for reporting it!
