### ISSUE TITLE
Improvement to troubleshooting conda instalation

### ISSUE THREAD

**Issue by MichaelGradek** [udacity/dlnd-issue-reports#407]
I found how to troubleshoot conda on stackoverflow before I found it here https://classroom.udacity.com/nanodegrees/nd101/parts/bc6e1adc-6149-4d81-a96e-68baf31c1810/modules/1a8f9ad8-4c56-451b-b1d8-0600424a8a67/lessons/9e9ed61d-20c3-4431-95aa-a1099f28d601/concepts/d45d6e48-ff3a-4192-b377-f0264723f92e

Not sure if many students run into this issue, but maybe consider adding a little more info on how to find the anaconda/bin folder (some people may have anaconda2, anaconda3, installed) and making it more visible? It looks like it's in the "On Windows" section by the size of the subtitle and that's the main reason I didn't find it.

**Comment by Ortalarel** [comment]
Thank you, we will look into that.
