### ISSUE TITLE
Small error in Lesson 8.24

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#408]
Small error in Lesson 8.24: Deep Learning for Cancer Detection; Refresh on Confusion Matrices

_For example, from the entry on the first row and the second column, we can determine that if a patient has illness B, the probability of getting diagnosed with illness A is exactly 0.08._

It should be written as "on the second row and the first column" instead. 

https://discussions.udacity.com/t/l8-deep-learning-for-cancer-detection-small-error/486484

**Comment by lcrucks** [comment]
Fixed; thanks!
