### ISSUE TITLE
Style Transfer

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#409]
For Lesson 2, page 2 in this Nanodegree, "Style Transfer", you might want to add for Windows users that in order for the 'conda' command to work properly after installing Miniconda, they will want to make sure previous Python installs are removed and that they need to Add C:\{your-path-to-Andaconda}\Anaconda3 and C:\{your-path-to-Andaconda}\Anaconda3\Scripts to their PATH variable. Otherwise, it won't be recognized.

**Comment by lcrucks** [comment]
(student recommended improvement)

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLND-1283

**Comment by Ortalarel** [comment]
From another student:
Running the file as presented on Github returns this error: 'ImportError: No module named moviepy.video.io.VideoFileClip'.

Solved it by doing two things:

Pip install moviepy
In evaluate.py, add the following two lines of code right after line 13:
import imageio
imageio.plugins.ffmpeg.download()

It seems like there was a missing dependency, not sure if this happened to others, but felt the need to point it out.

**Comment by Ortalarel** [comment]
Update: I executed the file again without the two lines of additional code I mentioned above and it ran successfully. I think what happened was I was missing a ffmpeg exe file, and I was getting errors asking to download it. Once I did that once it seems to work. Still researching exactly what a ffmpeg is and why it was necessary.

Write
