### ISSUE TITLE
.pem key is private

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#410]
I think it is worth to include the step on how to make .pem file from private to public. 

`chmod 0600 path/to/my-key-file.pem` as this article said.
https://confluence.atlassian.com/bamkb/why-can-t-i-ssh-to-my-elastic-instance-180290491.html

**Comment by lcrucks** [comment]
Projects will be moved to the classroom soon, so this will be solved by that move (as AWS and .pem files will no longer be necessary).
