### ISSUE TITLE
First Neural Network project-my answers not refreshed in notebook

### ISSUE THREAD

**Issue by letyrodridc** [udacity/dlnd-issue-reports#411]
my_answers.py code is not refreshed in the notebook
https://github.com/udacity/deep-learning/blob/master/first-neural-network/Your_first_neural_network.ipynb

These lines aren't in the notebook
```
%load_ext autoreload
%autoreload 2
```

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1255
