### ISSUE TITLE
Gradient descent error

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#414]
From student:
There is an error in your mathematical proof for gradient descent. See attached.

"...derivative of the error E at a point x, with respect to the weight w​j ..." 
​ 
In step 4, on the right hands side of the proof you will see a 1/(1-y^). In the next step, this is changed to -1/(1-y^). I Initially thought this was due to the chain rule being applied to the remainder of the right side (hence the (-1) immediately following this in the next step)), but in reality this -1 was erroneously applied and if left the remainder of the proof will not work out the way that it is written. Please correct this.

**Comment by lcrucks** [comment]
![gradient_descent_proof_error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588b9ba628c7741a00ff4082/125516c66e82c728ace21e0d46ef869b278b86a79bd6bb46b75ef59a3d793761260ba5147597f127ad0037431f1d11f6140b1b56f6eb8c23aebe6a7483555abcd2655d21c06911adb9d417b604be32975dc7e7e2de139db17770a599855d3f170f198cfe5e3da9984ec05bfe49e05f18.png)

**Comment by LivingProgram** [comment]
The proof is indeed wrong
