### ISSUE TITLE
Misspelling in cancer detection

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#417]
veredict -> verdict

https://classroom.udacity.com/nanodegrees/nd101/parts/b9c4c3c3-b524-427b-8832-9d0748f14a2e/modules/cb574ac4-7144-4ba5-97b9-1c1265525ff8/lessons/54e18898-2666-445d-ba5c-ecab62a61d00/concepts/536af98c-9002-4fe3-b6a1-4b02ce171a5a

**Comment by lcrucks** [comment]
Fixed, thanks!
