### ISSUE TITLE
Explanation in the video is a little bit different

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#419]
https://classroom.udacity.com/nanodegrees/nd101/parts/6df11d93-4b44-4f35-b410-a63b2e852bb9/modules/96aa308a-b292-4506-b9f1-3e80821676ce/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/7b7c1680-19e1-46c5-a48a-143ad051254c

**Comment by hidehiro98** [comment]
![Screen Shot 2017-12-30 at 9.21.04.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a1939b30ba47e00111f6099/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216457f36b7191a371f1102a4f5f5b5cb053181d1ba6acda6fb4bc2e75825403bbd5645625973e19aeed844bbf00bb76834680b2ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4acc5dff48e44553a5173671ab.png)

Should Gated Recurrent Networks be Gated Recurrent Units?

**Comment by Ortalarel** [comment]
You are correct that GRU is short for Gated Recurrent Unit. In the context of this lesson, using the phrase Networks is not a mistake.  Further explanation of GRUs is given the the text below the video.
