### ISSUE TITLE
Cannot submit linear regression quiz

### ISSUE THREAD

**Issue by exit99** [udacity/dlnd-issue-reports#42]
There's an error with the code
Click "Test Run" to see the error message

```python
# TODO: Add import statements
import pandas
import sklearn

# Assign the dataframe to this variable.
# TODO: Load the data
bmi_life_data = pandas.read_csv("bmi_and_life_expectancy.csv")

# Make and fit the linear regression model
#TODO: Fit the model and Assign it to bmi_life_model
bmi_life_model = sklearn.linear_model.LinearRegression()
bmi_life_model.fit(bmi_life_data[["BMI"]], bmi_life_data[["Life expectancy"]])

# Mak a prediction using the model
# TODO: Predict life expectancy for a BMI value of 21.07931
laos_life_exp = bmi_life_model.predict([[21.07931]])
```

**Comment by exit99** [comment]
The output from the "test quiz" button does not produce an error (shrug)

**Comment by jg1141** [comment]
On the page
https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/18a1c995-b59c-4d70-910f-f592c5689bb5

I get 
Nice!  You got it all correct.

Input 1    Input 2    Confidence    Activation Output   Is Correct
      0          0          -1.0                    0          Yes
      0          1           0.0                    0          Yes
      1          0           0.0                    0          Yes
      1          1           1.0                    1          Yes

from [Test Run]

But 
Try Again
That's not the correct answer.
TRY AGAIN

from [Submit Answer]

**Comment by Brok-Bucholtz** [comment]
@jg1141,

Please open up a new issue for that error.

**Comment by Brok-Bucholtz** [comment]
@Kazanz,

I fixed the error.  It had to do with python not able to find the `sklearn.linear_model`.  Thanks for letting us know.
