### ISSUE TITLE
In backpropagation quiz of RNN, equation marks are different

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#420]
https://classroom.udacity.com/nanodegrees/nd101/parts/6df11d93-4b44-4f35-b410-a63b2e852bb9/modules/96aa308a-b292-4506-b9f1-3e80821676ce/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/d9e54163-c08b-471d-b83a-9bfed326699c

**Comment by hidehiro98** [comment]
![Screen Shot 2017-12-30 at 17.38.43.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a1939b30ba47e00111f6099/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216457f36b7191a379e80c2859415b4dbe5d4a1f06a3a3dc78e2a436628f5403e58769567d976c12a4bad719eb01bb21dd478cb3b89850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec95cf049e24f56ac1a3467f43b.png)

**Comment by Ortalarel** [comment]
Can you please elaborate on the issue here?

**Comment by Ortalarel** [comment]
Thank you for pointing that out. The issue has been fixed.
