### ISSUE TITLE
Misspelling in RNNs

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#421]
tilmestep -> timestep

https://classroom.udacity.com/nanodegrees/nd101/parts/6df11d93-4b44-4f35-b410-a63b2e852bb9/modules/96aa308a-b292-4506-b9f1-3e80821676ce/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/9528e9b5-7b59-49be-bbbc-fd3f3e697e55

**Comment by lcrucks** [comment]
Corrected, thank you!
