### ISSUE TITLE
No round delta of s(t+3) in equation 50

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#422]
https://classroom.udacity.com/nanodegrees/nd101/parts/6df11d93-4b44-4f35-b410-a63b2e852bb9/modules/96aa308a-b292-4506-b9f1-3e80821676ce/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/593835fd-09a7-44a3-a1fc-56dadb02b2ca

**Comment by Ortalarel** [comment]
Thank you. We fixed the issue.
