### ISSUE TITLE
Equation number mistakes in RNN lecture

### ISSUE THREAD

**Issue by hidehiro98** [udacity/dlnd-issue-reports#423]
https://classroom.udacity.com/nanodegrees/nd101/parts/6df11d93-4b44-4f35-b410-a63b2e852bb9/modules/96aa308a-b292-4506-b9f1-3e80821676ce/lessons/72ae4549-d6b9-4634-93c6-24964a41e598/concepts/514cf09c-9651-4877-8b2c-d651bca3cd16

First, in this part (Explanation of equation 23), equation 9 means equation 21.
The second calculation of equation 9 can be calculated the following way:

Second, this part (Explanation of equation 24) as well
After understanding how to treat each multiplication of equation 9 separately, we can now summarize it the following way:

Lastly, this part (Explanation of equation 25), this equation 5 should be equation 17
We are ready to finalize step 2, in which we update the weights of matrix W ​1 ​​ by calculating the gradient shown in equation 5. From the above calculations, we can conclude that:

**Comment by hidehiro98** [comment]
This is a forum thread for this topic.
https://discussions.udacity.com/t/are-the-equation-number-wrong/501170

**Comment by Ortalarel** [comment]
Thank you very much for noticing that! These mistakes have been corrected.
