### ISSUE TITLE
Test Notation Differs

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#424]
Deep Learning Nanodegree->Recurrent Network->Lesson2->part8 
Test notation is different from what the instructor is saying.

**Comment by lcrucks** [comment]
![Lesson2_Part8.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588b9ba628c7741a00ff4082/125516c66e82c728ace21e0d46c49189308d8dfbb0d9be51b005b2d86b56357c2301a03f32dfa17de71a23075b5647fd105b5746a9ffdd2ba7b76a7883590fffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98b49c1eb3427ef8e874c3f0c48.png)

**Comment by Ortalarel** [comment]
The test gives a link to another overview of LSTMs. Using what the instructor had shown along with extra help form the link (if needed) , is enough to solve the quiz.
