### ISSUE TITLE
"Forum" link is unavailable

### ISSUE THREAD

**Issue by the-vampiire** [udacity/dlnd-issue-reports#427]
Lesson 1.5 - Community Support

the "forum" link (https://discussions.udacity.com/c/nd101-Project-1/) fails with the following error

`Oops! That page doesn’t exist or is private.`

**Comment by the-vampiire** [comment]
![Screen Shot 2018-01-09 at 3.17.43 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a04be24bf3d81001222cbfd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226454fa6b7191a37bf1132c4f5b5c5ecc3c4a4356bcbbd671f3e57862804e0ee5d9650970cf3440fdbb8a1dea07ee208a4ed3beb58f48d2f42f67b6d5db1063474f4dcbed5727a19041c95df74ee44f5ca6163662e1712431.png)

**Comment by Ortalarel** [comment]
The link is active. To have permission and access you will need to use the link through the classroom.  After that, the external links should work as well. 
Please let us know if you have further issues.
