### ISSUE TITLE
Programming Quiz: Multiple Linear Regression

### ISSUE THREAD

**Issue by harishsinha11** [udacity/dlnd-issue-reports#43]
In the intro it's given that there are 12 features of a house whereas when we were asked to predict the target, the sample_house contained 13 features. I further tried finding the number of features per house entry in the training data and found it 13 too. In the intro, I think the mistake should be corrected.

**Comment by Brok-Bucholtz** [comment]
@harishsinha11,

This has been corrected.  Thanks for letting us know.
