### ISSUE TITLE
2.1.19 mislabeled point in video

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#433]
In Unit 2, Lesson 1, part 19 (Cross-Entropy 1) the video at 2:12 has a mislabeled point in the graph on the right. The point that is labeled "-log(0.2)" should be labeled "-log(0.7)". If the video can't be changed, a note below the video could alert people to this mistake.

**Comment by Ortalarel** [comment]
Thank you for noticing that. We will fix the issue.
