### ISSUE TITLE
Lesson 9 Tensorflow Input Section 4 Quiz

### ISSUE THREAD

**Issue by emanuelegit** [udacity/dlnd-issue-reports#434]
Running the correct code:

# Quiz Solution
# Note: You can't run code in this tab
import tensorflow as tf

def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        output = sess.run(x, feed_dict={x: 123})

    return output

Lead to the wrong result (it looks like a Python 2 vs 3 issue):

Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_tbtoquboge/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_tbtoquboge/studentMain.py", line 1, in <module>
    from all import run_python3_shell
  File "/tmp/vmuser_tbtoquboge/all.py", line 17
SyntaxError: Non-ASCII character '\xc3' in file /tmp/vmuser_tbtoquboge/all.py on line 17, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by lcrucks** [comment]
Thanks for reporting this!  This issue is being followed internally on a different waffle issue: https://waffle.io/udacity/dlnd-issue-reports/cards/5a6207c015886c007eb45e73
