### ISSUE TITLE
LaTex Mathematical formulas in text not rendered correctly

### ISSUE THREAD

**Issue by taavikuusik** [udacity/dlnd-issue-reports#438]

**Comment by taavikuusik** [comment]
All throughout the Neural Network lessons math formulas are broken and look like this:  "E = -\frac{1}{m} \sum_{i=1}^m \left( y_i \ln(\hat{y_i}) + (1-y_i) \ln (1-\hat{y_i}) \right) ". SOME are not broken, but about half seem to be.

**Comment by lcrucks** [comment]
Additional LaTex problems from other students:

In Lesson3 of the reinforcement learning class a lot of the mathematical notations (I assume it's written in latex) is broken and come out as a code rather than as notations.

**Comment by lcrucks** [comment]
Additional Case:
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588b9ba628c7741a00ff4082/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51fb732883b771e6437a52575d1baa15585e45aaf1802ea2a42062c80d55b98e30063e937f03a6aa8317b500bf218d4b82bfbc894bc0e83d37aa.PNG)

**Comment by Ortalarel** [comment]
Thank you for reporting the problem. We had a LayTex issue at the time you saw these equations. All equations have been corrected.
