### ISSUE TITLE
Backpropagation confusion

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#439]
From a student:

In the last video in Lesson1.33 (Backpropagation) at 3:10 Luis says : "we have already calculated the first one, the derivative of E with respect to y-hat. And if you remember, we got y-hat minus y". 
Excuse me, but I don't remember. There were no calculations of it. And I can't find the way the derivative of this: 
-y*ln(y^) - (1-y)*ln(1-y^) 
with respect to y-hat is simply "y-hat minus y" 
OK, we've calculated the gradient in Lesson1.23, but we used another approach, which's development is at least described in the instructor notes. But later in Lesson2 we use Squared Error function: 
E = sqr(y - y^)/2 
And voila, it's derivative with respect to y-hat is exactly "y-hat - y" (Well if I had a time machine, I would remember it in Lesson1.33).

**Comment by Ortalarel** [comment]
Thank you for for your notes. We are looking into it.
