### ISSUE TITLE
Intro to NN - 15 - Typo

### ISSUE THREAD

**Issue by antevis** [udacity/dlnd-issue-reports#44]
..where z is the input to the output unit.

'z' -> 'a'

**Comment by clapollo** [comment]
I'm not convinced this is incorrect. I need more direction to decide whether to change it.

**Comment by clapollo** [comment]
I've closed this because as far as I can tell, it should be z, not a. If you disagree, please provide more details explaining why, including the exact function you're discussing and why you think the variable names are incorrect.
