### ISSUE TITLE
Video 2.1.19 @ 2:20 : Wrong value

### ISSUE THREAD

**Issue by eliaskousk** [udacity/dlnd-issue-reports#446]
In video 2.1.19 @ 2:20 the probability of the point on the top right of the right plot is wrong (0.36) and needs to be like on the bottom right point of the left plot (1.61).

**Comment by lcrucks** [comment]
This issue is being tracked at https://waffle.io/udacity/dlnd-issue-reports/cards/5a613da06aaadf0062eaf677 (433); I'll close this duplicate.  Thanks for reporting it!

**Comment by eliaskousk** [comment]
Thanks, it seems I also suggested the wrong change, the other issue has it correct.
