### ISSUE TITLE
6.2.5 Dead Link

### ISSUE THREAD

**Issue by elberman** [udacity/dlnd-issue-reports#447]
Link to Rahimi & Recht, 2007 paper generates a 404 error under Q-Learning video in Reinforcement Learning section

**Comment by lcrucks** [comment]
Located here: https://classroom.udacity.com/nanodegrees/nd101/parts/7d0218b1-1a81-4d49-95f7-14b015020851/modules/691b7845-f7d8-413d-90c7-971cd5016b5c/lessons/2faec296-1a78-4393-9aea-2b91310713ed/concepts/b0f459db-00d1-4bc7-bf67-0c4dab3c9fcd

Internal ticket: https://udacity.atlassian.net/browse/DLAND-11

**Comment by elberman** [comment]
If I'm not mistaken, that link just takes you back to the video...not to the paper by Rahimi & Recht
