### ISSUE TITLE
Updated Link: VMWare Workstation

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#448]
Student's post here https://discussions.udacity.com/t/updated-link-vmware-workstation/547058

_the download link on the VMWare site has changed since the notebook was written._

_I have found this link works -_
https://www.vmware.com/products/workstation-player/workstation-player-evaluation.html

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLAND-12

**Comment by napratin** [comment]
Fixed!
