### ISSUE TITLE
2.2.8 TeX equations not rendering

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#449]
In Unit 2, Lesson 2, Section 8 "Implementing Backpropagation", the equations above the heading "Backpropagation Exercise" are not rendering.

**Comment by lcrucks** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/0e07fafa-e796-4fab-b119-13f47f1d5c1b/concepts/b2bbdc9a-9f48-4735-b408-71cf67f5b000

**Comment by Ortalarel** [comment]
Thank you for your comment. We fixed it.
