### ISSUE TITLE
Idea: fully qualify the names of the demo.py files

### ISSUE THREAD

**Issue by krismatson** [udacity/dlnd-issue-reports#45]
I have multiple "demo.py" files in my editor after following just a few lessons the past couple of days and it's messing with my workflow :-(. Suggest fully qualifying the main .py file names, such as:
"make_a_neural_network_demo.py"
instead of "demo.py" 
This will jumping from project to project SO much easier.

**Comment by oritavital** [comment]
Thank you for the feedback. That is indeed good suggestion, we'll make sure to follow it going forward.
