### ISSUE TITLE
Synchronize Lesson progress accross device

### ISSUE THREAD

**Issue by macfly1202** [udacity/dlnd-issue-reports#450]
Is there a way to reset progression on a lesson? There is serious synchronisation lesson progress issues between linux, my iPhone and iPad. Neither are synchronize. I must close all session, And perhaps after that, it will be ok on iPhone or iPad. My iPad just start to play next session lesson don't know why. For me, it's really a pain to see a 'false progress' (advance is the worst,  or late).

**Comment by lcrucks** [comment]
There isn't currently a way to reset progression, to my knowledge.  I can file an engineering ticket for this, but one possible issue is that the iPhone and iPad can play lessons offline, and that very ability allows for synchronization issues.  Could you check to see how quickly it takes to synchronize when everything is online?  (And what conditions it takes?)
