### ISSUE TITLE
Project 2 Rubric typo

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#453]
First line: "Subission Files"

Should be --> "Submission Files"

**Comment by lcrucks** [comment]
Hi, could you give an image to show what you mean?  I'm not finding that typo.

**Comment by sbbogdan** [comment]
Looks like somebody fixed it already. I had originally submitted this to
the slack channel two weeks ago, and just recently copied to waffleboard as
it appears that is the preferred method for resolving issues now. Looks
like it was fixed somewhere in between. You can resolve this as no-repro.

**Comment by lcrucks** [comment]
ok, thank you!
