### ISSUE TITLE
(RNN's): Mismatch in equation reference numbers inline, versus in narrative

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#454]
Throughout Section4.Lesson1.Step18 multiple references are made to equation numbers throughout the narrative paragraph notes. For eaxmple: "" If you look closely at equations 2, 3 and 4, you will notice a pattern."

However, there exists no equations 2, 3, or 4. Instead these equations (via logical inference) are labeled 38, 39, 40. Please synchronize the narrative and actual equation numbers.

**Comment by Ortalarel** [comment]
Thank you for noticing that mistake. The correct sentence should be:  If you look closely at the three components of equation 41, you will notice a pattern.

That has been corrected.
