### ISSUE TITLE
2.8.2 Keras: "input" should say "hidden"

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#459]
In this code block comment:
" # 1st Layer - Add an input layer of 32 nodes with the same input shape as
 # the training samples in X"
'input' should say 'hidden', I think

**Comment by lcrucks** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1355
