### ISSUE TITLE
Outdated link for jupyter kernels

### ISSUE THREAD

**Issue by wtrott** [udacity/dlnd-issue-reports#46]
Currently the link in the second to last paragraph of the "What are Jupyter notebooks?" lesson points to the IPython list that tells you to go to the Jupyter list instead. It seems better to link to the Jupyter list directly.

https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

**Comment by mcleonard** [comment]
Thanks for spotting that. Fixed the link.
