### ISSUE TITLE
2.9.9 test run breaks view

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#463]
Clicking the Test Run button on the quiz at the bottom makes the view go to the top of the page, so I have to scroll all the way back down each time to see the results. This may be a problem with all quizzes. Using Chrome on Windows.

**Comment by Ortalarel** [comment]
Can you please be more specific as to which lesson you are referring to? you mention 2.9.9 , but I am still not sure. Thanks!
