### ISSUE TITLE
Please articulate a threshold with 'embeddings' notebook (Skip-Gram_word2dev)

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#465]
In subsampling programming/assignment section, no threshold value is given. This left me searching around for one in the notebook for a while and, worse, made me presume I was missing something. Solution notebook appears to assign arbitrary threshold value. Please make desired threshold value explicit, this was unnecessarily difficult to locate/work through!

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1353
