### ISSUE TITLE
2.4.2 mistake in text

### ISSUE THREAD

**Issue by RodolfoAndrade** [udacity/dlnd-issue-reports#466]
There is a mistake in this: "Sometimes in the literature, you'll see False Positives and True Negatives (should be False Negative) as Type 1 and Type 2 errors."

**Comment by Ortalarel** [comment]
Can you please indicate which lesson you are referring to?

**Comment by RodolfoAndrade** [comment]
Extracurricular - 1. Additional Lessons - Lesson 1: Evaluation Metrics - 2. Confusion Matrix:
The title of the text is "Type 1 and Type 2 Errors"

**Comment by Ortalarel** [comment]
thank you for the feedback. Yes, we are aware of the issue and will fix it.
