### ISSUE TITLE
Into to NN - 12 Implementing Gradient Descent - Implementing with Numpy  - weights initialization code wrong

### ISSUE THREAD

**Issue by chirwin** [udacity/dlnd-issue-reports#47]
A good value for the scale is 1/√
​n​ where n is the number of input units. This keeps the input to the sigmoid low for increasing numbers of input units.

weights = np.random.normal(scale=1/n_features**-.5, size=n_features)

either the 1/ should be removed
OR
it should be n_features**0.5

**Comment by mcleonard** [comment]
Should be fixed. If you're still seeing the negative sign there, try pressing "Reset Quiz"

**Comment by totogo** [comment]
In the article it is still :
```
weights = np.random.normal(scale=1/n_features**-.5, size=n_features)
```
```-``` or ```1/``` should be removed. 

But in the code it is fixed
```
weights = np.random.normal(scale=1 / n_features**.5, size=n_features)
```
