### ISSUE TITLE
Deadlines for Feb Cohort Missing

### ISSUE THREAD

**Issue by dsc03** [udacity/dlnd-issue-reports#470]

**Comment by mpinner** [comment]
also, i got confused a bit by this and added the wrong deadlines to my gcal

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1354

**Comment by SherylHohman** [comment]
Me too. Feb cohort was at the top, so I also added Feb  calendar, instead of Jan.  Each Term enrollment should show their deadlines at the top.
