### ISSUE TITLE
Running code for style-transfer: missing packages.

### ISSUE THREAD

**Issue by dsc03** [udacity/dlnd-issue-reports#472]
Running the file as presented on Github returns this error: 'ImportError: No module named moviepy.video.io.VideoFileClip'.

Solved it by doing two things:
1) Pip install moviepy
2) In evaluate.py, add the following two lines of code right after line 13:

import imageio
imageio.plugins.ffmpeg.download()

It seems like there was a missing dependency, not sure if this happened to others, but felt the need to point it out.

**Comment by dsc03** [comment]
Update: I executed the file again without the two lines of additional code I mentioned above and it ran successfully. I think what happened was I was missing a ffmpeg exe file, and I was getting errors asking to download it. Once I did that once it seems to work. Still researching exactly what a ffmpeg is and why it was necessary.

**Comment by Ortalarel** [comment]
Thank you for the update.
