### ISSUE TITLE
2.2.8 Quiz 'Test Run' repeatedly returns 'program shut down for using 13 CPU seconds'

### ISSUE THREAD

**Issue by jwallman** [udacity/dlnd-issue-reports#475]
contrary to the note below the quiz a second, third or even tenth run of the program does always complete with the same error. 

this happens even when executing the solution.py. So errors in the user's script can be excluded as origin of the problem

**Comment by lcrucks** [comment]
While I couldn't reproduce the error (as the servers seem to be faster at the moment), the allowable time should be double (26 seconds) now.
