### ISSUE TITLE
Implementing Backpropagation assignment just times out every time

### ISSUE THREAD

**Issue by bradengroom** [udacity/dlnd-issue-reports#476]
I'm working on the backpropagation exercise. There is a note saying to retry if things timeout. I've retried probably 20 times now and I just get "program shut down for using 13 CPU seconds". I've even copy/pasted in the solution to confirm it wasn't me. Even using the provided solution I can only get timeouts.

**Comment by lcrucks** [comment]
Doubled allowable time so this shouldn't happen.  (I couldn't reproduce, but you should now have 26 seconds on this problem instead of 13)
