### ISSUE TITLE
Generate faces project has step 'One Project Away!' - but we're not!

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#479]
The 'Generate Faces' Project #4 has a first step which is 'One Project Away!' where Mat exclaims this is the last project before graduating.

Except it's not. We also have the quadcopter project #5 that's required for graduation? It seems like this step/video should be removed?

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1341

Thanks for reporting this!
