### ISSUE TITLE
Typo: https://in.udacity.com/course/natural-language-processing-nanodegree--nd889-innlp

### ISSUE THREAD

**Issue by quickrworld** [udacity/dlnd-issue-reports#481]
The word start is spelt as stat:

What are you going to learn
In this Nanodegree you will stat with an introduction to neural networks. Learn to ...

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/NLPND-39

**Comment by raderonmu** [comment]
This now redirects to an update to date NDOP that does not have this typo: https://in.udacity.com/course/natural-language-processing-nanodegree--nd892
