### ISSUE TITLE
Lesson 1: Ch 9 Perceptron Trick

### ISSUE THREAD

**Issue by spointr** [udacity/dlnd-issue-reports#483]

**Comment by spointr** [comment]
For the second example, where the line is described by 3x1+ 4x2 - 10 = 0, if the learning rate was set to 0.1, how many times would you have to apply the perceptron trick to move the line to a position where the blue point, at (1, 1), is correctly classified?

Shouldn't the accept answer be 11 ? Because the 10th iteration just puts the point on the line.

**Comment by Ortalarel** [comment]
Hi, and thank you for your comment. For issues of this nature please refer to the forums or mentors.
