### ISSUE TITLE
Possible error in equation

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#484]
In RNN unit, Lesson 1, part 9 "Backpropagation - Example (part a)" the equation right above Equation 11 might have an error. The line of equations under the word "Therefore" has a final equality at the right that starts with "2(alpha/2)". I don't think this final part is right.

**Comment by Ortalarel** [comment]
Where do you see the error? (there is an internal derivative to (-y), which cancels the negative sign). Curious what you are referring to.

**Comment by joebenderweb** [comment]
It's been a little while since I've done calculus so I wasn't sure of an error, but I thought the d(d-y)^2 should produce a 2(d-y) next to the d(d-y). I see the 2 there next to the alpha/2, but not the (d-y).

**Comment by joebenderweb** [comment]
I'm still not sure why the negative is canceled, since the derivative of (d-y)^2 with respect to (d-y) is 2(d-y), which is multiplied by deriv. (d-y) with respect to the weight to complete the chain rule for deriv. (d-y)^2 with respect to the weight.

**Comment by joe-bender** [comment]
![equation](https://user-images.githubusercontent.com/20362667/36512160-274c49e2-1737-11e8-8d6e-d338ed968e80.PNG)
Just to be sure we are talking about the same equation

**Comment by joe-bender** [comment]
![equation_sketch](https://user-images.githubusercontent.com/20362667/36512445-72339aa4-1738-11e8-804c-2e0d7e2c1cb7.png)
I think this is what should be inside the blue circle, but that everything else is correct. Is that right?

**Comment by Ortalarel** [comment]
that is right. If you look at equation 11, you can see (d-y) there. since d is a constant, its derivative was zero, and we are left with the derivative of y.

**Comment by Ortalarel** [comment]
Oh! I see what you are referring to! yes! thank you for that!

**Comment by joe-bender** [comment]
Yes, just that intermediate step. Is my math right?

**Comment by Ortalarel** [comment]
yes, it's correct. you will the the correction soon in the classroom.

**Comment by joe-bender** [comment]
Thanks for all the updates. I know I submitted a lot of them yesterday.

**Comment by Ortalarel** [comment]
We appreciate all of them. Thank you.

**Comment by joe-bender** [comment]
The negative sign is still missing it looks like.

**Comment by Ortalarel** [comment]
no, the negative sign is cancelled out with the additional negative sign that came from the (-y)

**Comment by joe-bender** [comment]
Doesn't that happen only after the blue circled part is simplified? The negative sign gets cancelled once we change d(d-y) to d(y), which hasn't happened yet in the blue circled part.

**Comment by Ortalarel** [comment]
yes, that was added with (d-y)

**Comment by joe-bender** [comment]
I see the (d-y) was added but maybe the negative sign in front is not rendering.

**Comment by joe-bender** [comment]
It gets cancelled in the last step but should still be there in the second to last step.

**Comment by joe-bender** [comment]
Now it looks right. Thanks

**Comment by Ortalarel** [comment]
NP, thanks for catching the (d-y) issue.
