### ISSUE TITLE
Single weight referred to as matrix

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#485]
In RNN unit, Lesson 1, part 11 "Backpropagation Quiz", the quiz question says "What is the update rule of weight matrix W1?" W1 is a single weight in the network and not a whole matrix, so the word "matrix" should be removed from this sentence. I'm 90% sure, so please double check this is correct before changing.

**Comment by Ortalarel** [comment]
Thank you for the comment. In this quiz, there are different dimensions to some of the matrices. a vector (which is one of  the cases here), is a matrix with a single column or a single row.

**Comment by joe-bender** [comment]
I understood W1 in the diagram to be the weight going from the single neuron in the input (X) to the first neuron in the first hidden layer (h1). Is W1 a vector? I thought W1 and W4 together would make up the weight matrix from the input to the first hidden layer, and I'm having trouble seeing how W1 could be a vector if it is going from a single neuron to another single neuron.

After typing that, I now see that X is not a single neuron but could be any number of neurons, which means W1 is a vector connecting all of those to h1. I would think of W1 and W4 together as the first weight matrix, but thank you for explaining that a single vector from the matrix is itself also a matrix.
