### ISSUE TITLE
Double meaning of variable in confusing equation

### ISSUE THREAD

**Issue by joe-bender** [udacity/dlnd-issue-reports#486]
In the RNN unit, Lesson 1, Part 10 "Backpropagation- Example (part b)", equations 17 and 25 use the j variable as part of the sum but also as a placeholder, so it's not clear which j is which. The video on the same page at 2:14 uses a 'p' in a more generalized version of the equation. This makes it clear which letter is part of the sum and which isn't.

**Comment by Ortalarel** [comment]
Thank you for that. Spot on. We fixed it.
