### ISSUE TITLE
Subtitles missing

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#488]
From a student:

I enrolled Deep Learning Foundation Nanodegree program. 
And I study using subtitle for video. 
but I have some problem

first, subtitle file is not same for video file name. 
very confusing! 
so, I changed subtitle file name to same video file name. 
but i found missing the subtitle file that is for

1 - Introduction.mp4 
43 - DL 41 Feedforward FIX V2.mp4 
44 - DL 42 Neural Network Error Function (1).mp4 
48 - DL 46 Calculating The Gradient 2 V2 (2).mp4

in introduction to neural networks section. 
I hard to study without subtitle.

**Comment by lcrucks** [comment]
So those 4 videos lack subtitles (according to the student)

**Comment by Ortalarel** [comment]
Can you see the videos directly from the classroom? Can you send us the links to the videos? thank you!

**Comment by springloops** [comment]
I download subtitles and translate for my contry language for study.
but these video’s subtitle files are not exist in lesson resource page.
[Uploading 36440C9C-E82F-4241-91CC-58B64EF2784E.jpeg...]

**Comment by Ortalarel** [comment]
Hi! We have looked through all of the NN videos (in the DL nanodegree), and found that they all have subtitles. I still do not understand which videos you are not finding subtitles for. 
Can you send a link (not the name) ? We want to help you understand the lessons. Thank you

**Comment by springloops** [comment]
Hi, I paste url address.

transcripts in zip link (https://s3.amazonaws.com/zips.udacity-data.com/93d158ce-25e1-4fc1-a187-162982e3cef7/409890/1513131580502/Introduction%20to%20Neural%20Networks%20Subtitles.zip)

 in this page  (https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/7a42d26d-7d7e-4c76-a014-5bf8b4413179 
)
