### ISSUE TITLE
Use Gate/Output Gate Error

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#489]
From a student:

It seems like content needs to be updated. The Use Gate/Output Gate does not take input directly from the Forget Gate as indicated. Instead, it takes uses the output of the Remember Gate (which is a sum of the outputs of the Forget and Learn Gate) and uses it as input. Accordingly, the formulas in this video need to be fixed as well.

**Comment by lcrucks** [comment]
![Screen Shot 2018-02-18 at 9.17.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/588b9ba628c7741a00ff4082/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455fb6b7191a371f1132c4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5d9650970cf3440fdbb8a1dea07ee208a4ed3beb58f48d2f42f67b6d5db1063474f4dcbed5727a19041c95df742e34550a4123466e0732431.png)

**Comment by Ortalarel** [comment]
Thank you for the input. We try to update our content frequently. We appreciate the feedback.
