### ISSUE TITLE
equation typo

### ISSUE THREAD

**Issue by XkhldY** [udacity/dlnd-issue-reports#49]
Implementing gradient descent

f(h)=1/(1+e​−x​​ )

**Comment by clapollo** [comment]
I'm not sure if this is complaining that the x should be an h (to match up with the f(h)) or if the equation used to say e-x instead of e to the power of -x. Thoughts?

**Comment by dhruvp** [comment]
I think it's a suggestion that it should be only `h` or only `x`. Combining the two seems incorrect

**Comment by clapollo** [comment]
Thanks! Went with h. (Looks funny to me, but makes sense mathematically.
