### ISSUE TITLE
typo in C2.P1

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#490]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/4c03fd28-20ca-40e6-89cc-e72ae96141c2/project

"`my_answers.py`python file" is missing a space, it should be
" `my_answers.py` python file"

**Comment by lcrucks** [comment]
Fixed!  Thanks for reporting.
