### ISSUE TITLE
Implementing of Iterative Policy Evaluation: Tests not passed

### ISSUE THREAD

**Issue by RevenNiaga** [udacity/dlnd-issue-reports#491]
I am trying to implement the iterative policy evaluation algorithm in the mini project in concept 9. I don’t see any errors in my code but can’t pass the test supplied. Please see my forum post with the same header for reference to my solution.

**Comment by lcrucks** [comment]
Raised the issue with forum mentors; feel free to re-raise the issue here if it turns out there is an error with the mini project itself.
