### ISSUE TITLE
Slack broken link

### ISSUE THREAD

**Issue by deepakvashist** [udacity/dlnd-issue-reports#492]
Hi, i'm new student and i'm trying to access Slack course link (https://dlf-slack.udacity.com/) but this link are broken.

**Comment by lcrucks** [comment]
The slack itself is nd101.slack.com, but I'll forward this along to our community manager to see check on the new student link.

**Comment by lcrucks** [comment]
Internal Ticket: https://udacity.atlassian.net/browse/DLND-1370

**Comment by afshan-udacity** [comment]
Hi, the link is actually: https://deep-learning-slack.udacity.com/

Can you link me to where you found that other link and I can fix it. Thanks!
