### ISSUE TITLE
FAQ for project submissions has dead link

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#493]
https://review.udacity.com/#!/submissions/student-faq

My project didn’t receive a status of "Exceeds Specifications" - why is that?
Exceeds Specifications is no longer used for Project Reviews. All submissions will receive a response of either “Meets Specifications” or “Requires Changes”. You can find more info here.

The linked to page:
https://discussions.udacity.com/t/exceeds-specifications-will-be-retired-on-march-31/161702

Says: Sorry, you don't have access to that topic!

**Comment by lcrucks** [comment]
You've found a pretty old link there (the forums post was alerting students to a policy change from 2 years ago); I'll request that that FAQ page is updated.  (There seems to be no reason to let people know that a change was made 2 years after the fact.)

Internal Ticket: https://udacity.atlassian.net/browse/DLND-1372
