### ISSUE TITLE
Potential improvement for def test_generator (project 4

### ISSUE THREAD

**Issue by PierceEigirthon** [udacity/dlnd-issue-reports#495]
output = generator(z, out_channel_dim, False) may get some people a bit confused on why they are not passing the tests. I've defined my generator as def generator(z, out..., alpha = 0.2, is_train = True). Since this functions third argument is alpha and not is_train it will never pass the test, even though there is nothing wrong with the function itself. So I guess it might be a bit confusing for some people if that happens.

Very simple potential solution (not really efficient tho) I got out the top of my head would be something like:

Try:
output = generator(z, out_channel_dim, False)
......
 assert mock_variable_scopre.call_arg.......
......
except:
output = generator(z, out_channel_dim, , False)
......
 assert mock_variable_scopre.call_arg.......
......

just a thought

**Comment by Ortalarel** [comment]
Thank you for the feedback. We are looking into it.
