### ISSUE TITLE
Lesson 7 Chapter 13 correct hyperlink

### ISSUE THREAD

**Issue by RahulMetangale** [udacity/dlnd-issue-reports#497]
Dorpout hyperlink open feedforward. Correct link should be https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/1a0c733f-e9a5-4ffb-a905-a7a2de1975bf/concepts/05d1b01f-191e-4b45-8e93-469aa0e05877

**Comment by Ortalarel** [comment]
The link to dropout directs you to the dropout video. I am not sure which error you are referring to.
