### ISSUE TITLE
waffle board for non-course-specific items?

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#499]
For example, issues, feedback, or recommendations for:
  - course content / classroom layout (at the "classroom" level ie, would apply to all courses, and/or all nanodegree courses)
  - mentorship
  - general website issues (no login required)

Mentorship: allow us to send a rating, comment, or "change mentor" request at anytime, rather than having to wait for the weekly prompt.

Search Udacity for courses was broken the other week.  It was broken whether I was logged out or logged in.  Dunno if it's been fixed.  
(I do not remember the specifics offhand, so no details to add at this time). 

Suggestion: Add a link to said waffle boards within the classroom, if they exist.

**Comment by Ortalarel** [comment]
Thank you for the feedback
