### ISSUE TITLE
Link to project 1 is not provided

### ISSUE THREAD

**Issue by dalex01** [udacity/dlnd-issue-reports#5]

**Comment by dalex01** [comment]
Or I can't find it.
Here: https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/9027814e-e801-44f5-a416-fff0504482ed/project

**Comment by adarsh0806** [comment]
It's at the bottom of the page.

**Comment by oritavital** [comment]
There is a link to the zip file to download in the bottom of that page
