### ISSUE TITLE
C2.L6.S2: clarify role of Keras and Tensorflow

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#504]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

"Compiling the Keras model calls the backend (tensorflow, theano, etc.) and binds.."

This sentence makes no sense to me.  

Scanning Keras and Tensorflow and Caffe does not give me any insight on how these are used in conjunction with each other, or what role each plays in deep learning, as compared with the code we wrote thus far.

Both this lecture, and the library pages assume a prior knowledge of this space beyond what we have encountered in the course thus far.

High Level Overview:  
It would be helpful to indicate what relation Keras/Theano has to Tensorflow/Caffe.  What role do the two different classes of software play in relation to one another.  How do they relate to deep learning? How do the 2 libraries compare to what we did in previous lessons and in Project 1.  Why are 2 different software libraries needed instead of one?  

Please add a high level overview of what how Keras and Tensorflow relate to each other, and how they work in relation to how we coded our neural networks up to this point.  How and why are there 2 segregated, but interdependent libraries to handle the one deep learning task ?

**Comment by Ortalarel** [comment]
Thank you for comment.
