### ISSUE TITLE
C2.L6.S2: minor typos

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#505]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

We'll specify the loss function to be categorical_crossentropy which can be used when there are only two classes, and specify adam as the optimizer (which is a reasonable default when speed is a priority). And finally, we can specify what metrics we want to evaluate the model with. Here we'll use accuracy.

Suggested edit:  
1) `accuracy` should have code highlighting
2) missing comma
3) recommend splitting long compound sentences into separate sentences.
4) minor sentence rewording for readability, and grammatical correctness.

We'll specify the loss function to be `categorical_crossentropy`, which can be used when there are only two classes.  We'll specify `adam` as the optimizer, which is a reasonable default when speed is a priority. Finally, we can specify the metrics we want to evaluate the model with. Here we'll use `accuracy`.

(could also indicate why "accuracy" was chosen)

**Comment by Ortalarel** [comment]
Thank you for your comments.
