### ISSUE TITLE
C2.L6.S2: minor edits for readability

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#506]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/7c042ed0-08e7-4138-ad78-1a8d671d5da5/concepts/7c3d9b4c-206d-4430-9459-c78357181d9a

Current:  
The model is trained with the fit() method, through the following command that specifies the number of training epochs and the message level (how much information we want displayed on the screen during training).

Suggestions:
1) comma should not be there.
2) Split into 2 sentences.
3) remove unnecessary words for clarity.

Proposed:  
The model is trained with the `fit()` method. 
The following command specifies the number of training epochs, and the message level (how much information is displayed on the screen during training).

**Comment by Ortalarel** [comment]
Thank you for you feedback.
