### ISSUE TITLE
C2.L6.S2 typo in student admissions notebook

### ISSUE THREAD

**Issue by SherylHohman** [udacity/dlnd-issue-reports#510]
Deep-learning repo:
student-admissions-keras/StudentAdmissions.ipynb

https://github.com/udacity/deep-learning/blob/master/student-admissions-keras/StudentAdmissionsKeras.ipynb

is:
Use the get_dummies function in numpy in order to one-hot encode the data.

what  needs fixed:
Issue:
`get_dummies` is pandas, not numpy
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.get_dummies.html

should be: 
Use the get_dummies function in pandas in order to one-hot encode the data.

**Comment by lcrucks** [comment]
Fixed
