### ISSUE TITLE
S6.L9.S6 - distorted audio in video

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#511]
Section 6 ('RL'), Lesson 9 (DQN), Step 6 (Deep Q Network)

Distorted audio clipping in video at ~2:58 - 3:05

**Comment by sbbogdan** [comment]
Direct link: https://youtu.be/GgtR_d1OB-M?t=178

**Comment by Ortalarel** [comment]
Thank you! We will fix that.
