### ISSUE TITLE
In `build_nn` function, `rnn_size` seems to be redundant. TV Script Project 3.

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#513]
Check out this https://discussions.udacity.com/t/build-nn-use-of-rnn-size/619939

Fix `build_nn` function by removing `rnn_size` parameter as it may cause confusion to the students. https://github.com/udacity/deep-learning/blob/master/tv-script-generation/dlnd_tv_script_generation.ipynb

**Comment by Ortalarel** [comment]
Thank you for your comment.
