### ISSUE TITLE
Cannot use multi-layer LSTM in Jupyter Notebook in Sentiment Analysis with RNNs

### ISSUE THREAD

**Issue by VikramRadhakrishnan** [udacity/dlnd-issue-reports#514]
In the Sentiment Analysis with RNNs section, the Jupyter Notebook provided currently uses lstm_layers = 1 in the code. The notebook suggests that if we increase the number of layers, we should be able to overcome under-fitting and get higher accuracy. However, when I change the lstm_layers to something higher than 1, for example, lstm_layers = 5, I get the following error:

ValueError: Dimensions must be equal, but are 512 and 556 for 'rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/MatMul_1' (op: 'MatMul') with input shapes: [500,512], [556,1024].

I don't think this particular Notebook was tested for more than 1 layer.

**Comment by Ortalarel** [comment]
Thank you for the comments. For issues of these nature please use our slack group and forums.
