### ISSUE TITLE
Incomplete downloads to Android App

### ISSUE THREAD

**Issue by jetojedno** [udacity/dlnd-issue-reports#516]
I download the DLND content for offline usage.  Several times the downloaded content appears to be incomplete, so it will not load / display / whatever in the App.

Most recent example was in the Autoencoders section on CNNs.

**Comment by jetojedno** [comment]
![Screenshot_2018-03-05-18-44-28.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a9f87f386e13900146816de/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc6416743e7951ee7a28c8b77cf2102343434d0eee1e020a17b8eb8339a3be3478dc5802e4803c5c7cc46817f8b8831ee909b3258f5d99a4fedb1294b7607caddecd5d340c041083fe5837a09d4bcc51fe4ae24f57b65e.png)

**Comment by Ortalarel** [comment]
Internal mobile ticket: https://udacity.atlassian.net/browse/MOBA-1195

thank you
