### ISSUE TITLE
Bad behaviour from Android App

### ISSUE THREAD

**Issue by jetojedno** [udacity/dlnd-issue-reports#517]
The Android App is almost impossible to use.  Because of auto-play, and various other uncontrollable "features," it's not fit for purpose.

There are certain things you need to do, as a student following the course, which you can't do:
- go back to the previous video
- skip over videos to get to the next unwatched video, if you're using more than one device.
- go back to the menu if part way through a video
- see a list of the contents (videos, quizzes etc.) of a section.

Can I suggest that the developers get a range of devices on which to test their product (and do so both portrait & landscape), and try to develop a list of normal activities for a student following a course, to use for testing.  Standard stuff!

**Comment by Ortalarel** [comment]
Internal mobile ticket: https://udacity.atlassian.net/browse/MOBA-1195

thank you
