### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ybarraj** [udacity/dlnd-issue-reports#518]
The forms link in deep learning lesson 1.5 is broken.

**Comment by ybarraj** [comment]
![Screen Shot 2018-03-07 at 7.07.26 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa09b3494d89d0013fc5825/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f46b7191a37ff1122c4f5d595ecc3c4a4356bcbbd671f3e57862804e0ee5d9650970cf3440fdbb8a1dea07ee208a4ed3beb58f48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df44be54a50a61b3462e7742431.png)

**Comment by lcrucks** [comment]
@ybarraj The forums link works; it's possible that you have don't have the correct permissions.  Assuming you are in a current DLND cohort (and therefore should have permissions), you can get permissions by going through the Udacity site to the forums.  (They will generate when you go through the forums link in the 'Resources' tab.) . If you should have permissions, and that *doesn't* work, I would recommend emailing deeplearning-support@udacity.com so we can get your permissions worked out.
