### ISSUE TITLE
S6.FinalProject.Step9 - redundant comment line in last code block

### ISSUE THREAD

**Issue by sbbogdan** [udacity/dlnd-issue-reports#520]
Issue: The following comment line is included twice in the final code block of the Final Project, Step #9.

# Compute action gradients (derivative of Q values w.r.t. to actions)
# Compute action gradients (derivative of Q values w.r.t. to actions)
action_gradients = K.gradients(Q_values, actions)

Resolution: Remove the additional '# Compute action gradients (derivative of Q values w.r.t. to actions)' comment from the code block.

**Comment by lcrucks** [comment]
Hello,

Could you provide a link to where you are looking?  I can't locate this.

**Comment by sbbogdan** [comment]
This was in reference to the prior quadcopter project, there is no Step 9 in the new project. This was, however, associated with the Critic code (now: Final Project - Step 5), but it looks like it has been corrected in the latest incarnation. 

Here's the link (the problem has been fixed - see text at bottom):
https://classroom.udacity.com/nanodegrees/nd101/parts/7d0218b1-1a81-4d49-95f7-14b015020851/modules/691b7845-f7d8-413d-90c7-971cd5016b5c/lessons/fef7e79a-0941-460b-936c-d24c759ff700/concepts/50c9b848-c212-4ba5-a468-7298b81c0c01

You can close this bug, unless you are still using the old quadcopter project somewhere and this duplication of comment/content exist (e.g. Machine Learning ND).
