### ISSUE TITLE
Bug in DCGAN-SVHN notebook

### ISSUE THREAD

**Issue by VikramRadhakrishnan** [udacity/dlnd-issue-reports#523]
In the DCGAN section, I encounter this error when I run the provided notebook. The error occurs when I run the train function.

Inputs to operation gradients/discriminator/Maximum_2_grad/Select_1 of type Select must have the same size and shape.  Input 0: [128,4,4,256] != input 1: [128,256,4,4]

I am using TF version 1.5

**Comment by lcrucks** [comment]
Hi Vikram,

I could not reproduce this error; you may want to post this on the forums (discussions.udacity.com)
