### ISSUE TITLE
Bug in DeepFaces Unit Test

### ISSUE THREAD

**Issue by mark5udacity** [udacity/dlnd-issue-reports#524]
Starting on line 125/126, line 126 should clearly be asserting tensor shape for g_loss, not d_loss

 _assert_tensor_shape(d_loss, [], 'Discriminator Loss')
_assert_tensor_shape(d_loss, [], 'Generator Loss')

**Comment by lcrucks** [comment]
Hi Mark,

Where precisely is this?

**Comment by mark5udacity** [comment]
Hey Luke,

Thanks for reaching out.

I hope the following link helps:
https://github.com/udacity/deep-learning/blob/master/face_generation/problem_unittests.py#L126

**Comment by lcrucks** [comment]
Fixed
