### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by BerkOFF** [udacity/dlnd-issue-reports#526]

**Comment by BerkOFF** [comment]
https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/c03e2d61-77be-4a7e-a380-b7ade8b062e5

is giving me 404
supposed to point to cross-entropy lesson

**Comment by lcrucks** [comment]
Internal Link: https://udacity.atlassian.net/browse/DLND-1409
