### ISSUE TITLE
defects in Dermatologist AI downloaded content

### ISSUE THREAD

**Issue by jetojedno** [udacity/dlnd-issue-reports#528]
I downloaded all the content for the Dermatologist AI module to my Android tablet, and it won't load / proceed without a working network connection.

I download the content as the mobile network on my commute is present but unreliable ... the software seems to be trying to use the network if it "thinks" there's a network present, even if the content has been downloaded & is cached on the device ... or the download bundle is incomplete.

**Comment by lcrucks** [comment]
Internal mobile ticket: https://udacity.atlassian.net/browse/MOBA-1195
