### ISSUE TITLE
update projects to recent software versions

### ISSUE THREAD

**Issue by jetojedno** [udacity/dlnd-issue-reports#529]
The dog project is requiring tensorflow 1.0.0 which was released February 15, 2017.  This causes problems as many needed packages are not sufficiently backwards compatible so a lot of time is wasted getting the environment set up.  In the end, I couldn't get a version of cudnn compatible with tf 1.0.0 and cuda 8.0 and the nvidia drivers I had installed so had to hope the software I wrote would be backwards compatible with the specified environment.

It would be much better if the projects are regularly updated to more recent versions, say between 3 and 6 months old.

**Comment by lcrucks** [comment]
Thanks for reporting this!  I'll see what is inherent with using Keras and how it can be updated.
