### ISSUE TITLE
Does the parameter “states” have a typo in DDPG class?

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#530]
I think the parameter “states” should be “state” as there is no “states” in the function body of DDPG act method. Can you confirm?

![states](https://user-images.githubusercontent.com/21355015/37783228-c2e9fffc-2e16-11e8-9473-d63dd5660eb5.png)

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLND-1424

**Comment by alexisbcook** [comment]
changed. thanks!
