### ISSUE TITLE
OpenAI Taxi website

### ISSUE THREAD

**Issue by rahul-ahuja** [udacity/dlnd-issue-reports#531]
In Lesson 7: Mini-Project OpenAI Taxi. the link https://gym.openai.com/envs/Taxi-v1/

I have trouble downloading the best solution from the OpenAI link;
https://gym.openai.com/evaluations/eval_fQB5PUJLQAKyuWvM3U6oA/

![screen shot 2018-03-23 at 10 06 41 pm](https://user-images.githubusercontent.com/21355015/37865942-61be013e-2fa5-11e8-9423-6b22912df9f0.png)

Also tried to sign in with Github, but I get the error.

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLND-1423
