### ISSUE TITLE
broken RL paper link

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#532]
https://classroom.udacity.com/nanodegrees/nd101/parts/7d0218b1-1a81-4d49-95f7-14b015020851/modules/38c16ab9-91e8-44ce-a0ce-ae1b9ba12146/lessons/4894b062-f2ed-4f31-95bc-f28a90f7acff/concepts/c6a9bf61-1311-4fb3-bdef-74cd7b94eacb

The pdf link [this paper](http://www-all.cs.umass.edu/pubs/1995_96/singh_s_ML96.pdf) is not working

**Comment by Ortalarel** [comment]
The issue is fixed. Thank you for your comment.
