### ISSUE TITLE
Missing video in Lesson 2: CNNs

### ISSUE THREAD

**Issue by pdudero** [udacity/dlnd-issue-reports#537]
…between step 3 and step 4?
Because in step 4 Alexis keeps referring to things learned in “the last video” that are not contained in step 3!
Step 3, “How computers interpret images”, ended with one-hot-encoding the labels of the MNIST digits.
Step 4, “MLPs for image classification”, starts with the CNN layer model, and assumes that you’ve seen keras code in python before, and “relu” activation functions, and “remember we learned about dropout layers”, and what-not.

So where did the video in between go? It’s quite jarring to have the instructor suddenly refer to things that were never introduced as if they already had!

**Comment by pdudero** [comment]
This issue can be closed. The real problem is that the classroom navigation clues led me to believe that I was done with Lesson 2 ("All requirements have been satisfied!") after the bike sharing data project, when in fact there were 3 more modules to complete!

**Comment by lcrucks** [comment]
Thanks for the update!
