### ISSUE TITLE
Python 2 or 3 ?

### ISSUE THREAD

**Issue by viennej** [udacity/dlnd-issue-reports#54]
In the Anaconda  part, you mention:
"For this Nanodegree, we will be using Python 3 almost exclusively."

But the LS video of Sira'j about regression was using a Python 2.6+ version, I had to "fix" its code to get it run on Python 3+.

**Comment by clapollo** [comment]
Closing this issue. We are using Python 3 "almost" exclusively. But that implies that sometimes we don't. We can't change the code used in Siraj's videos, but the vast majority of the code in this class uses Python 3.
