### ISSUE TITLE
Project 4: "dlnd_face_generation" fails with "AttributeError: 'numpy.ndarray' object has no attribute 'mask'"

### ISSUE THREAD

**Issue by manish** [udacity/dlnd-issue-reports#540]

**Comment by manish** [comment]
[dlnd_face_generation.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5bef4c701d4b00141d49a6/125516c66e82c728ace21e0d46ec989427bd85a88cec8044a153f58628522e7c2746ef696097ec22ba416f43554d4ba449500940f5f0d87aa5be3e258c080becd03b577dc33903b0aac04ee155e57dd205d0f4ae805ec2ea3724e2898c4c3d1e001989fa5d31b2d4.pdf) The output

**Comment by gmsharpe** [comment]
I'm getting the above error when using the GPU enabled workspace provided by Udacity.... is there a way to fix this, or do I just have to wait for Udacity to get around to fixing it themselves?

**Comment by stimut** [comment]
It was posted in Slack that a workaround is to run '!pip install matplotlib --upgrade' in a cell, and then restart the kernel.

Source: https://dl-nd.slack.com/archives/C3R94FHPD/p1523850550000180?thread_ts=1523361916.000477&cid=C3R94FHPD

**Comment by Ortalarel** [comment]
Thank you for these notes. We are aware of the issue and prioritized it with our engineering team.

**Comment by gustavf** [comment]
Why did this get closed? It's still an issue.
