### ISSUE TITLE
I can't enroll deep learning nano degree

### ISSUE THREAD

**Issue by macgebi** [udacity/dlnd-issue-reports#544]
- When I press start button in the page below, it sends me to the payment page of Deep Learning Foundation Nanodegree, not Deep Learning Nanodegree.
So I registered, and waited for the lecture open, but I realized that other students were watching Deep Learning Nanodegree class room instead of foundation nanodegree.

- Even I cancelled the payment, foundation nanodegree is still in my classroom list, and still it sends me to the foundation nano degree classroom payment page.

**Comment by macgebi** [comment]
This is what I can see.
![what_i_am_seeing.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf918b5791ad001363400e/125516c66e82c728ace21e0d46ff9c9b37bd8a968ee48050a158f99a2e046b313916ac217586f76ae5002e59575718a848510e15fff18b7ea0e23c718b0a03e4d4694d68d47f40f2ecdd42e64bef62994597b7b5804dc5ea3e20e28986483f1f051e9bb2.jpg)

**Comment by macgebi** [comment]
This is another student's view.
![Screen Shot 2018-04-12 at 9.48.31 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5acf918b5791ad001363400e/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f16b7191a371f116234f5c5e5edd3c4a4356bcbbd671f3e57862804e0ee5d9650970cf3440fdbb8a1dea07ee208a4ed3beb58f48d2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e44856a4173761e5732431.png)

**Comment by macgebi** [comment]
To be sure, this is not just typo error. the class doesn't start.

**Comment by macgebi** [comment]
This issue is addressed by asking udacity support. I heard that it was caused by wrong class version(?) and fixed by updating my class data.

**Comment by macgebi** [comment]
I tried to close but I can't.

**Comment by Ortalarel** [comment]
Hi, to make sure, is all ok now?

**Comment by macgebi** [comment]
Yes. Everything is fine now. Thanks.
