### ISSUE TITLE
Transfer Learning in Lesson 2 - library versions need to be re-visited

### ISSUE THREAD

**Issue by emmaggie** [udacity/dlnd-issue-reports#545]
E.g. In the instructions for Mac/Linux, tensorflow is listed as 0.11.0. Pip contains versions from 0.12.0 on.

**Comment by emmaggie** [comment]
![Screen Shot 2018-04-13 at 8.11.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ad05a9f126fa80011524309/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f06b7191a370f1132a4f5b595ecc3c4a4356bcbbd671f3e57862804e0ee5d9650970cf3440fdbb8a1dea07ee208a4ed3beb58f48d2f42f67b6d5db1063474f4dcbed5727a29841c95df448e74956a511356be4732431.png)

**Comment by emmaggie** [comment]
Everything worked perfect with: tf 0.12.0,  numpy==1.14.2, moviepy==0.2.3.2, Pillow==5.1.0, scipy==0.18.1

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/VOS-350.

Thanks for reporting this!
