### ISSUE TITLE
C2.L1.S11 Both number of weights and points is n - confusing

### ISSUE THREAD

**Issue by mikhailchetin** [udacity/dlnd-issue-reports#548]
Number of points is n, number of weights (dimensions) is 2

**Comment by lcrucks** [comment]
From this video: https://classroom.udacity.com/nanodegrees/nd101/parts/73a7fe8e-4354-4362-939d-a8bf2bae870d/modules/e6a4e4a1-98a9-4afe-a744-7ae6a59c01b8/lessons/93d158ce-25e1-4fc1-a187-162982e3cef7/concepts/dc837952-c0d8-43fc-921c-f1ffe316c795

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLND-1447
