### ISSUE TITLE
[Quadcopter Project ] equation of angular position equation is wrongly given in physics_sim.py

### ISSUE THREAD

**Issue by Vivekkmr91** [udacity/dlnd-issue-reports#549]
equation of angular position equation is wrongly given in physics_sim.py:
It is given as
angles = self.pose[3:] + self.angular_v * self.dt + 0.5 * self.angular_accels * self.angular_accels * self.dt
However it should be 
angles = self.pose[3:] + self.angular_v * self.dt + 0.5 * self.angular_accels  * self.dt**2

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/MLND-1309

**Comment by lcrucks** [comment]
Fixed
