### ISSUE TITLE
Heaviside Step Function

### ISSUE THREAD

**Issue by japurma** [udacity/dlnd-issue-reports#55]
The lesson on Perceptron states that "This function returns a 0 if the linear combination it sees is negative or equal to zero, and 1 in any other case ".  Shortly after it states that "the activation function will only return a 1 if grades and test are 0!"  The content contradicts itself.

**Comment by Brok-Bucholtz** [comment]
@japurma,

We changed the sentence from "This function returns a 0 if the linear combination it sees is negative or equal to zero, and 1 in any other case..." to "This function returns a 1 if the linear combination it sees is positive or equal to zero, and 0 in any other case..."

Thanks for letting us know.  Let us know if you see anything else and we'll be happy to fix it.

**Comment by jillsthebest** [comment]
" positive or equal to zero, and 0 in any other case..."  The "or equal to zero" part contradicts the picture below it which shows that only less than zero will return a zero, not equal to zero, and the coding quiz also sticks to this!
