### ISSUE TITLE
Batch_Normalization_Exercises.ipynb description discrepancy

### ISSUE THREAD

**Issue by jetojedno** [udacity/dlnd-issue-reports#553]
In the text in Batch_Normalization_Exercises.ipynb it says:
"strides of 1x1 on layers with odd depths"
but the code says:
"if layer_depth % 3 == 0"

This would only be accurate if the "odd" layers were translated into 2 graph layers and the "even" layers one (which is possible, but should be explained if true).

**Comment by lcrucks** [comment]
Internal ticket: https://udacity.atlassian.net/browse/DLND-1445
