### ISSUE TITLE
Cannot submit Project 2: Dog Breed

### ISSUE THREAD

**Issue by jcane86** [udacity/dlnd-issue-reports#554]
If I try to submit it form the Workspace, it just hangs with no progress indication.
If I go on to page 3 of the lesson and click submit project there, it just takes me straight to the dialog for rating the lesson.

**Comment by lcrucks** [comment]
Hi @jcane86, have you written in to deeplearning-support@udacity.com?  (The workspace issue is known and being worked on, but not being able to submit elsewhere is new; trying from your account would be helpful).

**Comment by jcane86** [comment]
Hi, the issue is solved. The problem I was having is that the submit dialog shows the smileys to rate the lesson, and if you click on them, you lose the chance to submit. I figured it out now and was able to submit successfully. Thanks!
