### ISSUE TITLE
More space on workspace request

### ISSUE THREAD

**Issue by lcrucks** [udacity/dlnd-issue-reports#558]
More space on workspace request from student: Hi, I'm trying to do the mini-project in part 3 lesson 8 (Deep Learning for Cancer Detection with Sebastian Thrun). The mini-project requires about 12 GB for training, validation, and testing datasets. The GPU Workspace you provide us does't seem to support that much storage. I suggest upscaling the space to 20GB for each student. That would really help!

**Comment by Ortalarel** [comment]
Thank you for the feedback,  we are looking into it
