### ISSUE TITLE
May's Cohort Google Calendar is empty

### ISSUE THREAD

**Issue by deveweber** [udacity/dlnd-issue-reports#563]
Hey, guys, there are no any dates in google calendar from Deadline Policy:
https://calendar.google.com/calendar/embed?src=knowlabs.com_3a3g6p2c7ibeio8of6sbh1c52s@group.calendar.google.com&ctz=America/Los_Angeles

**Comment by jemdiggity** [comment]
Why is this issue closed? The calendar is still empty.
