### ISSUE TITLE
Simulation in project 5 does not stop after crash or runtime

### ISSUE THREAD

**Issue by KarlisJ** [udacity/dlnd-issue-reports#564]
/Users/karlis/Projects/phyton/dl_nanodegree/RL-Quadcopter-2/physics_sim.py:116: RuntimeWarning: overflow encountered in double_scalars
  C_T = max(.12 - .07*max(0, J)-.1*max(0, J)**2, 0)
/Users/karlis/Projects/phyton/dl_nanodegree/RL-Quadcopter-2/physics_sim.py:69: RuntimeWarning: overflow encountered in square
  linear_drag = 0.5 * self.rho * self.find_body_velocity()**2 * self.areas * self.C_d

**Comment by lcrucks** [comment]
Hi,

Could you detail exactly what error you are getting in the project (beyond the traceback; when and where does it occur?  What's the context?)

**Comment by KarlisJ** [comment]
Sorry for late update. I finally found my own mistake. I had overwritten the `done` variable in my task definition.
