### ISSUE TITLE
Anna KaRNNa exercise is VERY confusing

### ISSUE THREAD

**Issue by pdudero** [udacity/dlnd-issue-reports#567]

**Comment by pdudero** [comment]
I saw on the waffle board issue number #525 titled "output reshaping in Anna KaRNNa exercise is confusing". I'm sorry to have to report that just about the whole exercise is VERY confusing. I've seen many questions from students spread out over several forums, a lot of the same kinds of questions. My own confusion is documented in these two posts:

https://discussions.udacity.com/t/anna-karnna-making-training-mini-batches-instructions/682257
https://discussions.udacity.com/t/more-questions-about-sequence-batching-and-lstm-dimension-parameters/683218/11

The issues that I see:
1) I understand that use of the terms "batch_size", "num_steps", etc. are derived from the outside community. That doesn't change the fact that they are being horribly abused. Having just come out of the CNN lessons, batch_size sounds like the number of elements in a batch, and num_steps sounds like either the number of times you step the window, or else what was called the "stride" in CNN space. But here it is neither. Terribly confusing.

2) Similarly words like "sequence" and "cell" and "batch" are used to mean different things even within the notebook. Exhibit A is the diagram under the "Making mini-batches" heading. First [1 2 3 4 5 6] is described as a sequence. Immediately below that it says that the sequence length is 3. So 6 = 3 now. "Cell" can mean either a single LSTM, or a bunch of "units" (never explicitly defined) wrapped together, or even a whole network with a bunch of layers. How many times did I go around with the forum mentor because when I said "cell" I apparently meant "unit"?

3) Then there's the orientation of the batch as it is fed into the network. That is, which numbers are presented *simultaneously* to the network? The diagram under "Making mini-batches" definitely indicates that "1 2 3" is fed first, and then "7 8 9", and then presumably "4 5 6" and then "10 11 12". A video made by Mat (I think), "sequence_batches.mp4", and posted as an answer to questions on the forums, shows the same thing. That's confusing because that means that words and sentences are being interleaved, essentially jumbled together. How can the network possibly learn sequences longer than "num_steps" this way?  In fact if you dig down in my second post the forum mentor, rahul_ahuja, says that 1 and 7 are processed together, and then 2 and 8, and then 3 and 9, which makes better sense, since order is preserved both within batches and between batches. But it directly contradicts the diagram and the video. So which am I supposed to believe?

4) The lesson suffers tremendously from not having a network architecture diagram. I tried explaining this to the forum mentor, as you can see in the second post, but I kept getting unrolled diagrams and diagrams and discussions of LSTM internals like the four gates, etc. I wanted to see and understand how inputs are mapped into the first hidden layer of the LSTM network. The diagram I mentioned in the previous point, and also the diagram at the very top, gives the strong impression that there is no cross-connection between the input layer and the hidden layer, but rather each character goes to its own "cell", or "unit", or whatever you're supposed to call it. However, the hyperparameter defaults in the notebook set "lstm_size" to 128, and batch_size to 10. One-hot encoding the inputs multiples 10 by 84 to get 840 inputs.  How are these inputs mapped to the first LSTM hidden layer without cross-connecting? The same problem exists if I've got the orientation wrong, and it's num_steps that I should be paying attention to. And how are the hidden layers connected to each other? And how is the last hidden layer connected to the outputs? A diagram that explicitly depicts the entire network, as we have seen with every previous lesson in the ND, complete with depictions of what "batch_size", "lstm_size", "num_steps", M, N, L, etc. etc. would be tremendously helpful and would clear up a lot of confusion.

Thanks.

**Comment by Ortalarel** [comment]
Thank you for the feedback. We are looking into ways to improve.
