### ISSUE TITLE
Project deadlines by cohort missing new(June) cohort

### ISSUE THREAD

**Issue by bkapsalis** [udacity/dlnd-issue-reports#582]
[Deadline Policy-Lesson 1](https://classroom.udacity.com/nanodegrees/nd101/parts/bc6e1adc-6149-4d81-a96e-68baf31c1810/modules/1a8f9ad8-4c56-451b-b1d8-0600424a8a67/lessons/6f134b7e-7dbf-4c83-a5d7-dff0d048b6c0/concepts/fde81b4c-59dc-488e-b2da-354b37b296ce)

**Comment by markwusinich** [comment]
Came here to say this. (and some others that I will look to see if someone else posted, and add if not)

**Comment by lcarbajal** [comment]
Same issue here!

**Comment by markwusinich** [comment]
If you search for #June_cohort, you can join it. It is just not defaulting to the list of subscribed things.

**Comment by eric4867** [comment]
adding support for this issue
