### ISSUE TITLE
Broken link:  best practices for revising and resubmitting your project

### ISSUE THREAD

**Issue by angelmtenor** [udacity/dlnd-issue-reports#60]
At the bottom of  Project Review Page:

'Learn the best practices for revising and resubmitting your project'  results in 404 error

**Comment by lcrucks** [comment]
Is it possible to specify where exactly this link is?  I can't find any location on P1 with the link.

**Comment by angelmtenor** [comment]
From my account I can find it at the bottom of this page:
https://review.udacity.com/#!/reviews/346691

--------------------------------------------------------------------------

Best practices for your project resubmission

Ben shares 5 helpful tips to get you through revising and resubmitting your project.

[ Watch Video (3:01)](https://review.udacity.com/)

**Comment by lcrucks** [comment]
This issue's been fixed (forgot to update this).
