### ISSUE TITLE
No information about November class

### ISSUE THREAD

**Issue by Jasmin25** [udacity/dlnd-issue-reports#612]
https://classroom.udacity.com/nanodegrees/nd101/parts/09023a41-74e1-4df6-8404-5020a0c94369/modules/81544872-f3d6-42aa-82a5-fba50ec612b2/lessons/45350b27-a8d5-4c90-a9b3-146ba8fb23bb/concepts/a456aee3-2f0b-4871-ba0e-11068515a591

**Comment by ghost** [comment]
+1. Came to report same, missing November deadlines in the course
