### ISSUE TITLE
Udacity DLNF has lost track of the courses i have already completed

### ISSUE THREAD

**Issue by PythonWillRule** [udacity/dlnd-issue-reports#62]
Went back to week 1 to search for some information that I thought was there now it thinks I have not completed  lessons 2 and 3 and shows 4,5,6 are completed which is correct and & partially completed.

**Comment by jzemel** [comment]
This is the same for me - all of lessons 1-7 appear to be incomplete and no record of my quizzes.

**Comment by clapollo** [comment]
I know that sometimes, if some content gets updated, it will show up as incomplete in the classroom again. It can be a nice hint if you want to go back to see what's new, but you aren't required to complete anything but the projects in order to graduate.
