### ISSUE TITLE
Heaviside step Function - Re-open please

### ISSUE THREAD

**Issue by jillsthebest** [udacity/dlnd-issue-reports#64]
" positive or equal to zero, and 0 in any other case..."  The "or equal to zero" part contradicts the picture below it which shows that only less than zero will return a zero, not equal to zero, and the coding quiz also sticks to this!

**Comment by Brok-Bucholtz** [comment]
@jillsthebest,

I think you're reading the sentence incorrectly.  The step function returns a ***1*** if the linear combination is equal to or greater than 0.  The picture is also showing this:
https://d17h27t6h515a5.cloudfront.net/topher/2017/January/588ea1f6_step-function/step-function.gif

I broke down the sentence to make it easer to read. I changed the line from
"This function returns a 1 if the linear combination it sees is positive or equal to zero, and 0 in any other case (when the linear combination is negative)."
to
"This function returns a **0** if the linear combination is less than 0. It returns a **1** if the linear combination is positive or equal to zero."

If I'm misunderstanding you, please reopen this issue.
