### ISSUE TITLE
Content needs more 'rigor'

### ISSUE THREAD

**Issue by jillsthebest** [udacity/dlnd-issue-reports#67]
"Implementing backpropagation
Now we've seen that the error in the output layer is
<latex>
and the error in the hidden layer is
<more latex>"

The latex here is different that the latex used in the section before this one (Backpropogation)

Please stick to the same format of variables for consistency , in other words, use the same naming conventions. 

Just like having 15 different variables all referencing the same single variable is bad programming, it's also bad practice to constantly switch variable names in these lessons because it makes the reading harder to follow, just like it makes code harder to follow.

That's my lecture for the day.

**Comment by oritavital** [comment]
Thanks for your feedback.
We have multiple content developers working on this course, which might be the reason for this kind of issues.
But we'll make sure to have a unified convention to avoid similar problems.
