### ISSUE TITLE
activation interchanged with output without saying so

### ISSUE THREAD

**Issue by jillsthebest** [udacity/dlnd-issue-reports#69]
The word activation appears out of thin air to refer to what was previously referenced as the output of a perceptron. I don't recall activation being defined anywhere, so it's probably best to introduce the term activation earlier. Specifically, in the code, it's "hidden_activations" but in the text it's "hidden_output"

**Comment by jillsthebest** [comment]
p.s. see https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/329a736b-1700-43d4-9bf0-753cc461bebc/lessons/dc37fa92-75fd-4d41-b23e-9659dde80866/concepts/b2bbdc9a-9f48-4735-b408-71cf67f5b000

**Comment by clapollo** [comment]
I went in and added a bit about what activation functions are and the term activations. I also changed the code in the backdrop quiz to use hidden_output instead because I don't think there is really a need to start calling them hidden_activations there anyway.
