### ISSUE TITLE
Lesson 9, 3. Materials - filename too long

### ISSUE THREAD

**Issue by leehanchung** [udacity/dlnd-issue-reports#71]
Supporting materials filenames too long to be extracted under Windows 10 w/ WinRAR.

**Comment by clapollo** [comment]
Can you specify the name of the section and lesson instead of just the numbers? Things have moved around and when I look at lesson 9, 3, there are no files.

**Comment by mcleonard** [comment]
This might be Andrew Trask's lessons. The notebooks have long names

**Comment by mcleonard** [comment]
@clapollo I think this might be related to the really long titles of the notebooks in Andrew's lesson. Think you could shorten them in your revising of the lesson?

**Comment by clapollo** [comment]
@mcleonard Yep, I'll take care of that with the other updates tonight.

**Comment by clapollo** [comment]
I've updated the Trask lesson files, but I'm going to leave this issue open until I've had a change to go over all the files in the repo and make sure nothing is too long.

**Comment by clapollo** [comment]
Ok, latest commit to GitHub has removed all the super long names. Not sure if there's a specific length we should be shooting for, but since we are using GitHub directly for most things instead of zips, I'm hoping we won't have any more problems.
