### ISSUE TITLE
In lesson 9-5, the MSE is wrong

### ISSUE THREAD

**Issue by Gan-Jiang** [udacity/dlnd-issue-reports#78]
From my understanding, the mse is compute the sum of square error, in which the error is the distance between y_true and y_prediction, BUT the instructor is using the distance between the prediction to the line.

**Comment by 0xpantera** [comment]
Values in the line are the predictions (y_prediction). The points not in the line are the true values (y_true). The difference between each true value (y_true) outside the line and each predicted value (y_prediction) is the error for each value. The mean of the those errors squared is the MSE.

**Comment by Gan-Jiang** [comment]
It still has not been processed...

**Comment by etendue** [comment]
I come across this too.  Distance/Boundary between sample point and line/hyper-plane is used in Support Vector Machine, if I remember correctly

**Comment by clapollo** [comment]
I think this is shown correctly, so I'm closing the issue. As Francososa pointed out, the line values **are** the predictions. If you still think it is incorrect, please reopen the issue with more details explaining why.
