### ISSUE TITLE
Sentiment Classification - Mini Project 1.ipynb

### ISSUE THREAD

**Issue by Adosha** [udacity/dlnd-issue-reports#79]
It is impossible to understand what should I do in the project without watching to answer.

It is better to add markdown block with description like:

# Project 1

Create Counters (https://docs.python.org/2/library/collections.html#collections.Counter) positive_words and negative_words with words which contained in positive reviews and in negative reviews. Print first 10 in each list.

in fact printing is useless if student will not delete stopwords.
It is not so hard to do.

**Comment by nehal96** [comment]
I agree. I think there should be hints pushing us in the right direction, or introducing us to conveniences (like in this case, Counters) that will help us.

**Comment by clapollo** [comment]
New version of these lessons includes much more guidance throughout. Thanks!
