### ISSUE TITLE
can't find anaconda in my mac

### ISSUE THREAD

**Issue by luckyarthur** [udacity/dlnd-issue-reports#81]
i just use the graphic install package to install anaconda on my mac, buy i cant use terminal command to use it, i installed it in the Application directory and i change the terminal path to it, it just doesnt work

**Comment by oritavital** [comment]
Hi, can you please post your question on the forum? that is a better place to get answers to specific problems.
We try to use this board to keep track of problems with the content itself.

Thanks!
Orit
