### ISSUE TITLE
Request for Centralized Resources page

### ISSUE THREAD

**Issue by lyndond** [udacity/dlnd-issue-reports#84]
In the Q&A on Friday at around 44:30 someone mentioned that they'd like a Centralized Resource page. I think this is a great idea! Perhaps 1 page with subheaders for each Lesson and underneath each subheader would be a list of recommended supplemental reading or material. Perhaps followed by a 1-line description of which lectures it relates to/how it relates to what we've learned. Right now it feels a little bit all over the place to have to sift through each lesson to get to the supplemental material.

**Comment by oritavital** [comment]
We have this spreadsheet that one of the students created
https://docs.google.com/spreadsheets/d/1NZtIxDWiJ_B0UKhIDUk-wTZAT3Fxfh-fGwcQKXg1bQU/edit#gid=0
It contains many links and other useful information.
