### ISSUE TITLE
Intro to NN - 6. Perceptron

### ISSUE THREAD

**Issue by 0xpantera** [udacity/dlnd-issue-reports#87]
Below "Summing the Input Data"  sub-title the weights used in the example are set as: 

W​eight grades = -1
​Weight test = −0.2
​
However, when explaining the process of linear combination on the paragraph below the weights are reversed as:

Wgrades * Xgrades + Wtest * Xtest = -0.2 * Xgrades -1 * Xtest.

**Comment by clapollo** [comment]
Hey Brok, I didn't realize you were assigned to this, but I fixed it while doing something else.
