### ISSUE TITLE
Unable to access forums via georgia tech udacity login

### ISSUE THREAD

**Issue by jfalkson** [udacity/dlnd-issue-reports#90]

**Comment by jfalkson** [comment]
I am a former OMS student who used the Georgia Tech udacity login when I payed for my nano degree foundation program. The forum link redirects me to the main DLND page, so I am entirely blocked from accessing the course forums.

**Comment by oritavital** [comment]
Please open a support ticket for that (deeplearning-support@udacity.com), so we can assist you. Thanks
