### ISSUE TITLE
tflearn on Windows

### ISSUE THREAD

**Issue by dhilgarth** [udacity/dlnd-issue-reports#91]
[This](https://classroom.udacity.com/nanodegrees/nd101/parts/2a9dba0b-28eb-4b0e-acfa-bdcf35680d90/modules/e0ad6969-6321-437a-8279-d9b20a7cd00a/lessons/cec79d13-b41a-4c61-9441-eada5b39c9e6/concepts/c29b0417-7bef-48bd-b499-ed79676b7d02) should contain information on how to make tflearn work in Windows

Details: https://nd101.slack.com/messages/code/convo/C3Q7CGF35-1486233843.006213/

**Comment by clapollo** [comment]
Changed installation instructions to include these tips.
