### ISSUE TITLE
use np.multiply and reshape

### ISSUE THREAD

**Issue by cbhyphen** [udacity/dlnd-issue-reports#92]
For understanding the math behind backprop, I think it would be better to use `np.multiply` instead of the `*` operator for element-wise multiplication.  Also for creating a column vector from a row, `.reshape` instead of `[:, None]`.  The math was much easier to follow when I used these.

For example, in the solution to 14:

```
del_err_hidden = np.dot(del_err_output, weights_hidden_output) * \
                 hidden_layer_output * (1 - hidden_layer_output)
```

the gradient error for the hidden input could be broken up and defined first as the hidden input gradients (maybe `np.multiply` here if only to clarify that there is a vector of 2):

```
gradient_hidden_output = np.multiply(hidden_layer_output, (1 - hidden_layer_output))
```

and then:

```
del_err_hidden = del_err_output * np.multiply(weights_hidden_output, gradient_hidden_output)
```

For change in weights to input layer:

```
delta_w_i_o = learnrate * del_err_hidden * x[:, None]
```

using reshape:

```
delta_w_h_i = learnrate * np.multiply(del_err_hidden, x.reshape(len(x), 1))
```

this might also help for intuition.

**Comment by clapollo** [comment]
This syntax is pretty common. Rather than change it, I've added a section explaining it inside the NumPy refresher lesson Data in NumPy.
