### ISSUE TITLE
Intro to NN - 11. Gradient Descent

### ISSUE THREAD

**Issue by onemodtwo** [udacity/dlnd-issue-reports#95]
On this page the word "error" is used variously to refer to the error function, the error at each layer and even, at one point, to the delta value, which is the layer error multiplied by the layer gradient. It would be much clearer if the terminology were tightened up somewhat.

**Comment by clapollo** [comment]
We've made various changes over the weeks in an attempt to be more consistent. However, there may be places we've missed. I'm going to close this issue for now, but if you come across a specific instance of a term you think is used in an incorrect, confusing, or inconsistent manner, please open a new issue and provide the details there. Thank you!
