### ISSUE TITLE
Disconnect with Expectation setup and Course progress requirements causing delayed progress

### ISSUE THREAD

**Issue by dev-usa** [udacity/dlnd-issue-reports#97]
Copy pasting from Slack - https://nd101.slack.com/archives/feedback/p1486446437008706

@siraj and @Udacity - guys, there seems to be a huge disconnect on setting the expectations for a new comer to this course vs. what is happening in the course

1. Basic python knowledge was the pre-requisite on this course as per what was mentioned before sign-up. - seems to be a big deviation from what is expected out of this course.

2. To be successful in completing the first part of the course at least, I see we are using a lot of linear algebra / differential calculus. While I am not against learning something new, I would have liked both of them added to pre-requisites.
Please note that not everyone who opted for the course is a full time student and has to spend their time doing day jobs (I am one of them and I am sure there are more).  It has been 10 years since I am out of college doing web development in java and I did not have to use calculus in my last 10 years… which puts me back to almost at the beginning of my learning curve for differential calculus.

3. The time commitment recommended is 3 hours per week. I am sure this is for someone as smart as Siraj - I wish I was as smart after looking at all those videos and his energy (hi Siraj :slightly_smiling_face: ). The first part of the course took me at least 15 hours so far (including following all those links to the Khan academy and the online books) and I have not event started on the project and why you ask - Oh, thats because I have a day job and personal commitments and the "3 hour per week and a little more than that for the first week” seems to be an exaggeration. I apologize if my comments sound hard. It is after managing so much of my time trying accomplish everything on time and with an intension for setting better expectations in future.

4. I am still playing catch up with the "lesson 7” and yet to start on the project. Is anyone in the same boat looking for more time to complete the project?

Is Udacity planning to provide any extension to the timeline for project submission given that there is a disconnect?

**Comment by dhilgarth** [comment]
I absolutely agree! I actually have the feeling that we are beta testers for this course and Udacity is learning along the way. Not something that I want to happen on a course that costs 400 bucks

**Comment by oritavital** [comment]
Hi

I believe these issues has been addressed on Slack before, but I wanted to summarize it here as well.
We are aware that on the first session, we had some misalignments between the published pre-reqs and the actual ones needed. Also the time commitment was low than it should be.

We have updated that information, and were also working with the students to help catch up.

I hope that by now you feel better about the program, but if any issue comes up, please reach out to us using our support email (deeplearning-support@udacity.com)

Thanks
Orit
